/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ActivityLogsResponse,
  DocumentStagesResponse,
  DocumentStatsResponse,
  ErrorModel,
  GetActivityLogsParams,
  GetUserGrowthParams,
  ReportStatsResponse,
  SessionStatsResponse,
  SystemOverviewResponse,
  UserGrowthResponse,
  UserStatsResponse
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * @summary Get recent admin activity logs
 */
export type getActivityLogsResponse200 = {
  data: ActivityLogsResponse
  status: 200
}

export type getActivityLogsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getActivityLogsResponseSuccess = (getActivityLogsResponse200) & {
  headers: Headers;
};
export type getActivityLogsResponseError = (getActivityLogsResponseDefault) & {
  headers: Headers;
};

export type getActivityLogsResponse = (getActivityLogsResponseSuccess | getActivityLogsResponseError)

export const getGetActivityLogsUrl = (params?: GetActivityLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/dashboard/activity-logs?${stringifiedParams}` : `/api/v1/admin/dashboard/activity-logs`
}

export const getActivityLogs = async (params?: GetActivityLogsParams, options?: RequestInit): Promise<getActivityLogsResponse> => {
  
  return customFetch<getActivityLogsResponse>(getGetActivityLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get document pipeline stage breakdown
 */
export type getDocumentStagesResponse200 = {
  data: DocumentStagesResponse
  status: 200
}

export type getDocumentStagesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDocumentStagesResponseSuccess = (getDocumentStagesResponse200) & {
  headers: Headers;
};
export type getDocumentStagesResponseError = (getDocumentStagesResponseDefault) & {
  headers: Headers;
};

export type getDocumentStagesResponse = (getDocumentStagesResponseSuccess | getDocumentStagesResponseError)

export const getGetDocumentStagesUrl = () => {


  

  return `/api/v1/admin/dashboard/document-stages`
}

export const getDocumentStages = async ( options?: RequestInit): Promise<getDocumentStagesResponse> => {
  
  return customFetch<getDocumentStagesResponse>(getGetDocumentStagesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get document ingestion statistics
 */
export type getDocumentStatsResponse200 = {
  data: DocumentStatsResponse
  status: 200
}

export type getDocumentStatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDocumentStatsResponseSuccess = (getDocumentStatsResponse200) & {
  headers: Headers;
};
export type getDocumentStatsResponseError = (getDocumentStatsResponseDefault) & {
  headers: Headers;
};

export type getDocumentStatsResponse = (getDocumentStatsResponseSuccess | getDocumentStatsResponseError)

export const getGetDocumentStatsUrl = () => {


  

  return `/api/v1/admin/dashboard/document-stats`
}

export const getDocumentStats = async ( options?: RequestInit): Promise<getDocumentStatsResponse> => {
  
  return customFetch<getDocumentStatsResponse>(getGetDocumentStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get content report statistics
 */
export type getReportStatsResponse200 = {
  data: ReportStatsResponse
  status: 200
}

export type getReportStatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getReportStatsResponseSuccess = (getReportStatsResponse200) & {
  headers: Headers;
};
export type getReportStatsResponseError = (getReportStatsResponseDefault) & {
  headers: Headers;
};

export type getReportStatsResponse = (getReportStatsResponseSuccess | getReportStatsResponseError)

export const getGetReportStatsUrl = () => {


  

  return `/api/v1/admin/dashboard/report-stats`
}

export const getReportStats = async ( options?: RequestInit): Promise<getReportStatsResponse> => {
  
  return customFetch<getReportStatsResponse>(getGetReportStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get session statistics
 */
export type getSessionStatsResponse200 = {
  data: SessionStatsResponse
  status: 200
}

export type getSessionStatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getSessionStatsResponseSuccess = (getSessionStatsResponse200) & {
  headers: Headers;
};
export type getSessionStatsResponseError = (getSessionStatsResponseDefault) & {
  headers: Headers;
};

export type getSessionStatsResponse = (getSessionStatsResponseSuccess | getSessionStatsResponseError)

export const getGetSessionStatsUrl = () => {


  

  return `/api/v1/admin/dashboard/session-stats`
}

export const getSessionStats = async ( options?: RequestInit): Promise<getSessionStatsResponse> => {
  
  return customFetch<getSessionStatsResponse>(getGetSessionStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get system overview indicators
 */
export type getSystemOverviewResponse200 = {
  data: SystemOverviewResponse
  status: 200
}

export type getSystemOverviewResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getSystemOverviewResponseSuccess = (getSystemOverviewResponse200) & {
  headers: Headers;
};
export type getSystemOverviewResponseError = (getSystemOverviewResponseDefault) & {
  headers: Headers;
};

export type getSystemOverviewResponse = (getSystemOverviewResponseSuccess | getSystemOverviewResponseError)

export const getGetSystemOverviewUrl = () => {


  

  return `/api/v1/admin/dashboard/system-overview`
}

export const getSystemOverview = async ( options?: RequestInit): Promise<getSystemOverviewResponse> => {
  
  return customFetch<getSystemOverviewResponse>(getGetSystemOverviewUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get user growth by tier
 */
export type getUserGrowthResponse200 = {
  data: UserGrowthResponse
  status: 200
}

export type getUserGrowthResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getUserGrowthResponseSuccess = (getUserGrowthResponse200) & {
  headers: Headers;
};
export type getUserGrowthResponseError = (getUserGrowthResponseDefault) & {
  headers: Headers;
};

export type getUserGrowthResponse = (getUserGrowthResponseSuccess | getUserGrowthResponseError)

export const getGetUserGrowthUrl = (params?: GetUserGrowthParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/dashboard/user-growth?${stringifiedParams}` : `/api/v1/admin/dashboard/user-growth`
}

export const getUserGrowth = async (params?: GetUserGrowthParams, options?: RequestInit): Promise<getUserGrowthResponse> => {
  
  return customFetch<getUserGrowthResponse>(getGetUserGrowthUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Get user statistics
 */
export type getUserStatsResponse200 = {
  data: UserStatsResponse
  status: 200
}

export type getUserStatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getUserStatsResponseSuccess = (getUserStatsResponse200) & {
  headers: Headers;
};
export type getUserStatsResponseError = (getUserStatsResponseDefault) & {
  headers: Headers;
};

export type getUserStatsResponse = (getUserStatsResponseSuccess | getUserStatsResponseError)

export const getGetUserStatsUrl = () => {


  

  return `/api/v1/admin/dashboard/user-stats`
}

export const getUserStats = async ( options?: RequestInit): Promise<getUserStatsResponse> => {
  
  return customFetch<getUserStatsResponse>(getGetUserStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

