/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateSectorRequest,
  CreateSectorResponseBody,
  CreateTagRequest,
  CreateTagResponseBody,
  ErrorModel,
  ListSectorsParams,
  ListSectorsResponseBody,
  ListTagsParams,
  ListTagsResponseBody,
  SectorResponse,
  TagResponse,
  UpdateSectorRequest,
  UpdateSectorResponseBody,
  UpdateTagRequest,
  UpdateTagResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * @summary List sectors
 */
export type listSectorsResponse200 = {
  data: ListSectorsResponseBody
  status: 200
}

export type listSectorsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listSectorsResponseSuccess = (listSectorsResponse200) & {
  headers: Headers;
};
export type listSectorsResponseError = (listSectorsResponseDefault) & {
  headers: Headers;
};

export type listSectorsResponse = (listSectorsResponseSuccess | listSectorsResponseError)

export const getListSectorsUrl = (params?: ListSectorsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/sectors?${stringifiedParams}` : `/api/v1/admin/sectors`
}

export const listSectors = async (params?: ListSectorsParams, options?: RequestInit): Promise<listSectorsResponse> => {
  
  return customFetch<listSectorsResponse>(getListSectorsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Create sector
 */
export type createSectorResponse200 = {
  data: CreateSectorResponseBody
  status: 200
}

export type createSectorResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createSectorResponseSuccess = (createSectorResponse200) & {
  headers: Headers;
};
export type createSectorResponseError = (createSectorResponseDefault) & {
  headers: Headers;
};

export type createSectorResponse = (createSectorResponseSuccess | createSectorResponseError)

export const getCreateSectorUrl = () => {


  

  return `/api/v1/admin/sectors`
}

export const createSector = async (createSectorRequest: NonReadonly<CreateSectorRequest>, options?: RequestInit): Promise<createSectorResponse> => {
  
  return customFetch<createSectorResponse>(getCreateSectorUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createSectorRequest,)
  }
);}
  

/**
 * @summary Delete sector
 */
export type deleteSectorResponse200 = {
  data: UpdateSectorResponseBody
  status: 200
}

export type deleteSectorResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteSectorResponseSuccess = (deleteSectorResponse200) & {
  headers: Headers;
};
export type deleteSectorResponseError = (deleteSectorResponseDefault) & {
  headers: Headers;
};

export type deleteSectorResponse = (deleteSectorResponseSuccess | deleteSectorResponseError)

export const getDeleteSectorUrl = (id: string,) => {


  

  return `/api/v1/admin/sectors/${id}`
}

export const deleteSector = async (id: string, options?: RequestInit): Promise<deleteSectorResponse> => {
  
  return customFetch<deleteSectorResponse>(getDeleteSectorUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * @summary Get sector
 */
export type getSectorResponse200 = {
  data: SectorResponse
  status: 200
}

export type getSectorResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getSectorResponseSuccess = (getSectorResponse200) & {
  headers: Headers;
};
export type getSectorResponseError = (getSectorResponseDefault) & {
  headers: Headers;
};

export type getSectorResponse = (getSectorResponseSuccess | getSectorResponseError)

export const getGetSectorUrl = (id: string,) => {


  

  return `/api/v1/admin/sectors/${id}`
}

export const getSector = async (id: string, options?: RequestInit): Promise<getSectorResponse> => {
  
  return customFetch<getSectorResponse>(getGetSectorUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Update sector
 */
export type updateSectorResponse200 = {
  data: UpdateSectorResponseBody
  status: 200
}

export type updateSectorResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateSectorResponseSuccess = (updateSectorResponse200) & {
  headers: Headers;
};
export type updateSectorResponseError = (updateSectorResponseDefault) & {
  headers: Headers;
};

export type updateSectorResponse = (updateSectorResponseSuccess | updateSectorResponseError)

export const getUpdateSectorUrl = (id: string,) => {


  

  return `/api/v1/admin/sectors/${id}`
}

export const updateSector = async (id: string,
    updateSectorRequest: NonReadonly<UpdateSectorRequest>, options?: RequestInit): Promise<updateSectorResponse> => {
  
  return customFetch<updateSectorResponse>(getUpdateSectorUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateSectorRequest,)
  }
);}
  

/**
 * @summary List tags
 */
export type listTagsResponse200 = {
  data: ListTagsResponseBody
  status: 200
}

export type listTagsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listTagsResponseSuccess = (listTagsResponse200) & {
  headers: Headers;
};
export type listTagsResponseError = (listTagsResponseDefault) & {
  headers: Headers;
};

export type listTagsResponse = (listTagsResponseSuccess | listTagsResponseError)

export const getListTagsUrl = (params?: ListTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/tags?${stringifiedParams}` : `/api/v1/admin/tags`
}

export const listTags = async (params?: ListTagsParams, options?: RequestInit): Promise<listTagsResponse> => {
  
  return customFetch<listTagsResponse>(getListTagsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Create tag
 */
export type createTagResponse200 = {
  data: CreateTagResponseBody
  status: 200
}

export type createTagResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createTagResponseSuccess = (createTagResponse200) & {
  headers: Headers;
};
export type createTagResponseError = (createTagResponseDefault) & {
  headers: Headers;
};

export type createTagResponse = (createTagResponseSuccess | createTagResponseError)

export const getCreateTagUrl = () => {


  

  return `/api/v1/admin/tags`
}

export const createTag = async (createTagRequest: NonReadonly<CreateTagRequest>, options?: RequestInit): Promise<createTagResponse> => {
  
  return customFetch<createTagResponse>(getCreateTagUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTagRequest,)
  }
);}
  

/**
 * @summary Delete tag
 */
export type deleteTagResponse200 = {
  data: UpdateTagResponseBody
  status: 200
}

export type deleteTagResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteTagResponseSuccess = (deleteTagResponse200) & {
  headers: Headers;
};
export type deleteTagResponseError = (deleteTagResponseDefault) & {
  headers: Headers;
};

export type deleteTagResponse = (deleteTagResponseSuccess | deleteTagResponseError)

export const getDeleteTagUrl = (id: string,) => {


  

  return `/api/v1/admin/tags/${id}`
}

export const deleteTag = async (id: string, options?: RequestInit): Promise<deleteTagResponse> => {
  
  return customFetch<deleteTagResponse>(getDeleteTagUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * @summary Get tag
 */
export type getTagResponse200 = {
  data: TagResponse
  status: 200
}

export type getTagResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getTagResponseSuccess = (getTagResponse200) & {
  headers: Headers;
};
export type getTagResponseError = (getTagResponseDefault) & {
  headers: Headers;
};

export type getTagResponse = (getTagResponseSuccess | getTagResponseError)

export const getGetTagUrl = (id: string,) => {


  

  return `/api/v1/admin/tags/${id}`
}

export const getTag = async (id: string, options?: RequestInit): Promise<getTagResponse> => {
  
  return customFetch<getTagResponse>(getGetTagUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * @summary Update tag
 */
export type updateTagResponse200 = {
  data: UpdateTagResponseBody
  status: 200
}

export type updateTagResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateTagResponseSuccess = (updateTagResponse200) & {
  headers: Headers;
};
export type updateTagResponseError = (updateTagResponseDefault) & {
  headers: Headers;
};

export type updateTagResponse = (updateTagResponseSuccess | updateTagResponseError)

export const getUpdateTagUrl = (id: string,) => {


  

  return `/api/v1/admin/tags/${id}`
}

export const updateTag = async (id: string,
    updateTagRequest: NonReadonly<UpdateTagRequest>, options?: RequestInit): Promise<updateTagResponse> => {
  
  return customFetch<updateTagResponse>(getUpdateTagUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTagRequest,)
  }
);}
  

