/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddCategoryConditionRequest,
  AddCategoryConditionResponseBody,
  CreateCategoryRequest,
  CreateCategoryResponseBody,
  DeleteCategoryResponseBody,
  ErrorModel,
  RemoveCategoryConditionResponseBody,
  SetCategoryTranslationsRequest,
  SetCategoryTranslationsResponseBody,
  UpdateCategoryRequest,
  UpdateCategoryResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Creates a new guide category with optional translations and conditions.
 * @summary Create category
 */
export type createCategoryResponse200 = {
  data: CreateCategoryResponseBody
  status: 200
}

export type createCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createCategoryResponseSuccess = (createCategoryResponse200) & {
  headers: Headers;
};
export type createCategoryResponseError = (createCategoryResponseDefault) & {
  headers: Headers;
};

export type createCategoryResponse = (createCategoryResponseSuccess | createCategoryResponseError)

export const getCreateCategoryUrl = () => {


  

  return `/api/v1/admin/guides/categories`
}

export const createCategory = async (createCategoryRequest: NonReadonly<CreateCategoryRequest>, options?: RequestInit): Promise<createCategoryResponse> => {
  
  return customFetch<createCategoryResponse>(getCreateCategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCategoryRequest,)
  }
);}
  

/**
 * Removes a visibility condition from a category.
 * @summary Remove category condition
 */
export type removeCategoryConditionResponse200 = {
  data: RemoveCategoryConditionResponseBody
  status: 200
}

export type removeCategoryConditionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type removeCategoryConditionResponseSuccess = (removeCategoryConditionResponse200) & {
  headers: Headers;
};
export type removeCategoryConditionResponseError = (removeCategoryConditionResponseDefault) & {
  headers: Headers;
};

export type removeCategoryConditionResponse = (removeCategoryConditionResponseSuccess | removeCategoryConditionResponseError)

export const getRemoveCategoryConditionUrl = (condId: string,) => {


  

  return `/api/v1/admin/guides/categories/conditions/${condId}`
}

export const removeCategoryCondition = async (condId: string, options?: RequestInit): Promise<removeCategoryConditionResponse> => {
  
  return customFetch<removeCategoryConditionResponse>(getRemoveCategoryConditionUrl(condId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Deletes a guide category.
 * @summary Delete category
 */
export type deleteCategoryResponse200 = {
  data: DeleteCategoryResponseBody
  status: 200
}

export type deleteCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteCategoryResponseSuccess = (deleteCategoryResponse200) & {
  headers: Headers;
};
export type deleteCategoryResponseError = (deleteCategoryResponseDefault) & {
  headers: Headers;
};

export type deleteCategoryResponse = (deleteCategoryResponseSuccess | deleteCategoryResponseError)

export const getDeleteCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/categories/${id}`
}

export const deleteCategory = async (id: string, options?: RequestInit): Promise<deleteCategoryResponse> => {
  
  return customFetch<deleteCategoryResponse>(getDeleteCategoryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates an existing guide category.
 * @summary Update category
 */
export type updateCategoryResponse200 = {
  data: UpdateCategoryResponseBody
  status: 200
}

export type updateCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCategoryResponseSuccess = (updateCategoryResponse200) & {
  headers: Headers;
};
export type updateCategoryResponseError = (updateCategoryResponseDefault) & {
  headers: Headers;
};

export type updateCategoryResponse = (updateCategoryResponseSuccess | updateCategoryResponseError)

export const getUpdateCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/categories/${id}`
}

export const updateCategory = async (id: string,
    updateCategoryRequest: NonReadonly<UpdateCategoryRequest>, options?: RequestInit): Promise<updateCategoryResponse> => {
  
  return customFetch<updateCategoryResponse>(getUpdateCategoryUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCategoryRequest,)
  }
);}
  

/**
 * Adds a visibility condition to a category.
 * @summary Add category condition
 */
export type addCategoryConditionResponse200 = {
  data: AddCategoryConditionResponseBody
  status: 200
}

export type addCategoryConditionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type addCategoryConditionResponseSuccess = (addCategoryConditionResponse200) & {
  headers: Headers;
};
export type addCategoryConditionResponseError = (addCategoryConditionResponseDefault) & {
  headers: Headers;
};

export type addCategoryConditionResponse = (addCategoryConditionResponseSuccess | addCategoryConditionResponseError)

export const getAddCategoryConditionUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/categories/${id}/conditions`
}

export const addCategoryCondition = async (id: string,
    addCategoryConditionRequest: NonReadonly<AddCategoryConditionRequest>, options?: RequestInit): Promise<addCategoryConditionResponse> => {
  
  return customFetch<addCategoryConditionResponse>(getAddCategoryConditionUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addCategoryConditionRequest,)
  }
);}
  

/**
 * Replaces all translations for a category.
 * @summary Set category translations
 */
export type setCategoryTranslationsResponse200 = {
  data: SetCategoryTranslationsResponseBody
  status: 200
}

export type setCategoryTranslationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type setCategoryTranslationsResponseSuccess = (setCategoryTranslationsResponse200) & {
  headers: Headers;
};
export type setCategoryTranslationsResponseError = (setCategoryTranslationsResponseDefault) & {
  headers: Headers;
};

export type setCategoryTranslationsResponse = (setCategoryTranslationsResponseSuccess | setCategoryTranslationsResponseError)

export const getSetCategoryTranslationsUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/categories/${id}/translations`
}

export const setCategoryTranslations = async (id: string,
    setCategoryTranslationsRequest: NonReadonly<SetCategoryTranslationsRequest>, options?: RequestInit): Promise<setCategoryTranslationsResponse> => {
  
  return customFetch<setCategoryTranslationsResponse>(getSetCategoryTranslationsUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setCategoryTranslationsRequest,)
  }
);}
  

