/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AdminListAllBlockedUsersParams,
  AdminListCommunityCategoriesParams,
  AdminListPostReportsParams,
  AdminListThreadBlockedUsersParams,
  AdminListThreadReportsParams,
  AdminListUserReportsParams,
  BlockReportedUserRequest,
  BlockReportedUserResponseBody,
  BlockUserRequest,
  BlockUserResponseBody,
  CreateCommunityCategoryRequest,
  CreateCommunityCategoryResponseBody,
  DeleteCommunityCategoryResponseBody,
  DeleteReportedContentResponseBody,
  ErrorModel,
  GetPostReportResponseBody,
  GetThreadReportResponseBody,
  GetUserReportResponseBody,
  ListAllBlockedUsersResponseBody,
  ListBlockedUsersResponseBody,
  ListCategoriesResponseBody,
  ListPostReportsResponseBody,
  ListThreadReportsResponseBody,
  ListUserReportsResponseBody,
  UpdateCommunityCategoryRequest,
  UpdateCommunityCategoryResponseBody,
  UpdatePostReportStatusRequest,
  UpdatePostReportStatusResponseBody,
  UpdateThreadReportStatusRequest,
  UpdateThreadReportStatusResponseBody,
  UpdateUserReportStatusRequest,
  UpdateUserReportStatusResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists all blocked users across all threads.
 * @summary List all blocked users (admin)
 */
export type adminListAllBlockedUsersResponse200 = {
  data: ListAllBlockedUsersResponseBody
  status: 200
}

export type adminListAllBlockedUsersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListAllBlockedUsersResponseSuccess = (adminListAllBlockedUsersResponse200) & {
  headers: Headers;
};
export type adminListAllBlockedUsersResponseError = (adminListAllBlockedUsersResponseDefault) & {
  headers: Headers;
};

export type adminListAllBlockedUsersResponse = (adminListAllBlockedUsersResponseSuccess | adminListAllBlockedUsersResponseError)

export const getAdminListAllBlockedUsersUrl = (params?: AdminListAllBlockedUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/blocks?${stringifiedParams}` : `/api/v1/admin/community/blocks`
}

export const adminListAllBlockedUsers = async (params?: AdminListAllBlockedUsersParams, options?: RequestInit): Promise<adminListAllBlockedUsersResponse> => {
  
  return customFetch<adminListAllBlockedUsersResponse>(getAdminListAllBlockedUsersUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists community categories including inactive ones.
 * @summary List community categories (admin)
 */
export type adminListCommunityCategoriesResponse200 = {
  data: ListCategoriesResponseBody
  status: 200
}

export type adminListCommunityCategoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListCommunityCategoriesResponseSuccess = (adminListCommunityCategoriesResponse200) & {
  headers: Headers;
};
export type adminListCommunityCategoriesResponseError = (adminListCommunityCategoriesResponseDefault) & {
  headers: Headers;
};

export type adminListCommunityCategoriesResponse = (adminListCommunityCategoriesResponseSuccess | adminListCommunityCategoriesResponseError)

export const getAdminListCommunityCategoriesUrl = (params?: AdminListCommunityCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/categories?${stringifiedParams}` : `/api/v1/admin/community/categories`
}

export const adminListCommunityCategories = async (params?: AdminListCommunityCategoriesParams, options?: RequestInit): Promise<adminListCommunityCategoriesResponse> => {
  
  return customFetch<adminListCommunityCategoriesResponse>(getAdminListCommunityCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a community category.
 * @summary Create community category
 */
export type adminCreateCommunityCategoryResponse200 = {
  data: CreateCommunityCategoryResponseBody
  status: 200
}

export type adminCreateCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminCreateCommunityCategoryResponseSuccess = (adminCreateCommunityCategoryResponse200) & {
  headers: Headers;
};
export type adminCreateCommunityCategoryResponseError = (adminCreateCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type adminCreateCommunityCategoryResponse = (adminCreateCommunityCategoryResponseSuccess | adminCreateCommunityCategoryResponseError)

export const getAdminCreateCommunityCategoryUrl = () => {


  

  return `/api/v1/admin/community/categories`
}

export const adminCreateCommunityCategory = async (createCommunityCategoryRequest: NonReadonly<CreateCommunityCategoryRequest>, options?: RequestInit): Promise<adminCreateCommunityCategoryResponse> => {
  
  return customFetch<adminCreateCommunityCategoryResponse>(getAdminCreateCommunityCategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCommunityCategoryRequest,)
  }
);}
  

/**
 * Deletes a community category.
 * @summary Delete community category
 */
export type adminDeleteCommunityCategoryResponse200 = {
  data: DeleteCommunityCategoryResponseBody
  status: 200
}

export type adminDeleteCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminDeleteCommunityCategoryResponseSuccess = (adminDeleteCommunityCategoryResponse200) & {
  headers: Headers;
};
export type adminDeleteCommunityCategoryResponseError = (adminDeleteCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type adminDeleteCommunityCategoryResponse = (adminDeleteCommunityCategoryResponseSuccess | adminDeleteCommunityCategoryResponseError)

export const getAdminDeleteCommunityCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/community/categories/${id}`
}

export const adminDeleteCommunityCategory = async (id: string, options?: RequestInit): Promise<adminDeleteCommunityCategoryResponse> => {
  
  return customFetch<adminDeleteCommunityCategoryResponse>(getAdminDeleteCommunityCategoryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates a community category.
 * @summary Update community category
 */
export type adminUpdateCommunityCategoryResponse200 = {
  data: UpdateCommunityCategoryResponseBody
  status: 200
}

export type adminUpdateCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminUpdateCommunityCategoryResponseSuccess = (adminUpdateCommunityCategoryResponse200) & {
  headers: Headers;
};
export type adminUpdateCommunityCategoryResponseError = (adminUpdateCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type adminUpdateCommunityCategoryResponse = (adminUpdateCommunityCategoryResponseSuccess | adminUpdateCommunityCategoryResponseError)

export const getAdminUpdateCommunityCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/community/categories/${id}`
}

export const adminUpdateCommunityCategory = async (id: string,
    updateCommunityCategoryRequest: NonReadonly<UpdateCommunityCategoryRequest>, options?: RequestInit): Promise<adminUpdateCommunityCategoryResponse> => {
  
  return customFetch<adminUpdateCommunityCategoryResponse>(getAdminUpdateCommunityCategoryUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCommunityCategoryRequest,)
  }
);}
  

/**
 * Lists post reports with optional status filter.
 * @summary List post reports (admin)
 */
export type adminListPostReportsResponse200 = {
  data: ListPostReportsResponseBody
  status: 200
}

export type adminListPostReportsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListPostReportsResponseSuccess = (adminListPostReportsResponse200) & {
  headers: Headers;
};
export type adminListPostReportsResponseError = (adminListPostReportsResponseDefault) & {
  headers: Headers;
};

export type adminListPostReportsResponse = (adminListPostReportsResponseSuccess | adminListPostReportsResponseError)

export const getAdminListPostReportsUrl = (params?: AdminListPostReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/reports/posts?${stringifiedParams}` : `/api/v1/admin/community/reports/posts`
}

export const adminListPostReports = async (params?: AdminListPostReportsParams, options?: RequestInit): Promise<adminListPostReportsResponse> => {
  
  return customFetch<adminListPostReportsResponse>(getAdminListPostReportsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Deletes a reported post and resolves the report.
 * @summary Delete reported post (admin)
 */
export type adminDeleteReportedPostResponse200 = {
  data: DeleteReportedContentResponseBody
  status: 200
}

export type adminDeleteReportedPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminDeleteReportedPostResponseSuccess = (adminDeleteReportedPostResponse200) & {
  headers: Headers;
};
export type adminDeleteReportedPostResponseError = (adminDeleteReportedPostResponseDefault) & {
  headers: Headers;
};

export type adminDeleteReportedPostResponse = (adminDeleteReportedPostResponseSuccess | adminDeleteReportedPostResponseError)

export const getAdminDeleteReportedPostUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/posts/${id}`
}

export const adminDeleteReportedPost = async (id: string, options?: RequestInit): Promise<adminDeleteReportedPostResponse> => {
  
  return customFetch<adminDeleteReportedPostResponse>(getAdminDeleteReportedPostUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a post report with reported content details.
 * @summary Get post report (admin)
 */
export type adminGetPostReportResponse200 = {
  data: GetPostReportResponseBody
  status: 200
}

export type adminGetPostReportResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminGetPostReportResponseSuccess = (adminGetPostReportResponse200) & {
  headers: Headers;
};
export type adminGetPostReportResponseError = (adminGetPostReportResponseDefault) & {
  headers: Headers;
};

export type adminGetPostReportResponse = (adminGetPostReportResponseSuccess | adminGetPostReportResponseError)

export const getAdminGetPostReportUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/posts/${id}`
}

export const adminGetPostReport = async (id: string, options?: RequestInit): Promise<adminGetPostReportResponse> => {
  
  return customFetch<adminGetPostReportResponse>(getAdminGetPostReportUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a post report status.
 * @summary Update post report status (admin)
 */
export type adminUpdatePostReportStatusResponse200 = {
  data: UpdatePostReportStatusResponseBody
  status: 200
}

export type adminUpdatePostReportStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminUpdatePostReportStatusResponseSuccess = (adminUpdatePostReportStatusResponse200) & {
  headers: Headers;
};
export type adminUpdatePostReportStatusResponseError = (adminUpdatePostReportStatusResponseDefault) & {
  headers: Headers;
};

export type adminUpdatePostReportStatusResponse = (adminUpdatePostReportStatusResponseSuccess | adminUpdatePostReportStatusResponseError)

export const getAdminUpdatePostReportStatusUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/posts/${id}/status`
}

export const adminUpdatePostReportStatus = async (id: string,
    updatePostReportStatusRequest: NonReadonly<UpdatePostReportStatusRequest>, options?: RequestInit): Promise<adminUpdatePostReportStatusResponse> => {
  
  return customFetch<adminUpdatePostReportStatusResponse>(getAdminUpdatePostReportStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePostReportStatusRequest,)
  }
);}
  

/**
 * Lists thread reports with optional status filter.
 * @summary List thread reports (admin)
 */
export type adminListThreadReportsResponse200 = {
  data: ListThreadReportsResponseBody
  status: 200
}

export type adminListThreadReportsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListThreadReportsResponseSuccess = (adminListThreadReportsResponse200) & {
  headers: Headers;
};
export type adminListThreadReportsResponseError = (adminListThreadReportsResponseDefault) & {
  headers: Headers;
};

export type adminListThreadReportsResponse = (adminListThreadReportsResponseSuccess | adminListThreadReportsResponseError)

export const getAdminListThreadReportsUrl = (params?: AdminListThreadReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/reports/threads?${stringifiedParams}` : `/api/v1/admin/community/reports/threads`
}

export const adminListThreadReports = async (params?: AdminListThreadReportsParams, options?: RequestInit): Promise<adminListThreadReportsResponse> => {
  
  return customFetch<adminListThreadReportsResponse>(getAdminListThreadReportsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Deletes a reported thread and resolves the report.
 * @summary Delete reported thread (admin)
 */
export type adminDeleteReportedThreadResponse200 = {
  data: DeleteReportedContentResponseBody
  status: 200
}

export type adminDeleteReportedThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminDeleteReportedThreadResponseSuccess = (adminDeleteReportedThreadResponse200) & {
  headers: Headers;
};
export type adminDeleteReportedThreadResponseError = (adminDeleteReportedThreadResponseDefault) & {
  headers: Headers;
};

export type adminDeleteReportedThreadResponse = (adminDeleteReportedThreadResponseSuccess | adminDeleteReportedThreadResponseError)

export const getAdminDeleteReportedThreadUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/threads/${id}`
}

export const adminDeleteReportedThread = async (id: string, options?: RequestInit): Promise<adminDeleteReportedThreadResponse> => {
  
  return customFetch<adminDeleteReportedThreadResponse>(getAdminDeleteReportedThreadUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a thread report with reported content details.
 * @summary Get thread report (admin)
 */
export type adminGetThreadReportResponse200 = {
  data: GetThreadReportResponseBody
  status: 200
}

export type adminGetThreadReportResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminGetThreadReportResponseSuccess = (adminGetThreadReportResponse200) & {
  headers: Headers;
};
export type adminGetThreadReportResponseError = (adminGetThreadReportResponseDefault) & {
  headers: Headers;
};

export type adminGetThreadReportResponse = (adminGetThreadReportResponseSuccess | adminGetThreadReportResponseError)

export const getAdminGetThreadReportUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/threads/${id}`
}

export const adminGetThreadReport = async (id: string, options?: RequestInit): Promise<adminGetThreadReportResponse> => {
  
  return customFetch<adminGetThreadReportResponse>(getAdminGetThreadReportUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a thread report status.
 * @summary Update thread report status (admin)
 */
export type adminUpdateThreadReportStatusResponse200 = {
  data: UpdateThreadReportStatusResponseBody
  status: 200
}

export type adminUpdateThreadReportStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminUpdateThreadReportStatusResponseSuccess = (adminUpdateThreadReportStatusResponse200) & {
  headers: Headers;
};
export type adminUpdateThreadReportStatusResponseError = (adminUpdateThreadReportStatusResponseDefault) & {
  headers: Headers;
};

export type adminUpdateThreadReportStatusResponse = (adminUpdateThreadReportStatusResponseSuccess | adminUpdateThreadReportStatusResponseError)

export const getAdminUpdateThreadReportStatusUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/threads/${id}/status`
}

export const adminUpdateThreadReportStatus = async (id: string,
    updateThreadReportStatusRequest: NonReadonly<UpdateThreadReportStatusRequest>, options?: RequestInit): Promise<adminUpdateThreadReportStatusResponse> => {
  
  return customFetch<adminUpdateThreadReportStatusResponse>(getAdminUpdateThreadReportStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateThreadReportStatusRequest,)
  }
);}
  

/**
 * Lists user reports with optional status filter.
 * @summary List user reports (admin)
 */
export type adminListUserReportsResponse200 = {
  data: ListUserReportsResponseBody
  status: 200
}

export type adminListUserReportsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListUserReportsResponseSuccess = (adminListUserReportsResponse200) & {
  headers: Headers;
};
export type adminListUserReportsResponseError = (adminListUserReportsResponseDefault) & {
  headers: Headers;
};

export type adminListUserReportsResponse = (adminListUserReportsResponseSuccess | adminListUserReportsResponseError)

export const getAdminListUserReportsUrl = (params?: AdminListUserReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/reports/users?${stringifiedParams}` : `/api/v1/admin/community/reports/users`
}

export const adminListUserReports = async (params?: AdminListUserReportsParams, options?: RequestInit): Promise<adminListUserReportsResponse> => {
  
  return customFetch<adminListUserReportsResponse>(getAdminListUserReportsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Gets a user report with reported user details.
 * @summary Get user report (admin)
 */
export type adminGetUserReportResponse200 = {
  data: GetUserReportResponseBody
  status: 200
}

export type adminGetUserReportResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminGetUserReportResponseSuccess = (adminGetUserReportResponse200) & {
  headers: Headers;
};
export type adminGetUserReportResponseError = (adminGetUserReportResponseDefault) & {
  headers: Headers;
};

export type adminGetUserReportResponse = (adminGetUserReportResponseSuccess | adminGetUserReportResponseError)

export const getAdminGetUserReportUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/users/${id}`
}

export const adminGetUserReport = async (id: string, options?: RequestInit): Promise<adminGetUserReportResponse> => {
  
  return customFetch<adminGetUserReportResponse>(getAdminGetUserReportUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Blocks the reported user from the thread and resolves the report.
 * @summary Block reported user (admin)
 */
export type adminBlockReportedUserResponse200 = {
  data: BlockReportedUserResponseBody
  status: 200
}

export type adminBlockReportedUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminBlockReportedUserResponseSuccess = (adminBlockReportedUserResponse200) & {
  headers: Headers;
};
export type adminBlockReportedUserResponseError = (adminBlockReportedUserResponseDefault) & {
  headers: Headers;
};

export type adminBlockReportedUserResponse = (adminBlockReportedUserResponseSuccess | adminBlockReportedUserResponseError)

export const getAdminBlockReportedUserUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/users/${id}/block`
}

export const adminBlockReportedUser = async (id: string,
    blockReportedUserRequest: NonReadonly<BlockReportedUserRequest>, options?: RequestInit): Promise<adminBlockReportedUserResponse> => {
  
  return customFetch<adminBlockReportedUserResponse>(getAdminBlockReportedUserUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockReportedUserRequest,)
  }
);}
  

/**
 * Updates a user report status.
 * @summary Update user report status (admin)
 */
export type adminUpdateUserReportStatusResponse200 = {
  data: UpdateUserReportStatusResponseBody
  status: 200
}

export type adminUpdateUserReportStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminUpdateUserReportStatusResponseSuccess = (adminUpdateUserReportStatusResponse200) & {
  headers: Headers;
};
export type adminUpdateUserReportStatusResponseError = (adminUpdateUserReportStatusResponseDefault) & {
  headers: Headers;
};

export type adminUpdateUserReportStatusResponse = (adminUpdateUserReportStatusResponseSuccess | adminUpdateUserReportStatusResponseError)

export const getAdminUpdateUserReportStatusUrl = (id: string,) => {


  

  return `/api/v1/admin/community/reports/users/${id}/status`
}

export const adminUpdateUserReportStatus = async (id: string,
    updateUserReportStatusRequest: NonReadonly<UpdateUserReportStatusRequest>, options?: RequestInit): Promise<adminUpdateUserReportStatusResponse> => {
  
  return customFetch<adminUpdateUserReportStatusResponse>(getAdminUpdateUserReportStatusUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserReportStatusRequest,)
  }
);}
  

/**
 * Lists blocked users for a specific thread.
 * @summary List blocked users in thread (admin)
 */
export type adminListThreadBlockedUsersResponse200 = {
  data: ListBlockedUsersResponseBody
  status: 200
}

export type adminListThreadBlockedUsersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminListThreadBlockedUsersResponseSuccess = (adminListThreadBlockedUsersResponse200) & {
  headers: Headers;
};
export type adminListThreadBlockedUsersResponseError = (adminListThreadBlockedUsersResponseDefault) & {
  headers: Headers;
};

export type adminListThreadBlockedUsersResponse = (adminListThreadBlockedUsersResponseSuccess | adminListThreadBlockedUsersResponseError)

export const getAdminListThreadBlockedUsersUrl = (id: string,
    params?: AdminListThreadBlockedUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/community/threads/${id}/blocks?${stringifiedParams}` : `/api/v1/admin/community/threads/${id}/blocks`
}

export const adminListThreadBlockedUsers = async (id: string,
    params?: AdminListThreadBlockedUsersParams, options?: RequestInit): Promise<adminListThreadBlockedUsersResponse> => {
  
  return customFetch<adminListThreadBlockedUsersResponse>(getAdminListThreadBlockedUsersUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Blocks a user from a thread as admin.
 * @summary Block user in thread (admin)
 */
export type adminBlockCommunityUserResponse200 = {
  data: BlockUserResponseBody
  status: 200
}

export type adminBlockCommunityUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminBlockCommunityUserResponseSuccess = (adminBlockCommunityUserResponse200) & {
  headers: Headers;
};
export type adminBlockCommunityUserResponseError = (adminBlockCommunityUserResponseDefault) & {
  headers: Headers;
};

export type adminBlockCommunityUserResponse = (adminBlockCommunityUserResponseSuccess | adminBlockCommunityUserResponseError)

export const getAdminBlockCommunityUserUrl = (id: string,) => {


  

  return `/api/v1/admin/community/threads/${id}/blocks`
}

export const adminBlockCommunityUser = async (id: string,
    blockUserRequest: NonReadonly<BlockUserRequest>, options?: RequestInit): Promise<adminBlockCommunityUserResponse> => {
  
  return customFetch<adminBlockCommunityUserResponse>(getAdminBlockCommunityUserUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockUserRequest,)
  }
);}
  

/**
 * Unblocks a user from a thread as admin.
 * @summary Unblock user in thread (admin)
 */
export type adminUnblockCommunityUserResponse200 = {
  data: BlockUserResponseBody
  status: 200
}

export type adminUnblockCommunityUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type adminUnblockCommunityUserResponseSuccess = (adminUnblockCommunityUserResponse200) & {
  headers: Headers;
};
export type adminUnblockCommunityUserResponseError = (adminUnblockCommunityUserResponseDefault) & {
  headers: Headers;
};

export type adminUnblockCommunityUserResponse = (adminUnblockCommunityUserResponseSuccess | adminUnblockCommunityUserResponseError)

export const getAdminUnblockCommunityUserUrl = (id: string,
    accountId: string,) => {


  

  return `/api/v1/admin/community/threads/${id}/blocks/${accountId}`
}

export const adminUnblockCommunityUser = async (id: string,
    accountId: string, options?: RequestInit): Promise<adminUnblockCommunityUserResponse> => {
  
  return customFetch<adminUnblockCommunityUserResponse>(getAdminUnblockCommunityUserUrl(id,accountId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

