/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddTranslationRequest,
  AddTranslationResponseBody,
  CampaignDetailResponse,
  CancelCampaignResponseBody,
  CreateCampaignRequest,
  CreateCampaignResponseBody,
  CreateTemplateRequest,
  CreateTemplateResponseBody,
  DeleteTemplateResponseBody,
  DeleteTranslationResponseBody,
  ErrorModel,
  ListCampaignsParams,
  ListCampaignsResponseBody,
  ListTemplatesParams,
  ListTemplatesResponseBody,
  QueueStatusResponse,
  RetryFailedParams,
  RetryFailedResponseBody,
  ScheduleCampaignResponseBody,
  TemplateDetailResponse,
  UpdateCampaignRequest,
  UpdateCampaignResponseBody,
  UpdateTemplateRequest,
  UpdateTemplateResponseBody,
  UpdateTranslationRequest,
  UpdateTranslationResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists notification campaigns with optional status filter.
 * @summary List campaigns
 */
export type listCampaignsResponse200 = {
  data: ListCampaignsResponseBody
  status: 200
}

export type listCampaignsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listCampaignsResponseSuccess = (listCampaignsResponse200) & {
  headers: Headers;
};
export type listCampaignsResponseError = (listCampaignsResponseDefault) & {
  headers: Headers;
};

export type listCampaignsResponse = (listCampaignsResponseSuccess | listCampaignsResponseError)

export const getListCampaignsUrl = (params?: ListCampaignsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/campaigns?${stringifiedParams}` : `/api/v1/admin/notifications/campaigns`
}

export const listCampaigns = async (params?: ListCampaignsParams, options?: RequestInit): Promise<listCampaignsResponse> => {
  
  return customFetch<listCampaignsResponse>(getListCampaignsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new notification campaign in draft status.
 * @summary Create campaign
 */
export type createCampaignResponse200 = {
  data: CreateCampaignResponseBody
  status: 200
}

export type createCampaignResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createCampaignResponseSuccess = (createCampaignResponse200) & {
  headers: Headers;
};
export type createCampaignResponseError = (createCampaignResponseDefault) & {
  headers: Headers;
};

export type createCampaignResponse = (createCampaignResponseSuccess | createCampaignResponseError)

export const getCreateCampaignUrl = () => {


  

  return `/api/v1/admin/notifications/campaigns`
}

export const createCampaign = async (createCampaignRequest: NonReadonly<CreateCampaignRequest>, options?: RequestInit): Promise<createCampaignResponse> => {
  
  return customFetch<createCampaignResponse>(getCreateCampaignUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCampaignRequest,)
  }
);}
  

/**
 * Gets a notification campaign by ID.
 * @summary Get campaign
 */
export type getCampaignResponse200 = {
  data: CampaignDetailResponse
  status: 200
}

export type getCampaignResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCampaignResponseSuccess = (getCampaignResponse200) & {
  headers: Headers;
};
export type getCampaignResponseError = (getCampaignResponseDefault) & {
  headers: Headers;
};

export type getCampaignResponse = (getCampaignResponseSuccess | getCampaignResponseError)

export const getGetCampaignUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaigns/${id}`
}

export const getCampaign = async (id: string, options?: RequestInit): Promise<getCampaignResponse> => {
  
  return customFetch<getCampaignResponse>(getGetCampaignUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a draft notification campaign.
 * @summary Update campaign
 */
export type updateCampaignResponse200 = {
  data: UpdateCampaignResponseBody
  status: 200
}

export type updateCampaignResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCampaignResponseSuccess = (updateCampaignResponse200) & {
  headers: Headers;
};
export type updateCampaignResponseError = (updateCampaignResponseDefault) & {
  headers: Headers;
};

export type updateCampaignResponse = (updateCampaignResponseSuccess | updateCampaignResponseError)

export const getUpdateCampaignUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaigns/${id}`
}

export const updateCampaign = async (id: string,
    updateCampaignRequest: NonReadonly<UpdateCampaignRequest>, options?: RequestInit): Promise<updateCampaignResponse> => {
  
  return customFetch<updateCampaignResponse>(getUpdateCampaignUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignRequest,)
  }
);}
  

/**
 * Cancels a scheduled or sending campaign.
 * @summary Cancel campaign
 */
export type cancelCampaignResponse200 = {
  data: CancelCampaignResponseBody
  status: 200
}

export type cancelCampaignResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type cancelCampaignResponseSuccess = (cancelCampaignResponse200) & {
  headers: Headers;
};
export type cancelCampaignResponseError = (cancelCampaignResponseDefault) & {
  headers: Headers;
};

export type cancelCampaignResponse = (cancelCampaignResponseSuccess | cancelCampaignResponseError)

export const getCancelCampaignUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaigns/${id}/cancel`
}

export const cancelCampaign = async (id: string, options?: RequestInit): Promise<cancelCampaignResponse> => {
  
  return customFetch<cancelCampaignResponse>(getCancelCampaignUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Schedules a draft campaign, resolving segment filters to a static recipient list.
 * @summary Schedule campaign
 */
export type scheduleCampaignResponse200 = {
  data: ScheduleCampaignResponseBody
  status: 200
}

export type scheduleCampaignResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type scheduleCampaignResponseSuccess = (scheduleCampaignResponse200) & {
  headers: Headers;
};
export type scheduleCampaignResponseError = (scheduleCampaignResponseDefault) & {
  headers: Headers;
};

export type scheduleCampaignResponse = (scheduleCampaignResponseSuccess | scheduleCampaignResponseError)

export const getScheduleCampaignUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaigns/${id}/schedule`
}

export const scheduleCampaign = async (id: string, options?: RequestInit): Promise<scheduleCampaignResponse> => {
  
  return customFetch<scheduleCampaignResponse>(getScheduleCampaignUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Retries failed notification queue items.
 * @summary Retry failed
 */
export type retryFailedResponse200 = {
  data: RetryFailedResponseBody
  status: 200
}

export type retryFailedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type retryFailedResponseSuccess = (retryFailedResponse200) & {
  headers: Headers;
};
export type retryFailedResponseError = (retryFailedResponseDefault) & {
  headers: Headers;
};

export type retryFailedResponse = (retryFailedResponseSuccess | retryFailedResponseError)

export const getRetryFailedUrl = (params?: RetryFailedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/queue/retry?${stringifiedParams}` : `/api/v1/admin/notifications/queue/retry`
}

export const retryFailed = async (params?: RetryFailedParams, options?: RequestInit): Promise<retryFailedResponse> => {
  
  return customFetch<retryFailedResponse>(getRetryFailedUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Returns notification queue counts by status.
 * @summary Get queue status
 */
export type getQueueStatusResponse200 = {
  data: QueueStatusResponse
  status: 200
}

export type getQueueStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getQueueStatusResponseSuccess = (getQueueStatusResponse200) & {
  headers: Headers;
};
export type getQueueStatusResponseError = (getQueueStatusResponseDefault) & {
  headers: Headers;
};

export type getQueueStatusResponse = (getQueueStatusResponseSuccess | getQueueStatusResponseError)

export const getGetQueueStatusUrl = () => {


  

  return `/api/v1/admin/notifications/queue/status`
}

export const getQueueStatus = async ( options?: RequestInit): Promise<getQueueStatusResponse> => {
  
  return customFetch<getQueueStatusResponse>(getGetQueueStatusUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists notification templates with optional category filter.
 * @summary List templates
 */
export type listTemplatesResponse200 = {
  data: ListTemplatesResponseBody
  status: 200
}

export type listTemplatesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listTemplatesResponseSuccess = (listTemplatesResponse200) & {
  headers: Headers;
};
export type listTemplatesResponseError = (listTemplatesResponseDefault) & {
  headers: Headers;
};

export type listTemplatesResponse = (listTemplatesResponseSuccess | listTemplatesResponseError)

export const getListTemplatesUrl = (params?: ListTemplatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/templates?${stringifiedParams}` : `/api/v1/admin/notifications/templates`
}

export const listTemplates = async (params?: ListTemplatesParams, options?: RequestInit): Promise<listTemplatesResponse> => {
  
  return customFetch<listTemplatesResponse>(getListTemplatesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new notification template.
 * @summary Create template
 */
export type createTemplateResponse200 = {
  data: CreateTemplateResponseBody
  status: 200
}

export type createTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createTemplateResponseSuccess = (createTemplateResponse200) & {
  headers: Headers;
};
export type createTemplateResponseError = (createTemplateResponseDefault) & {
  headers: Headers;
};

export type createTemplateResponse = (createTemplateResponseSuccess | createTemplateResponseError)

export const getCreateTemplateUrl = () => {


  

  return `/api/v1/admin/notifications/templates`
}

export const createTemplate = async (createTemplateRequest: NonReadonly<CreateTemplateRequest>, options?: RequestInit): Promise<createTemplateResponse> => {
  
  return customFetch<createTemplateResponse>(getCreateTemplateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTemplateRequest,)
  }
);}
  

/**
 * Soft-deletes a notification template. System-managed templates cannot be deleted.
 * @summary Delete template
 */
export type deleteTemplateResponse200 = {
  data: DeleteTemplateResponseBody
  status: 200
}

export type deleteTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteTemplateResponseSuccess = (deleteTemplateResponse200) & {
  headers: Headers;
};
export type deleteTemplateResponseError = (deleteTemplateResponseDefault) & {
  headers: Headers;
};

export type deleteTemplateResponse = (deleteTemplateResponseSuccess | deleteTemplateResponseError)

export const getDeleteTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}`
}

export const deleteTemplate = async (id: string, options?: RequestInit): Promise<deleteTemplateResponse> => {
  
  return customFetch<deleteTemplateResponse>(getDeleteTemplateUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a notification template with its translations.
 * @summary Get template
 */
export type getTemplateResponse200 = {
  data: TemplateDetailResponse
  status: 200
}

export type getTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getTemplateResponseSuccess = (getTemplateResponse200) & {
  headers: Headers;
};
export type getTemplateResponseError = (getTemplateResponseDefault) & {
  headers: Headers;
};

export type getTemplateResponse = (getTemplateResponseSuccess | getTemplateResponseError)

export const getGetTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}`
}

export const getTemplate = async (id: string, options?: RequestInit): Promise<getTemplateResponse> => {
  
  return customFetch<getTemplateResponse>(getGetTemplateUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a notification template. System-managed templates have restricted fields.
 * @summary Update template
 */
export type updateTemplateResponse200 = {
  data: UpdateTemplateResponseBody
  status: 200
}

export type updateTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateTemplateResponseSuccess = (updateTemplateResponse200) & {
  headers: Headers;
};
export type updateTemplateResponseError = (updateTemplateResponseDefault) & {
  headers: Headers;
};

export type updateTemplateResponse = (updateTemplateResponseSuccess | updateTemplateResponseError)

export const getUpdateTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}`
}

export const updateTemplate = async (id: string,
    updateTemplateRequest: NonReadonly<UpdateTemplateRequest>, options?: RequestInit): Promise<updateTemplateResponse> => {
  
  return customFetch<updateTemplateResponse>(getUpdateTemplateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTemplateRequest,)
  }
);}
  

/**
 * Adds a translation to a notification template.
 * @summary Add translation
 */
export type addTranslationResponse200 = {
  data: AddTranslationResponseBody
  status: 200
}

export type addTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type addTranslationResponseSuccess = (addTranslationResponse200) & {
  headers: Headers;
};
export type addTranslationResponseError = (addTranslationResponseDefault) & {
  headers: Headers;
};

export type addTranslationResponse = (addTranslationResponseSuccess | addTranslationResponseError)

export const getAddTranslationUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}/translations`
}

export const addTranslation = async (id: string,
    addTranslationRequest: NonReadonly<AddTranslationRequest>, options?: RequestInit): Promise<addTranslationResponse> => {
  
  return customFetch<addTranslationResponse>(getAddTranslationUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addTranslationRequest,)
  }
);}
  

/**
 * Deletes a translation from a notification template.
 * @summary Delete translation
 */
export type deleteTranslationResponse200 = {
  data: DeleteTranslationResponseBody
  status: 200
}

export type deleteTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteTranslationResponseSuccess = (deleteTranslationResponse200) & {
  headers: Headers;
};
export type deleteTranslationResponseError = (deleteTranslationResponseDefault) & {
  headers: Headers;
};

export type deleteTranslationResponse = (deleteTranslationResponseSuccess | deleteTranslationResponseError)

export const getDeleteTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}/translations/${lang}`
}

export const deleteTranslation = async (id: string,
    lang: string, options?: RequestInit): Promise<deleteTranslationResponse> => {
  
  return customFetch<deleteTranslationResponse>(getDeleteTranslationUrl(id,lang),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates an existing translation for a notification template.
 * @summary Update translation
 */
export type updateTranslationResponse200 = {
  data: UpdateTranslationResponseBody
  status: 200
}

export type updateTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateTranslationResponseSuccess = (updateTranslationResponse200) & {
  headers: Headers;
};
export type updateTranslationResponseError = (updateTranslationResponseDefault) & {
  headers: Headers;
};

export type updateTranslationResponse = (updateTranslationResponseSuccess | updateTranslationResponseError)

export const getUpdateTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/notifications/templates/${id}/translations/${lang}`
}

export const updateTranslation = async (id: string,
    lang: string,
    updateTranslationRequest: NonReadonly<UpdateTranslationRequest>, options?: RequestInit): Promise<updateTranslationResponse> => {
  
  return customFetch<updateTranslationResponse>(getUpdateTranslationUrl(id,lang),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTranslationRequest,)
  }
);}
  

