/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddGuideConditionRequest,
  AddGuideConditionResponseBody,
  CreateGuideRequest,
  CreateGuideResponseBody,
  DeleteGuideResponseBody,
  ErrorModel,
  GetGuideAdminParams,
  GetGuideAdminResponseBody,
  ListGuidesAdminParams,
  ListGuidesAdminResponseBody,
  RemoveGuideConditionResponseBody,
  SetGuideTranslationsRequest,
  SetGuideTranslationsResponseBody,
  UpdateGuideRequest,
  UpdateGuideResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists guides for admin management with pagination and filters.
 * @summary List guides
 */
export type listGuidesAdminResponse200 = {
  data: ListGuidesAdminResponseBody
  status: 200
}

export type listGuidesAdminResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listGuidesAdminResponseSuccess = (listGuidesAdminResponse200) & {
  headers: Headers;
};
export type listGuidesAdminResponseError = (listGuidesAdminResponseDefault) & {
  headers: Headers;
};

export type listGuidesAdminResponse = (listGuidesAdminResponseSuccess | listGuidesAdminResponseError)

export const getListGuidesAdminUrl = (params?: ListGuidesAdminParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/guides?${stringifiedParams}` : `/api/v1/admin/guides`
}

export const listGuidesAdmin = async (params?: ListGuidesAdminParams, options?: RequestInit): Promise<listGuidesAdminResponse> => {
  
  return customFetch<listGuidesAdminResponse>(getListGuidesAdminUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new guide with optional translations and conditions.
 * @summary Create guide
 */
export type createGuideResponse200 = {
  data: CreateGuideResponseBody
  status: 200
}

export type createGuideResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createGuideResponseSuccess = (createGuideResponse200) & {
  headers: Headers;
};
export type createGuideResponseError = (createGuideResponseDefault) & {
  headers: Headers;
};

export type createGuideResponse = (createGuideResponseSuccess | createGuideResponseError)

export const getCreateGuideUrl = () => {


  

  return `/api/v1/admin/guides`
}

export const createGuide = async (createGuideRequest: NonReadonly<CreateGuideRequest>, options?: RequestInit): Promise<createGuideResponse> => {
  
  return customFetch<createGuideResponse>(getCreateGuideUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createGuideRequest,)
  }
);}
  

/**
 * Removes a visibility condition from a guide.
 * @summary Remove guide condition
 */
export type removeGuideConditionResponse200 = {
  data: RemoveGuideConditionResponseBody
  status: 200
}

export type removeGuideConditionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type removeGuideConditionResponseSuccess = (removeGuideConditionResponse200) & {
  headers: Headers;
};
export type removeGuideConditionResponseError = (removeGuideConditionResponseDefault) & {
  headers: Headers;
};

export type removeGuideConditionResponse = (removeGuideConditionResponseSuccess | removeGuideConditionResponseError)

export const getRemoveGuideConditionUrl = (condId: string,) => {


  

  return `/api/v1/admin/guides/conditions/${condId}`
}

export const removeGuideCondition = async (condId: string, options?: RequestInit): Promise<removeGuideConditionResponse> => {
  
  return customFetch<removeGuideConditionResponse>(getRemoveGuideConditionUrl(condId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Deletes a guide.
 * @summary Delete guide
 */
export type deleteGuideResponse200 = {
  data: DeleteGuideResponseBody
  status: 200
}

export type deleteGuideResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteGuideResponseSuccess = (deleteGuideResponse200) & {
  headers: Headers;
};
export type deleteGuideResponseError = (deleteGuideResponseDefault) & {
  headers: Headers;
};

export type deleteGuideResponse = (deleteGuideResponseSuccess | deleteGuideResponseError)

export const getDeleteGuideUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/${id}`
}

export const deleteGuide = async (id: string, options?: RequestInit): Promise<deleteGuideResponse> => {
  
  return customFetch<deleteGuideResponse>(getDeleteGuideUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Retrieves guide detail for admin editor.
 * @summary Get guide detail
 */
export type getGuideAdminResponse200 = {
  data: GetGuideAdminResponseBody
  status: 200
}

export type getGuideAdminResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getGuideAdminResponseSuccess = (getGuideAdminResponse200) & {
  headers: Headers;
};
export type getGuideAdminResponseError = (getGuideAdminResponseDefault) & {
  headers: Headers;
};

export type getGuideAdminResponse = (getGuideAdminResponseSuccess | getGuideAdminResponseError)

export const getGetGuideAdminUrl = (id: string,
    params?: GetGuideAdminParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/guides/${id}?${stringifiedParams}` : `/api/v1/admin/guides/${id}`
}

export const getGuideAdmin = async (id: string,
    params?: GetGuideAdminParams, options?: RequestInit): Promise<getGuideAdminResponse> => {
  
  return customFetch<getGuideAdminResponse>(getGetGuideAdminUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates an existing guide.
 * @summary Update guide
 */
export type updateGuideResponse200 = {
  data: UpdateGuideResponseBody
  status: 200
}

export type updateGuideResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateGuideResponseSuccess = (updateGuideResponse200) & {
  headers: Headers;
};
export type updateGuideResponseError = (updateGuideResponseDefault) & {
  headers: Headers;
};

export type updateGuideResponse = (updateGuideResponseSuccess | updateGuideResponseError)

export const getUpdateGuideUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/${id}`
}

export const updateGuide = async (id: string,
    updateGuideRequest: NonReadonly<UpdateGuideRequest>, options?: RequestInit): Promise<updateGuideResponse> => {
  
  return customFetch<updateGuideResponse>(getUpdateGuideUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateGuideRequest,)
  }
);}
  

/**
 * Adds a visibility condition to a guide.
 * @summary Add guide condition
 */
export type addGuideConditionResponse200 = {
  data: AddGuideConditionResponseBody
  status: 200
}

export type addGuideConditionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type addGuideConditionResponseSuccess = (addGuideConditionResponse200) & {
  headers: Headers;
};
export type addGuideConditionResponseError = (addGuideConditionResponseDefault) & {
  headers: Headers;
};

export type addGuideConditionResponse = (addGuideConditionResponseSuccess | addGuideConditionResponseError)

export const getAddGuideConditionUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/${id}/conditions`
}

export const addGuideCondition = async (id: string,
    addGuideConditionRequest: NonReadonly<AddGuideConditionRequest>, options?: RequestInit): Promise<addGuideConditionResponse> => {
  
  return customFetch<addGuideConditionResponse>(getAddGuideConditionUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addGuideConditionRequest,)
  }
);}
  

/**
 * Replaces all translations for a guide.
 * @summary Set guide translations
 */
export type setGuideTranslationsResponse200 = {
  data: SetGuideTranslationsResponseBody
  status: 200
}

export type setGuideTranslationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type setGuideTranslationsResponseSuccess = (setGuideTranslationsResponse200) & {
  headers: Headers;
};
export type setGuideTranslationsResponseError = (setGuideTranslationsResponseDefault) & {
  headers: Headers;
};

export type setGuideTranslationsResponse = (setGuideTranslationsResponseSuccess | setGuideTranslationsResponseError)

export const getSetGuideTranslationsUrl = (id: string,) => {


  

  return `/api/v1/admin/guides/${id}/translations`
}

export const setGuideTranslations = async (id: string,
    setGuideTranslationsRequest: NonReadonly<SetGuideTranslationsRequest>, options?: RequestInit): Promise<setGuideTranslationsResponse> => {
  
  return customFetch<setGuideTranslationsResponse>(getSetGuideTranslationsUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setGuideTranslationsRequest,)
  }
);}
  

