/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddCampaignTemplateTranslationRequest,
  AddCampaignTemplateTranslationResponseBody,
  CampaignTemplateDetailResponse,
  CreateCampaignTemplateRequest,
  CreateCampaignTemplateResponseBody,
  DeleteCampaignTemplateResponseBody,
  DeleteCampaignTemplateTranslationResponseBody,
  ErrorModel,
  ListCampaignTemplatesParams,
  ListCampaignTemplatesResponseBody,
  UpdateCampaignTemplateRequest,
  UpdateCampaignTemplateResponseBody,
  UpdateCampaignTemplateTranslationRequest,
  UpdateCampaignTemplateTranslationResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists all campaign templates.
 * @summary List campaign templates
 */
export type listCampaignTemplatesResponse200 = {
  data: ListCampaignTemplatesResponseBody
  status: 200
}

export type listCampaignTemplatesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listCampaignTemplatesResponseSuccess = (listCampaignTemplatesResponse200) & {
  headers: Headers;
};
export type listCampaignTemplatesResponseError = (listCampaignTemplatesResponseDefault) & {
  headers: Headers;
};

export type listCampaignTemplatesResponse = (listCampaignTemplatesResponseSuccess | listCampaignTemplatesResponseError)

export const getListCampaignTemplatesUrl = (params?: ListCampaignTemplatesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/notifications/campaign-templates?${stringifiedParams}` : `/api/v1/admin/notifications/campaign-templates`
}

export const listCampaignTemplates = async (params?: ListCampaignTemplatesParams, options?: RequestInit): Promise<listCampaignTemplatesResponse> => {
  
  return customFetch<listCampaignTemplatesResponse>(getListCampaignTemplatesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new campaign template.
 * @summary Create campaign template
 */
export type createCampaignTemplateResponse200 = {
  data: CreateCampaignTemplateResponseBody
  status: 200
}

export type createCampaignTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createCampaignTemplateResponseSuccess = (createCampaignTemplateResponse200) & {
  headers: Headers;
};
export type createCampaignTemplateResponseError = (createCampaignTemplateResponseDefault) & {
  headers: Headers;
};

export type createCampaignTemplateResponse = (createCampaignTemplateResponseSuccess | createCampaignTemplateResponseError)

export const getCreateCampaignTemplateUrl = () => {


  

  return `/api/v1/admin/notifications/campaign-templates`
}

export const createCampaignTemplate = async (createCampaignTemplateRequest: NonReadonly<CreateCampaignTemplateRequest>, options?: RequestInit): Promise<createCampaignTemplateResponse> => {
  
  return customFetch<createCampaignTemplateResponse>(getCreateCampaignTemplateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCampaignTemplateRequest,)
  }
);}
  

/**
 * Deletes a campaign template.
 * @summary Delete campaign template
 */
export type deleteCampaignTemplateResponse200 = {
  data: DeleteCampaignTemplateResponseBody
  status: 200
}

export type deleteCampaignTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteCampaignTemplateResponseSuccess = (deleteCampaignTemplateResponse200) & {
  headers: Headers;
};
export type deleteCampaignTemplateResponseError = (deleteCampaignTemplateResponseDefault) & {
  headers: Headers;
};

export type deleteCampaignTemplateResponse = (deleteCampaignTemplateResponseSuccess | deleteCampaignTemplateResponseError)

export const getDeleteCampaignTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}`
}

export const deleteCampaignTemplate = async (id: string, options?: RequestInit): Promise<deleteCampaignTemplateResponse> => {
  
  return customFetch<deleteCampaignTemplateResponse>(getDeleteCampaignTemplateUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a campaign template with its translations.
 * @summary Get campaign template
 */
export type getCampaignTemplateResponse200 = {
  data: CampaignTemplateDetailResponse
  status: 200
}

export type getCampaignTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCampaignTemplateResponseSuccess = (getCampaignTemplateResponse200) & {
  headers: Headers;
};
export type getCampaignTemplateResponseError = (getCampaignTemplateResponseDefault) & {
  headers: Headers;
};

export type getCampaignTemplateResponse = (getCampaignTemplateResponseSuccess | getCampaignTemplateResponseError)

export const getGetCampaignTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}`
}

export const getCampaignTemplate = async (id: string, options?: RequestInit): Promise<getCampaignTemplateResponse> => {
  
  return customFetch<getCampaignTemplateResponse>(getGetCampaignTemplateUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a campaign template.
 * @summary Update campaign template
 */
export type updateCampaignTemplateResponse200 = {
  data: UpdateCampaignTemplateResponseBody
  status: 200
}

export type updateCampaignTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCampaignTemplateResponseSuccess = (updateCampaignTemplateResponse200) & {
  headers: Headers;
};
export type updateCampaignTemplateResponseError = (updateCampaignTemplateResponseDefault) & {
  headers: Headers;
};

export type updateCampaignTemplateResponse = (updateCampaignTemplateResponseSuccess | updateCampaignTemplateResponseError)

export const getUpdateCampaignTemplateUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}`
}

export const updateCampaignTemplate = async (id: string,
    updateCampaignTemplateRequest: NonReadonly<UpdateCampaignTemplateRequest>, options?: RequestInit): Promise<updateCampaignTemplateResponse> => {
  
  return customFetch<updateCampaignTemplateResponse>(getUpdateCampaignTemplateUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignTemplateRequest,)
  }
);}
  

/**
 * Adds a translation to a campaign template.
 * @summary Add campaign template translation
 */
export type addCampaignTemplateTranslationResponse200 = {
  data: AddCampaignTemplateTranslationResponseBody
  status: 200
}

export type addCampaignTemplateTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type addCampaignTemplateTranslationResponseSuccess = (addCampaignTemplateTranslationResponse200) & {
  headers: Headers;
};
export type addCampaignTemplateTranslationResponseError = (addCampaignTemplateTranslationResponseDefault) & {
  headers: Headers;
};

export type addCampaignTemplateTranslationResponse = (addCampaignTemplateTranslationResponseSuccess | addCampaignTemplateTranslationResponseError)

export const getAddCampaignTemplateTranslationUrl = (id: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}/translations`
}

export const addCampaignTemplateTranslation = async (id: string,
    addCampaignTemplateTranslationRequest: NonReadonly<AddCampaignTemplateTranslationRequest>, options?: RequestInit): Promise<addCampaignTemplateTranslationResponse> => {
  
  return customFetch<addCampaignTemplateTranslationResponse>(getAddCampaignTemplateTranslationUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addCampaignTemplateTranslationRequest,)
  }
);}
  

/**
 * Deletes a translation from a campaign template.
 * @summary Delete campaign template translation
 */
export type deleteCampaignTemplateTranslationResponse200 = {
  data: DeleteCampaignTemplateTranslationResponseBody
  status: 200
}

export type deleteCampaignTemplateTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteCampaignTemplateTranslationResponseSuccess = (deleteCampaignTemplateTranslationResponse200) & {
  headers: Headers;
};
export type deleteCampaignTemplateTranslationResponseError = (deleteCampaignTemplateTranslationResponseDefault) & {
  headers: Headers;
};

export type deleteCampaignTemplateTranslationResponse = (deleteCampaignTemplateTranslationResponseSuccess | deleteCampaignTemplateTranslationResponseError)

export const getDeleteCampaignTemplateTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}/translations/${lang}`
}

export const deleteCampaignTemplateTranslation = async (id: string,
    lang: string, options?: RequestInit): Promise<deleteCampaignTemplateTranslationResponse> => {
  
  return customFetch<deleteCampaignTemplateTranslationResponse>(getDeleteCampaignTemplateTranslationUrl(id,lang),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates an existing translation for a campaign template.
 * @summary Update campaign template translation
 */
export type updateCampaignTemplateTranslationResponse200 = {
  data: UpdateCampaignTemplateTranslationResponseBody
  status: 200
}

export type updateCampaignTemplateTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCampaignTemplateTranslationResponseSuccess = (updateCampaignTemplateTranslationResponse200) & {
  headers: Headers;
};
export type updateCampaignTemplateTranslationResponseError = (updateCampaignTemplateTranslationResponseDefault) & {
  headers: Headers;
};

export type updateCampaignTemplateTranslationResponse = (updateCampaignTemplateTranslationResponseSuccess | updateCampaignTemplateTranslationResponseError)

export const getUpdateCampaignTemplateTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/notifications/campaign-templates/${id}/translations/${lang}`
}

export const updateCampaignTemplateTranslation = async (id: string,
    lang: string,
    updateCampaignTemplateTranslationRequest: NonReadonly<UpdateCampaignTemplateTranslationRequest>, options?: RequestInit): Promise<updateCampaignTemplateTranslationResponse> => {
  
  return customFetch<updateCampaignTemplateTranslationResponse>(getUpdateCampaignTemplateTranslationUrl(id,lang),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCampaignTemplateTranslationRequest,)
  }
);}
  

