/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AdminListResponseBody,
  ErrorModel,
  ListAdminsParams,
  ResetAdminPasswordOutputBody,
  UpdateAdminStatusOutputBody,
  UpdateAdminStatusRequest
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns a paginated list of admin accounts filtered by search, status, and role.
 * @summary List admin accounts
 */
export type listAdminsResponse200 = {
  data: AdminListResponseBody
  status: 200
}

export type listAdminsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listAdminsResponseSuccess = (listAdminsResponse200) & {
  headers: Headers;
};
export type listAdminsResponseError = (listAdminsResponseDefault) & {
  headers: Headers;
};

export type listAdminsResponse = (listAdminsResponseSuccess | listAdminsResponseError)

export const getListAdminsUrl = (params?: ListAdminsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/accounts?${stringifiedParams}` : `/api/v1/admin/accounts`
}

export const listAdmins = async (params?: ListAdminsParams, options?: RequestInit): Promise<listAdminsResponse> => {
  
  return customFetch<listAdminsResponse>(getListAdminsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Triggers a password reset for an admin account by sending an OTP to their email.
 * @summary Trigger admin password reset
 */
export type resetAdminPasswordResponse200 = {
  data: ResetAdminPasswordOutputBody
  status: 200
}

export type resetAdminPasswordResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type resetAdminPasswordResponseSuccess = (resetAdminPasswordResponse200) & {
  headers: Headers;
};
export type resetAdminPasswordResponseError = (resetAdminPasswordResponseDefault) & {
  headers: Headers;
};

export type resetAdminPasswordResponse = (resetAdminPasswordResponseSuccess | resetAdminPasswordResponseError)

export const getResetAdminPasswordUrl = (accountId: string,) => {


  

  return `/api/v1/admin/accounts/${accountId}/reset-password`
}

export const resetAdminPassword = async (accountId: string, options?: RequestInit): Promise<resetAdminPasswordResponse> => {
  
  return customFetch<resetAdminPasswordResponse>(getResetAdminPasswordUrl(accountId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Updates the status of an admin account (active, locked, suspended).
 * @summary Update admin account status
 */
export type updateAdminStatusResponse200 = {
  data: UpdateAdminStatusOutputBody
  status: 200
}

export type updateAdminStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateAdminStatusResponseSuccess = (updateAdminStatusResponse200) & {
  headers: Headers;
};
export type updateAdminStatusResponseError = (updateAdminStatusResponseDefault) & {
  headers: Headers;
};

export type updateAdminStatusResponse = (updateAdminStatusResponseSuccess | updateAdminStatusResponseError)

export const getUpdateAdminStatusUrl = (accountId: string,) => {


  

  return `/api/v1/admin/accounts/${accountId}/status`
}

export const updateAdminStatus = async (accountId: string,
    updateAdminStatusRequest: NonReadonly<UpdateAdminStatusRequest>, options?: RequestInit): Promise<updateAdminStatusResponse> => {
  
  return customFetch<updateAdminStatusResponse>(getUpdateAdminStatusUrl(accountId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAdminStatusRequest,)
  }
);}
  

