/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddCategoryTranslationOutputBody,
  AddCategoryTranslationRequest,
  CategoryDetailResponse,
  CategorySummaryResponse,
  CreateInteractiveFormOutputBody,
  CreateInteractiveFormRequest,
  CreateLibraryCategoryOutputBody,
  CreateLibraryCategoryRequest,
  CreateTemplateGroupOutputBody,
  CreateTemplateGroupRequest,
  DeleteCategoryTranslationOutputBody,
  DeleteInteractiveFormOutputBody,
  DeleteTemplateGroupOutputBody,
  DownloadLogListResponse,
  ErrorModel,
  InteractiveFormDetailResponse,
  LibraryCreateTemplateBody,
  LibraryCreateTemplateOutputBody,
  LibraryDeleteCategoryOutputBody,
  LibraryDeleteTemplateOutputBody,
  LibraryGetDownloadLogsParams,
  LibraryListAllCategoriesParams,
  LibraryListAllTemplateGroupsParams,
  LibraryTemplateDetailResponse,
  LibraryUpdateTemplateBody,
  TemplateGroupDetailResponse,
  TemplateGroupSummaryResponse,
  TemplateItem,
  UpdateCategoryTranslationOutputBody,
  UpdateCategoryTranslationRequest,
  UpdateInteractiveFormRequest,
  UpdateLibraryCategoryRequest,
  UpdateTemplateGroupRequest
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists categories, optionally including inactive.
 * @summary List all categories
 */
export type libraryListAllCategoriesResponse200 = {
  data: CategorySummaryResponse[] | null
  status: 200
}

export type libraryListAllCategoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListAllCategoriesResponseSuccess = (libraryListAllCategoriesResponse200) & {
  headers: Headers;
};
export type libraryListAllCategoriesResponseError = (libraryListAllCategoriesResponseDefault) & {
  headers: Headers;
};

export type libraryListAllCategoriesResponse = (libraryListAllCategoriesResponseSuccess | libraryListAllCategoriesResponseError)

export const getLibraryListAllCategoriesUrl = (params?: LibraryListAllCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/library/categories?${stringifiedParams}` : `/api/v1/admin/library/categories`
}

export const libraryListAllCategories = async (params?: LibraryListAllCategoriesParams, options?: RequestInit): Promise<libraryListAllCategoriesResponse> => {
  
  return customFetch<libraryListAllCategoriesResponse>(getLibraryListAllCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new library category.
 * @summary Create category
 */
export type libraryCreateCategoryResponse200 = {
  data: CreateLibraryCategoryOutputBody
  status: 200
}

export type libraryCreateCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryCreateCategoryResponseSuccess = (libraryCreateCategoryResponse200) & {
  headers: Headers;
};
export type libraryCreateCategoryResponseError = (libraryCreateCategoryResponseDefault) & {
  headers: Headers;
};

export type libraryCreateCategoryResponse = (libraryCreateCategoryResponseSuccess | libraryCreateCategoryResponseError)

export const getLibraryCreateCategoryUrl = () => {


  

  return `/api/v1/admin/library/categories`
}

export const libraryCreateCategory = async (createLibraryCategoryRequest: NonReadonly<CreateLibraryCategoryRequest>, options?: RequestInit): Promise<libraryCreateCategoryResponse> => {
  
  return customFetch<libraryCreateCategoryResponse>(getLibraryCreateCategoryUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createLibraryCategoryRequest,)
  }
);}
  

/**
 * Soft-deletes a category. Fails if it has active template groups.
 * @summary Delete category
 */
export type libraryDeleteCategoryResponse200 = {
  data: LibraryDeleteCategoryOutputBody
  status: 200
}

export type libraryDeleteCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDeleteCategoryResponseSuccess = (libraryDeleteCategoryResponse200) & {
  headers: Headers;
};
export type libraryDeleteCategoryResponseError = (libraryDeleteCategoryResponseDefault) & {
  headers: Headers;
};

export type libraryDeleteCategoryResponse = (libraryDeleteCategoryResponseSuccess | libraryDeleteCategoryResponseError)

export const getLibraryDeleteCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/library/categories/${id}`
}

export const libraryDeleteCategory = async (id: string, options?: RequestInit): Promise<libraryDeleteCategoryResponse> => {
  
  return customFetch<libraryDeleteCategoryResponse>(getLibraryDeleteCategoryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a category with translations.
 * @summary Get category
 */
export type libraryGetCategoryResponse200 = {
  data: CategoryDetailResponse
  status: 200
}

export type libraryGetCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryGetCategoryResponseSuccess = (libraryGetCategoryResponse200) & {
  headers: Headers;
};
export type libraryGetCategoryResponseError = (libraryGetCategoryResponseDefault) & {
  headers: Headers;
};

export type libraryGetCategoryResponse = (libraryGetCategoryResponseSuccess | libraryGetCategoryResponseError)

export const getLibraryGetCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/library/categories/${id}`
}

export const libraryGetCategory = async (id: string, options?: RequestInit): Promise<libraryGetCategoryResponse> => {
  
  return customFetch<libraryGetCategoryResponse>(getLibraryGetCategoryUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a category's metadata.
 * @summary Update category
 */
export type libraryUpdateCategoryResponse200 = {
  data: CategoryDetailResponse
  status: 200
}

export type libraryUpdateCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryUpdateCategoryResponseSuccess = (libraryUpdateCategoryResponse200) & {
  headers: Headers;
};
export type libraryUpdateCategoryResponseError = (libraryUpdateCategoryResponseDefault) & {
  headers: Headers;
};

export type libraryUpdateCategoryResponse = (libraryUpdateCategoryResponseSuccess | libraryUpdateCategoryResponseError)

export const getLibraryUpdateCategoryUrl = (id: string,) => {


  

  return `/api/v1/admin/library/categories/${id}`
}

export const libraryUpdateCategory = async (id: string,
    updateLibraryCategoryRequest: NonReadonly<UpdateLibraryCategoryRequest>, options?: RequestInit): Promise<libraryUpdateCategoryResponse> => {
  
  return customFetch<libraryUpdateCategoryResponse>(getLibraryUpdateCategoryUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateLibraryCategoryRequest,)
  }
);}
  

/**
 * Adds a translation for a category.
 * @summary Add category translation
 */
export type libraryAddCategoryTranslationResponse200 = {
  data: AddCategoryTranslationOutputBody
  status: 200
}

export type libraryAddCategoryTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryAddCategoryTranslationResponseSuccess = (libraryAddCategoryTranslationResponse200) & {
  headers: Headers;
};
export type libraryAddCategoryTranslationResponseError = (libraryAddCategoryTranslationResponseDefault) & {
  headers: Headers;
};

export type libraryAddCategoryTranslationResponse = (libraryAddCategoryTranslationResponseSuccess | libraryAddCategoryTranslationResponseError)

export const getLibraryAddCategoryTranslationUrl = (id: string,) => {


  

  return `/api/v1/admin/library/categories/${id}/translations`
}

export const libraryAddCategoryTranslation = async (id: string,
    addCategoryTranslationRequest: NonReadonly<AddCategoryTranslationRequest>, options?: RequestInit): Promise<libraryAddCategoryTranslationResponse> => {
  
  return customFetch<libraryAddCategoryTranslationResponse>(getLibraryAddCategoryTranslationUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      addCategoryTranslationRequest,)
  }
);}
  

/**
 * Removes a category translation.
 * @summary Delete category translation
 */
export type libraryDeleteCategoryTranslationResponse200 = {
  data: DeleteCategoryTranslationOutputBody
  status: 200
}

export type libraryDeleteCategoryTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDeleteCategoryTranslationResponseSuccess = (libraryDeleteCategoryTranslationResponse200) & {
  headers: Headers;
};
export type libraryDeleteCategoryTranslationResponseError = (libraryDeleteCategoryTranslationResponseDefault) & {
  headers: Headers;
};

export type libraryDeleteCategoryTranslationResponse = (libraryDeleteCategoryTranslationResponseSuccess | libraryDeleteCategoryTranslationResponseError)

export const getLibraryDeleteCategoryTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/library/categories/${id}/translations/${lang}`
}

export const libraryDeleteCategoryTranslation = async (id: string,
    lang: string, options?: RequestInit): Promise<libraryDeleteCategoryTranslationResponse> => {
  
  return customFetch<libraryDeleteCategoryTranslationResponse>(getLibraryDeleteCategoryTranslationUrl(id,lang),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates an existing category translation.
 * @summary Update category translation
 */
export type libraryUpdateCategoryTranslationResponse200 = {
  data: UpdateCategoryTranslationOutputBody
  status: 200
}

export type libraryUpdateCategoryTranslationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryUpdateCategoryTranslationResponseSuccess = (libraryUpdateCategoryTranslationResponse200) & {
  headers: Headers;
};
export type libraryUpdateCategoryTranslationResponseError = (libraryUpdateCategoryTranslationResponseDefault) & {
  headers: Headers;
};

export type libraryUpdateCategoryTranslationResponse = (libraryUpdateCategoryTranslationResponseSuccess | libraryUpdateCategoryTranslationResponseError)

export const getLibraryUpdateCategoryTranslationUrl = (id: string,
    lang: string,) => {


  

  return `/api/v1/admin/library/categories/${id}/translations/${lang}`
}

export const libraryUpdateCategoryTranslation = async (id: string,
    lang: string,
    updateCategoryTranslationRequest: NonReadonly<UpdateCategoryTranslationRequest>, options?: RequestInit): Promise<libraryUpdateCategoryTranslationResponse> => {
  
  return customFetch<libraryUpdateCategoryTranslationResponse>(getLibraryUpdateCategoryTranslationUrl(id,lang),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCategoryTranslationRequest,)
  }
);}
  

/**
 * Lists download history with optional group filter.
 * @summary Get download logs
 */
export type libraryGetDownloadLogsResponse200 = {
  data: DownloadLogListResponse
  status: 200
}

export type libraryGetDownloadLogsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryGetDownloadLogsResponseSuccess = (libraryGetDownloadLogsResponse200) & {
  headers: Headers;
};
export type libraryGetDownloadLogsResponseError = (libraryGetDownloadLogsResponseDefault) & {
  headers: Headers;
};

export type libraryGetDownloadLogsResponse = (libraryGetDownloadLogsResponseSuccess | libraryGetDownloadLogsResponseError)

export const getLibraryGetDownloadLogsUrl = (params?: LibraryGetDownloadLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/library/downloads?${stringifiedParams}` : `/api/v1/admin/library/downloads`
}

export const libraryGetDownloadLogs = async (params?: LibraryGetDownloadLogsParams, options?: RequestInit): Promise<libraryGetDownloadLogsResponse> => {
  
  return customFetch<libraryGetDownloadLogsResponse>(getLibraryGetDownloadLogsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Soft-deletes an interactive form.
 * @summary Delete interactive form
 */
export type libraryDeleteInteractiveFormResponse200 = {
  data: DeleteInteractiveFormOutputBody
  status: 200
}

export type libraryDeleteInteractiveFormResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDeleteInteractiveFormResponseSuccess = (libraryDeleteInteractiveFormResponse200) & {
  headers: Headers;
};
export type libraryDeleteInteractiveFormResponseError = (libraryDeleteInteractiveFormResponseDefault) & {
  headers: Headers;
};

export type libraryDeleteInteractiveFormResponse = (libraryDeleteInteractiveFormResponseSuccess | libraryDeleteInteractiveFormResponseError)

export const getLibraryDeleteInteractiveFormUrl = (id: string,) => {


  

  return `/api/v1/admin/library/interactive-forms/${id}`
}

export const libraryDeleteInteractiveForm = async (id: string, options?: RequestInit): Promise<libraryDeleteInteractiveFormResponse> => {
  
  return customFetch<libraryDeleteInteractiveFormResponse>(getLibraryDeleteInteractiveFormUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates an interactive form's layout.
 * @summary Update interactive form
 */
export type libraryUpdateInteractiveFormResponse200 = {
  data: InteractiveFormDetailResponse
  status: 200
}

export type libraryUpdateInteractiveFormResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryUpdateInteractiveFormResponseSuccess = (libraryUpdateInteractiveFormResponse200) & {
  headers: Headers;
};
export type libraryUpdateInteractiveFormResponseError = (libraryUpdateInteractiveFormResponseDefault) & {
  headers: Headers;
};

export type libraryUpdateInteractiveFormResponse = (libraryUpdateInteractiveFormResponseSuccess | libraryUpdateInteractiveFormResponseError)

export const getLibraryUpdateInteractiveFormUrl = (id: string,) => {


  

  return `/api/v1/admin/library/interactive-forms/${id}`
}

export const libraryUpdateInteractiveForm = async (id: string,
    updateInteractiveFormRequest: NonReadonly<UpdateInteractiveFormRequest>, options?: RequestInit): Promise<libraryUpdateInteractiveFormResponse> => {
  
  return customFetch<libraryUpdateInteractiveFormResponse>(getLibraryUpdateInteractiveFormUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateInteractiveFormRequest,)
  }
);}
  

/**
 * Lists all template groups with optional category filter.
 * @summary List template groups
 */
export type libraryListAllTemplateGroupsResponse200 = {
  data: TemplateGroupSummaryResponse[] | null
  status: 200
}

export type libraryListAllTemplateGroupsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListAllTemplateGroupsResponseSuccess = (libraryListAllTemplateGroupsResponse200) & {
  headers: Headers;
};
export type libraryListAllTemplateGroupsResponseError = (libraryListAllTemplateGroupsResponseDefault) & {
  headers: Headers;
};

export type libraryListAllTemplateGroupsResponse = (libraryListAllTemplateGroupsResponseSuccess | libraryListAllTemplateGroupsResponseError)

export const getLibraryListAllTemplateGroupsUrl = (params?: LibraryListAllTemplateGroupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/admin/library/template-groups?${stringifiedParams}` : `/api/v1/admin/library/template-groups`
}

export const libraryListAllTemplateGroups = async (params?: LibraryListAllTemplateGroupsParams, options?: RequestInit): Promise<libraryListAllTemplateGroupsResponse> => {
  
  return customFetch<libraryListAllTemplateGroupsResponse>(getLibraryListAllTemplateGroupsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new template group with metadata.
 * @summary Create template group
 */
export type libraryCreateTemplateGroupResponse200 = {
  data: CreateTemplateGroupOutputBody
  status: 200
}

export type libraryCreateTemplateGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryCreateTemplateGroupResponseSuccess = (libraryCreateTemplateGroupResponse200) & {
  headers: Headers;
};
export type libraryCreateTemplateGroupResponseError = (libraryCreateTemplateGroupResponseDefault) & {
  headers: Headers;
};

export type libraryCreateTemplateGroupResponse = (libraryCreateTemplateGroupResponseSuccess | libraryCreateTemplateGroupResponseError)

export const getLibraryCreateTemplateGroupUrl = () => {


  

  return `/api/v1/admin/library/template-groups`
}

export const libraryCreateTemplateGroup = async (createTemplateGroupRequest: NonReadonly<CreateTemplateGroupRequest>, options?: RequestInit): Promise<libraryCreateTemplateGroupResponse> => {
  
  return customFetch<libraryCreateTemplateGroupResponse>(getLibraryCreateTemplateGroupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTemplateGroupRequest,)
  }
);}
  

/**
 * Soft-deletes a template group.
 * @summary Delete template group
 */
export type libraryDeleteTemplateGroupResponse200 = {
  data: DeleteTemplateGroupOutputBody
  status: 200
}

export type libraryDeleteTemplateGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDeleteTemplateGroupResponseSuccess = (libraryDeleteTemplateGroupResponse200) & {
  headers: Headers;
};
export type libraryDeleteTemplateGroupResponseError = (libraryDeleteTemplateGroupResponseDefault) & {
  headers: Headers;
};

export type libraryDeleteTemplateGroupResponse = (libraryDeleteTemplateGroupResponseSuccess | libraryDeleteTemplateGroupResponseError)

export const getLibraryDeleteTemplateGroupUrl = (groupId: string,) => {


  

  return `/api/v1/admin/library/template-groups/${groupId}`
}

export const libraryDeleteTemplateGroup = async (groupId: string, options?: RequestInit): Promise<libraryDeleteTemplateGroupResponse> => {
  
  return customFetch<libraryDeleteTemplateGroupResponse>(getLibraryDeleteTemplateGroupUrl(groupId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a template group with all templates.
 * @summary Get template group
 */
export type libraryAdminGetTemplateGroupResponse200 = {
  data: TemplateGroupDetailResponse
  status: 200
}

export type libraryAdminGetTemplateGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryAdminGetTemplateGroupResponseSuccess = (libraryAdminGetTemplateGroupResponse200) & {
  headers: Headers;
};
export type libraryAdminGetTemplateGroupResponseError = (libraryAdminGetTemplateGroupResponseDefault) & {
  headers: Headers;
};

export type libraryAdminGetTemplateGroupResponse = (libraryAdminGetTemplateGroupResponseSuccess | libraryAdminGetTemplateGroupResponseError)

export const getLibraryAdminGetTemplateGroupUrl = (groupId: string,) => {


  

  return `/api/v1/admin/library/template-groups/${groupId}`
}

export const libraryAdminGetTemplateGroup = async (groupId: string, options?: RequestInit): Promise<libraryAdminGetTemplateGroupResponse> => {
  
  return customFetch<libraryAdminGetTemplateGroupResponse>(getLibraryAdminGetTemplateGroupUrl(groupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a template group's metadata.
 * @summary Update template group
 */
export type libraryUpdateTemplateGroupResponse200 = {
  data: TemplateGroupDetailResponse
  status: 200
}

export type libraryUpdateTemplateGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryUpdateTemplateGroupResponseSuccess = (libraryUpdateTemplateGroupResponse200) & {
  headers: Headers;
};
export type libraryUpdateTemplateGroupResponseError = (libraryUpdateTemplateGroupResponseDefault) & {
  headers: Headers;
};

export type libraryUpdateTemplateGroupResponse = (libraryUpdateTemplateGroupResponseSuccess | libraryUpdateTemplateGroupResponseError)

export const getLibraryUpdateTemplateGroupUrl = (groupId: string,) => {


  

  return `/api/v1/admin/library/template-groups/${groupId}`
}

export const libraryUpdateTemplateGroup = async (groupId: string,
    updateTemplateGroupRequest: NonReadonly<UpdateTemplateGroupRequest>, options?: RequestInit): Promise<libraryUpdateTemplateGroupResponse> => {
  
  return customFetch<libraryUpdateTemplateGroupResponse>(getLibraryUpdateTemplateGroupUrl(groupId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTemplateGroupRequest,)
  }
);}
  

/**
 * Lists all template variants for a group.
 * @summary List templates by group
 */
export type libraryListTemplatesByGroupResponse200 = {
  data: TemplateItem[] | null
  status: 200
}

export type libraryListTemplatesByGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListTemplatesByGroupResponseSuccess = (libraryListTemplatesByGroupResponse200) & {
  headers: Headers;
};
export type libraryListTemplatesByGroupResponseError = (libraryListTemplatesByGroupResponseDefault) & {
  headers: Headers;
};

export type libraryListTemplatesByGroupResponse = (libraryListTemplatesByGroupResponseSuccess | libraryListTemplatesByGroupResponseError)

export const getLibraryListTemplatesByGroupUrl = (groupId: string,) => {


  

  return `/api/v1/admin/library/template-groups/${groupId}/templates`
}

export const libraryListTemplatesByGroup = async (groupId: string, options?: RequestInit): Promise<libraryListTemplatesByGroupResponse> => {
  
  return customFetch<libraryListTemplatesByGroupResponse>(getLibraryListTemplatesByGroupUrl(groupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Uploads a file and creates a template language variant.
 * @summary Create template
 */
export type libraryCreateTemplateResponse200 = {
  data: LibraryCreateTemplateOutputBody
  status: 200
}

export type libraryCreateTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryCreateTemplateResponseSuccess = (libraryCreateTemplateResponse200) & {
  headers: Headers;
};
export type libraryCreateTemplateResponseError = (libraryCreateTemplateResponseDefault) & {
  headers: Headers;
};

export type libraryCreateTemplateResponse = (libraryCreateTemplateResponseSuccess | libraryCreateTemplateResponseError)

export const getLibraryCreateTemplateUrl = (groupId: string,) => {


  

  return `/api/v1/admin/library/template-groups/${groupId}/templates`
}

export const libraryCreateTemplate = async (groupId: string,
    libraryCreateTemplateBody: LibraryCreateTemplateBody, options?: RequestInit): Promise<libraryCreateTemplateResponse> => {
    const formData = new FormData();
formData.append(`description`, libraryCreateTemplateBody.description instanceof Blob ? libraryCreateTemplateBody.description : new Blob([libraryCreateTemplateBody.description], { type: 'text/plain' }));
formData.append(`file`, libraryCreateTemplateBody.file);
formData.append(`language`, libraryCreateTemplateBody.language instanceof Blob ? libraryCreateTemplateBody.language : new Blob([libraryCreateTemplateBody.language], { type: 'text/plain' }));
formData.append(`title`, libraryCreateTemplateBody.title instanceof Blob ? libraryCreateTemplateBody.title : new Blob([libraryCreateTemplateBody.title], { type: 'text/plain' }));

  return customFetch<libraryCreateTemplateResponse>(getLibraryCreateTemplateUrl(groupId),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Soft-deletes a template.
 * @summary Delete template
 */
export type libraryDeleteTemplateResponse200 = {
  data: LibraryDeleteTemplateOutputBody
  status: 200
}

export type libraryDeleteTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDeleteTemplateResponseSuccess = (libraryDeleteTemplateResponse200) & {
  headers: Headers;
};
export type libraryDeleteTemplateResponseError = (libraryDeleteTemplateResponseDefault) & {
  headers: Headers;
};

export type libraryDeleteTemplateResponse = (libraryDeleteTemplateResponseSuccess | libraryDeleteTemplateResponseError)

export const getLibraryDeleteTemplateUrl = (templateId: string,) => {


  

  return `/api/v1/admin/library/templates/${templateId}`
}

export const libraryDeleteTemplate = async (templateId: string, options?: RequestInit): Promise<libraryDeleteTemplateResponse> => {
  
  return customFetch<libraryDeleteTemplateResponse>(getLibraryDeleteTemplateUrl(templateId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Gets a template by ID.
 * @summary Get template
 */
export type libraryGetTemplateResponse200 = {
  data: LibraryTemplateDetailResponse
  status: 200
}

export type libraryGetTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryGetTemplateResponseSuccess = (libraryGetTemplateResponse200) & {
  headers: Headers;
};
export type libraryGetTemplateResponseError = (libraryGetTemplateResponseDefault) & {
  headers: Headers;
};

export type libraryGetTemplateResponse = (libraryGetTemplateResponseSuccess | libraryGetTemplateResponseError)

export const getLibraryGetTemplateUrl = (templateId: string,) => {


  

  return `/api/v1/admin/library/templates/${templateId}`
}

export const libraryGetTemplate = async (templateId: string, options?: RequestInit): Promise<libraryGetTemplateResponse> => {
  
  return customFetch<libraryGetTemplateResponse>(getLibraryGetTemplateUrl(templateId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates template metadata or replaces the file.
 * @summary Update template
 */
export type libraryUpdateTemplateResponse200 = {
  data: LibraryTemplateDetailResponse
  status: 200
}

export type libraryUpdateTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryUpdateTemplateResponseSuccess = (libraryUpdateTemplateResponse200) & {
  headers: Headers;
};
export type libraryUpdateTemplateResponseError = (libraryUpdateTemplateResponseDefault) & {
  headers: Headers;
};

export type libraryUpdateTemplateResponse = (libraryUpdateTemplateResponseSuccess | libraryUpdateTemplateResponseError)

export const getLibraryUpdateTemplateUrl = (templateId: string,) => {


  

  return `/api/v1/admin/library/templates/${templateId}`
}

export const libraryUpdateTemplate = async (templateId: string,
    libraryUpdateTemplateBody: LibraryUpdateTemplateBody, options?: RequestInit): Promise<libraryUpdateTemplateResponse> => {
    const formData = new FormData();
formData.append(`description`, libraryUpdateTemplateBody.description instanceof Blob ? libraryUpdateTemplateBody.description : new Blob([libraryUpdateTemplateBody.description], { type: 'text/plain' }));
formData.append(`file`, libraryUpdateTemplateBody.file);
formData.append(`isActive`, libraryUpdateTemplateBody.isActive instanceof Blob ? libraryUpdateTemplateBody.isActive : new Blob([libraryUpdateTemplateBody.isActive], { type: 'text/plain' }));
formData.append(`title`, libraryUpdateTemplateBody.title instanceof Blob ? libraryUpdateTemplateBody.title : new Blob([libraryUpdateTemplateBody.title], { type: 'text/plain' }));

  return customFetch<libraryUpdateTemplateResponse>(getLibraryUpdateTemplateUrl(templateId),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Gets the interactive form for a template.
 * @summary Get interactive form
 */
export type libraryGetInteractiveFormResponse200 = {
  data: InteractiveFormDetailResponse
  status: 200
}

export type libraryGetInteractiveFormResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryGetInteractiveFormResponseSuccess = (libraryGetInteractiveFormResponse200) & {
  headers: Headers;
};
export type libraryGetInteractiveFormResponseError = (libraryGetInteractiveFormResponseDefault) & {
  headers: Headers;
};

export type libraryGetInteractiveFormResponse = (libraryGetInteractiveFormResponseSuccess | libraryGetInteractiveFormResponseError)

export const getLibraryGetInteractiveFormUrl = (templateId: string,) => {


  

  return `/api/v1/admin/library/templates/${templateId}/interactive-form`
}

export const libraryGetInteractiveForm = async (templateId: string, options?: RequestInit): Promise<libraryGetInteractiveFormResponse> => {
  
  return customFetch<libraryGetInteractiveFormResponse>(getLibraryGetInteractiveFormUrl(templateId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates an interactive form for an interactive template.
 * @summary Create interactive form
 */
export type libraryCreateInteractiveFormResponse200 = {
  data: CreateInteractiveFormOutputBody
  status: 200
}

export type libraryCreateInteractiveFormResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryCreateInteractiveFormResponseSuccess = (libraryCreateInteractiveFormResponse200) & {
  headers: Headers;
};
export type libraryCreateInteractiveFormResponseError = (libraryCreateInteractiveFormResponseDefault) & {
  headers: Headers;
};

export type libraryCreateInteractiveFormResponse = (libraryCreateInteractiveFormResponseSuccess | libraryCreateInteractiveFormResponseError)

export const getLibraryCreateInteractiveFormUrl = (templateId: string,) => {


  

  return `/api/v1/admin/library/templates/${templateId}/interactive-form`
}

export const libraryCreateInteractiveForm = async (templateId: string,
    createInteractiveFormRequest: NonReadonly<CreateInteractiveFormRequest>, options?: RequestInit): Promise<libraryCreateInteractiveFormResponse> => {
  
  return customFetch<libraryCreateInteractiveFormResponse>(getLibraryCreateInteractiveFormUrl(templateId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createInteractiveFormRequest,)
  }
);}
  

