/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AskRequest,
  AskResponseBody,
  ErrorModel
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Ask AI a question and get an answer with citations.
 * @summary Ask a question
 */
export type askResponse200 = {
  data: AskResponseBody
  status: 200
}

export type askResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type askResponseSuccess = (askResponse200) & {
  headers: Headers;
};
export type askResponseError = (askResponseDefault) & {
  headers: Headers;
};

export type askResponse = (askResponseSuccess | askResponseError)

export const getAskUrl = () => {


  

  return `/api/v1/ai/ask`
}

export const ask = async (askRequest: NonReadonly<AskRequest>, options?: RequestInit): Promise<askResponse> => {
  
  return customFetch<askResponse>(getAskUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      askRequest,)
  }
);}
  

/**
 * Ask AI a question and receive token chunks as Server-Sent Events.
 * @summary Ask a question with streaming response
 */
export type askStreamResponse200 = {
  data: void
  status: 200
}

export type askStreamResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type askStreamResponseSuccess = (askStreamResponse200) & {
  headers: Headers;
};
export type askStreamResponseError = (askStreamResponseDefault) & {
  headers: Headers;
};

export type askStreamResponse = (askStreamResponseSuccess | askStreamResponseError)

export const getAskStreamUrl = () => {


  

  return `/api/v1/ai/ask/stream`
}

export const askStream = async (askRequest: NonReadonly<AskRequest>, options?: RequestInit): Promise<askStreamResponse> => {
  
  return customFetch<askStreamResponse>(getAskStreamUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      askRequest,)
  }
);}
  

/**
 * Ask AI a question and receive full ReAct loop internals including reasoning, tool calls, and results. Requires admin permission.
 * @summary Ask a question with debug streaming (admin only)
 */
export type askStreamDebugResponse200 = {
  data: void
  status: 200
}

export type askStreamDebugResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type askStreamDebugResponseSuccess = (askStreamDebugResponse200) & {
  headers: Headers;
};
export type askStreamDebugResponseError = (askStreamDebugResponseDefault) & {
  headers: Headers;
};

export type askStreamDebugResponse = (askStreamDebugResponseSuccess | askStreamDebugResponseError)

export const getAskStreamDebugUrl = () => {


  

  return `/api/v1/ai/ask/stream/debug`
}

export const askStreamDebug = async (askRequest: NonReadonly<AskRequest>, options?: RequestInit): Promise<askStreamDebugResponse> => {
  
  return customFetch<askStreamDebugResponse>(getAskStreamDebugUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      askRequest,)
  }
);}
  

