/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ArchiveConversationInputBody,
  ArchiveConversationOutputBody,
  ErrorModel,
  GetConversationInputBody,
  GetConversationOutputBody,
  ListConversationsInputBody,
  ListConversationsOutputBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Get a paginated list of user's conversation sessions.
 * @summary List conversations
 */
export type listConversationsResponse200 = {
  data: ListConversationsOutputBody
  status: 200
}

export type listConversationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listConversationsResponseSuccess = (listConversationsResponse200) & {
  headers: Headers;
};
export type listConversationsResponseError = (listConversationsResponseDefault) & {
  headers: Headers;
};

export type listConversationsResponse = (listConversationsResponseSuccess | listConversationsResponseError)

export const getListConversationsUrl = () => {


  

  return `/api/v1/ai/conversations`
}

export const listConversations = async (listConversationsInputBody: NonReadonly<ListConversationsInputBody>, options?: RequestInit): Promise<listConversationsResponse> => {
  
  return customFetch<listConversationsResponse>(getListConversationsUrl(),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listConversationsInputBody,)
  }
);}
  

/**
 * Archive (soft-delete) a conversation session.
 * @summary Archive conversation
 */
export type archiveConversationResponse200 = {
  data: ArchiveConversationOutputBody
  status: 200
}

export type archiveConversationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type archiveConversationResponseSuccess = (archiveConversationResponse200) & {
  headers: Headers;
};
export type archiveConversationResponseError = (archiveConversationResponseDefault) & {
  headers: Headers;
};

export type archiveConversationResponse = (archiveConversationResponseSuccess | archiveConversationResponseError)

export const getArchiveConversationUrl = (sessionId: string,) => {


  

  return `/api/v1/ai/conversations/${sessionId}`
}

export const archiveConversation = async (sessionId: string,
    archiveConversationInputBody: NonReadonly<ArchiveConversationInputBody>, options?: RequestInit): Promise<archiveConversationResponse> => {
  
  return customFetch<archiveConversationResponse>(getArchiveConversationUrl(sessionId),
  {      
    ...options,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      archiveConversationInputBody,)
  }
);}
  

/**
 * Get a conversation with its messages.
 * @summary Get conversation
 */
export type getConversationResponse200 = {
  data: GetConversationOutputBody
  status: 200
}

export type getConversationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getConversationResponseSuccess = (getConversationResponse200) & {
  headers: Headers;
};
export type getConversationResponseError = (getConversationResponseDefault) & {
  headers: Headers;
};

export type getConversationResponse = (getConversationResponseSuccess | getConversationResponseError)

export const getGetConversationUrl = (sessionId: string,) => {


  

  return `/api/v1/ai/conversations/${sessionId}`
}

export const getConversation = async (sessionId: string,
    getConversationInputBody: NonReadonly<GetConversationInputBody>, options?: RequestInit): Promise<getConversationResponse> => {
  
  return customFetch<getConversationResponse>(getGetConversationUrl(sessionId),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      getConversationInputBody,)
  }
);}
  

