/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  DeadEventDTO,
  ErrorModel,
  ListDeadEventsOutputBody,
  RedriveBatchInputBody,
  RedriveBatchOutputBody,
  RedriveEventInputBody,
  RedriveEventOutputBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Get a paginated list of dead letter queue events for the account.
 * @summary List dead letter events
 */
export type listDeadEventsResponse200 = {
  data: ListDeadEventsOutputBody
  status: 200
}

export type listDeadEventsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listDeadEventsResponseSuccess = (listDeadEventsResponse200) & {
  headers: Headers;
};
export type listDeadEventsResponseError = (listDeadEventsResponseDefault) & {
  headers: Headers;
};

export type listDeadEventsResponse = (listDeadEventsResponseSuccess | listDeadEventsResponseError)

export const getListDeadEventsUrl = () => {


  

  return `/api/v1/ai/ingestion/dlq/events`
}

export const listDeadEvents = async ( options?: RequestInit): Promise<listDeadEventsResponse> => {
  
  return customFetch<listDeadEventsResponse>(getListDeadEventsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Redrive multiple dead events in a single request.
 * @summary Redrive batch
 */
export type redriveBatchResponse200 = {
  data: RedriveBatchOutputBody
  status: 200
}

export type redriveBatchResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type redriveBatchResponseSuccess = (redriveBatchResponse200) & {
  headers: Headers;
};
export type redriveBatchResponseError = (redriveBatchResponseDefault) & {
  headers: Headers;
};

export type redriveBatchResponse = (redriveBatchResponseSuccess | redriveBatchResponseError)

export const getRedriveBatchUrl = () => {


  

  return `/api/v1/ai/ingestion/dlq/events/batch/redrive`
}

export const redriveBatch = async (redriveBatchInputBody: NonReadonly<RedriveBatchInputBody>, options?: RequestInit): Promise<redriveBatchResponse> => {
  
  return customFetch<redriveBatchResponse>(getRedriveBatchUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      redriveBatchInputBody,)
  }
);}
  

/**
 * Get a specific dead letter queue event by ID.
 * @summary Get dead event
 */
export type getDeadEventResponse200 = {
  data: DeadEventDTO
  status: 200
}

export type getDeadEventResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDeadEventResponseSuccess = (getDeadEventResponse200) & {
  headers: Headers;
};
export type getDeadEventResponseError = (getDeadEventResponseDefault) & {
  headers: Headers;
};

export type getDeadEventResponse = (getDeadEventResponseSuccess | getDeadEventResponseError)

export const getGetDeadEventUrl = (eventId: string,) => {


  

  return `/api/v1/ai/ingestion/dlq/events/${eventId}`
}

export const getDeadEvent = async (eventId: string, options?: RequestInit): Promise<getDeadEventResponse> => {
  
  return customFetch<getDeadEventResponse>(getGetDeadEventUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Redrive a dead event back to the processing queue.
 * @summary Redrive single event
 */
export type redriveEventResponse200 = {
  data: RedriveEventOutputBody
  status: 200
}

export type redriveEventResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type redriveEventResponseSuccess = (redriveEventResponse200) & {
  headers: Headers;
};
export type redriveEventResponseError = (redriveEventResponseDefault) & {
  headers: Headers;
};

export type redriveEventResponse = (redriveEventResponseSuccess | redriveEventResponseError)

export const getRedriveEventUrl = (eventId: string,) => {


  

  return `/api/v1/ai/ingestion/dlq/events/${eventId}/redrive`
}

export const redriveEvent = async (eventId: string,
    redriveEventInputBody: NonReadonly<RedriveEventInputBody>, options?: RequestInit): Promise<redriveEventResponse> => {
  
  return customFetch<redriveEventResponse>(getRedriveEventUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      redriveEventInputBody,)
  }
);}
  

