/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateUploadIntentRequest,
  CreateUploadIntentResponseBody,
  DeleteDocumentResponseBody,
  ErrorModel,
  FinalizeUploadRequest,
  FinalizeUploadResponseBody,
  IngestToggleStateResponse,
  SetIngestToggleInputBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Soft-deletes an ingestion document and its status projection.
 * @summary Delete ingestion document
 */
export type deleteIngestionDocumentResponse200 = {
  data: DeleteDocumentResponseBody
  status: 200
}

export type deleteIngestionDocumentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteIngestionDocumentResponseSuccess = (deleteIngestionDocumentResponse200) & {
  headers: Headers;
};
export type deleteIngestionDocumentResponseError = (deleteIngestionDocumentResponseDefault) & {
  headers: Headers;
};

export type deleteIngestionDocumentResponse = (deleteIngestionDocumentResponseSuccess | deleteIngestionDocumentResponseError)

export const getDeleteIngestionDocumentUrl = (documentId: string,) => {


  

  return `/api/v1/ai/ingestion/documents/${documentId}`
}

export const deleteIngestionDocument = async (documentId: string, options?: RequestInit): Promise<deleteIngestionDocumentResponse> => {
  
  return customFetch<deleteIngestionDocumentResponse>(getDeleteIngestionDocumentUrl(documentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Get the current ingestion toggle state.
 * @summary Get ingestion toggle
 */
export type getIngestionToggleResponse200 = {
  data: IngestToggleStateResponse
  status: 200
}

export type getIngestionToggleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getIngestionToggleResponseSuccess = (getIngestionToggleResponse200) & {
  headers: Headers;
};
export type getIngestionToggleResponseError = (getIngestionToggleResponseDefault) & {
  headers: Headers;
};

export type getIngestionToggleResponse = (getIngestionToggleResponseSuccess | getIngestionToggleResponseError)

export const getGetIngestionToggleUrl = () => {


  

  return `/api/v1/ai/ingestion/toggle`
}

export const getIngestionToggle = async ( options?: RequestInit): Promise<getIngestionToggleResponse> => {
  
  return customFetch<getIngestionToggleResponse>(getGetIngestionToggleUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Enable or disable document ingestion for the account.
 * @summary Set ingestion toggle
 */
export type setIngestionToggleResponse200 = {
  data: IngestToggleStateResponse
  status: 200
}

export type setIngestionToggleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type setIngestionToggleResponseSuccess = (setIngestionToggleResponse200) & {
  headers: Headers;
};
export type setIngestionToggleResponseError = (setIngestionToggleResponseDefault) & {
  headers: Headers;
};

export type setIngestionToggleResponse = (setIngestionToggleResponseSuccess | setIngestionToggleResponseError)

export const getSetIngestionToggleUrl = () => {


  

  return `/api/v1/ai/ingestion/toggle`
}

export const setIngestionToggle = async (setIngestToggleInputBody: NonReadonly<SetIngestToggleInputBody>, options?: RequestInit): Promise<setIngestionToggleResponse> => {
  
  return customFetch<setIngestionToggleResponse>(getSetIngestionToggleUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setIngestToggleInputBody,)
  }
);}
  

/**
 * Validates uploaded object metadata, writes ingestion metadata and outbox entry atomically.
 * @summary Finalize uploaded document ingestion
 */
export type finalizeIngestionUploadResponse200 = {
  data: FinalizeUploadResponseBody
  status: 200
}

export type finalizeIngestionUploadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type finalizeIngestionUploadResponseSuccess = (finalizeIngestionUploadResponse200) & {
  headers: Headers;
};
export type finalizeIngestionUploadResponseError = (finalizeIngestionUploadResponseDefault) & {
  headers: Headers;
};

export type finalizeIngestionUploadResponse = (finalizeIngestionUploadResponseSuccess | finalizeIngestionUploadResponseError)

export const getFinalizeIngestionUploadUrl = () => {


  

  return `/api/v1/ai/ingestion/uploads/finalize`
}

export const finalizeIngestionUpload = async (finalizeUploadRequest: NonReadonly<FinalizeUploadRequest>, options?: RequestInit): Promise<finalizeIngestionUploadResponse> => {
  
  return customFetch<finalizeIngestionUploadResponse>(getFinalizeIngestionUploadUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      finalizeUploadRequest,)
  }
);}
  

/**
 * Generates a SeaweedFS direct-upload URL and required headers.
 * @summary Create direct upload intent
 */
export type createIngestionUploadIntentResponse200 = {
  data: CreateUploadIntentResponseBody
  status: 200
}

export type createIngestionUploadIntentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createIngestionUploadIntentResponseSuccess = (createIngestionUploadIntentResponse200) & {
  headers: Headers;
};
export type createIngestionUploadIntentResponseError = (createIngestionUploadIntentResponseDefault) & {
  headers: Headers;
};

export type createIngestionUploadIntentResponse = (createIngestionUploadIntentResponseSuccess | createIngestionUploadIntentResponseError)

export const getCreateIngestionUploadIntentUrl = () => {


  

  return `/api/v1/ai/ingestion/uploads/intents`
}

export const createIngestionUploadIntent = async (createUploadIntentRequest: NonReadonly<CreateUploadIntentRequest>, options?: RequestInit): Promise<createIngestionUploadIntentResponse> => {
  
  return customFetch<createIngestionUploadIntentResponse>(getCreateIngestionUploadIntentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createUploadIntentRequest,)
  }
);}
  

