/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  GetStatusByDocumentInputBody,
  IngestionStatusProjectionResponse,
  ListStatusByAccountInputBody,
  ListStatusByAccountOutputBody,
  ListStatusByUserInputBody,
  ListStatusByUserOutputBody,
  StreamStatusByDocumentInputBody,
  StreamStatusInputBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns a paginated list of ingestion statuses for an account.
 * @summary List ingestion status by account ID
 */
export type listIngestionStatusByAccountIDResponse200 = {
  data: ListStatusByAccountOutputBody
  status: 200
}

export type listIngestionStatusByAccountIDResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listIngestionStatusByAccountIDResponseSuccess = (listIngestionStatusByAccountIDResponse200) & {
  headers: Headers;
};
export type listIngestionStatusByAccountIDResponseError = (listIngestionStatusByAccountIDResponseDefault) & {
  headers: Headers;
};

export type listIngestionStatusByAccountIDResponse = (listIngestionStatusByAccountIDResponseSuccess | listIngestionStatusByAccountIDResponseError)

export const getListIngestionStatusByAccountIDUrl = (accountId: string,) => {


  

  return `/api/v1/ai/ingestion/status/accounts/${accountId}`
}

export const listIngestionStatusByAccountID = async (accountId: string,
    listStatusByAccountInputBody: NonReadonly<ListStatusByAccountInputBody>, options?: RequestInit): Promise<listIngestionStatusByAccountIDResponse> => {
  
  return customFetch<listIngestionStatusByAccountIDResponse>(getListIngestionStatusByAccountIDUrl(accountId),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listStatusByAccountInputBody,)
  }
);}
  

/**
 * Subscribe to real-time ingestion status updates for a specific document via SSE.
 * @summary Stream ingestion status by document ID
 */
export type streamIngestionStatusByDocumentResponse200 = {
  data: void
  status: 200
}

export type streamIngestionStatusByDocumentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type streamIngestionStatusByDocumentResponseSuccess = (streamIngestionStatusByDocumentResponse200) & {
  headers: Headers;
};
export type streamIngestionStatusByDocumentResponseError = (streamIngestionStatusByDocumentResponseDefault) & {
  headers: Headers;
};

export type streamIngestionStatusByDocumentResponse = (streamIngestionStatusByDocumentResponseSuccess | streamIngestionStatusByDocumentResponseError)

export const getStreamIngestionStatusByDocumentUrl = (documentId: string,) => {


  

  return `/api/v1/ai/ingestion/status/document/${documentId}/stream`
}

export const streamIngestionStatusByDocument = async (documentId: string,
    streamStatusByDocumentInputBody: NonReadonly<StreamStatusByDocumentInputBody>, options?: RequestInit): Promise<streamIngestionStatusByDocumentResponse> => {
  
  return customFetch<streamIngestionStatusByDocumentResponse>(getStreamIngestionStatusByDocumentUrl(documentId),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      streamStatusByDocumentInputBody,)
  }
);}
  

/**
 * Returns the current ingestion status for a document.
 * @summary Get ingestion status by document ID
 */
export type getIngestionStatusByDocumentIDResponse200 = {
  data: IngestionStatusProjectionResponse
  status: 200
}

export type getIngestionStatusByDocumentIDResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getIngestionStatusByDocumentIDResponseSuccess = (getIngestionStatusByDocumentIDResponse200) & {
  headers: Headers;
};
export type getIngestionStatusByDocumentIDResponseError = (getIngestionStatusByDocumentIDResponseDefault) & {
  headers: Headers;
};

export type getIngestionStatusByDocumentIDResponse = (getIngestionStatusByDocumentIDResponseSuccess | getIngestionStatusByDocumentIDResponseError)

export const getGetIngestionStatusByDocumentIDUrl = (documentId: string,) => {


  

  return `/api/v1/ai/ingestion/status/documents/${documentId}`
}

export const getIngestionStatusByDocumentID = async (documentId: string,
    getStatusByDocumentInputBody: NonReadonly<GetStatusByDocumentInputBody>, options?: RequestInit): Promise<getIngestionStatusByDocumentIDResponse> => {
  
  return customFetch<getIngestionStatusByDocumentIDResponse>(getGetIngestionStatusByDocumentIDUrl(documentId),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      getStatusByDocumentInputBody,)
  }
);}
  

/**
 * Subscribe to real-time ingestion status updates via SSE.
 * @summary Stream ingestion status
 */
export type streamIngestionStatusResponse200 = {
  data: void
  status: 200
}

export type streamIngestionStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type streamIngestionStatusResponseSuccess = (streamIngestionStatusResponse200) & {
  headers: Headers;
};
export type streamIngestionStatusResponseError = (streamIngestionStatusResponseDefault) & {
  headers: Headers;
};

export type streamIngestionStatusResponse = (streamIngestionStatusResponseSuccess | streamIngestionStatusResponseError)

export const getStreamIngestionStatusUrl = () => {


  

  return `/api/v1/ai/ingestion/status/stream`
}

export const streamIngestionStatus = async (streamStatusInputBody: NonReadonly<StreamStatusInputBody>, options?: RequestInit): Promise<streamIngestionStatusResponse> => {
  
  return customFetch<streamIngestionStatusResponse>(getStreamIngestionStatusUrl(),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      streamStatusInputBody,)
  }
);}
  

/**
 * Returns a paginated list of ingestion statuses for a user.
 * @summary List ingestion status by user ID
 */
export type listIngestionStatusByUserIDResponse200 = {
  data: ListStatusByUserOutputBody
  status: 200
}

export type listIngestionStatusByUserIDResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listIngestionStatusByUserIDResponseSuccess = (listIngestionStatusByUserIDResponse200) & {
  headers: Headers;
};
export type listIngestionStatusByUserIDResponseError = (listIngestionStatusByUserIDResponseDefault) & {
  headers: Headers;
};

export type listIngestionStatusByUserIDResponse = (listIngestionStatusByUserIDResponseSuccess | listIngestionStatusByUserIDResponseError)

export const getListIngestionStatusByUserIDUrl = (userId: string,) => {


  

  return `/api/v1/ai/ingestion/status/users/${userId}`
}

export const listIngestionStatusByUserID = async (userId: string,
    listStatusByUserInputBody: NonReadonly<ListStatusByUserInputBody>, options?: RequestInit): Promise<listIngestionStatusByUserIDResponse> => {
  
  return customFetch<listIngestionStatusByUserIDResponse>(getListIngestionStatusByUserIDUrl(userId),
  {      
    ...options,
    method: 'GET',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      listStatusByUserInputBody,)
  }
);}
  

