/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AdminRegisterRequest,
  AdminRegisterResponseBody,
  AdminUpdateRolesOutputBody,
  AdminUpdateRolesRequest,
  ErrorModel,
  GetCurrentUserResponseBody,
  LoginRequest,
  LoginResponseBody,
  RefreshResponseBody,
  RegisterRequest,
  RegisterResponseBody,
  ResendEmailOTPResponseBody,
  UpdateAccountPasswordRequest,
  UpdateAccountPasswordResponseBody,
  VerifyEmailOTPRequest,
  VerifyEmailOTPResponseBody
} from '../types';




// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Creates an admin account and emails the generated password.
 * @summary Register a new admin
 */
export type registerAdminResponse200 = {
  data: AdminRegisterResponseBody
  status: 200
}

export type registerAdminResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type registerAdminResponseSuccess = (registerAdminResponse200) & {
  headers: Headers;
};
export type registerAdminResponseError = (registerAdminResponseDefault) & {
  headers: Headers;
};

export type registerAdminResponse = (registerAdminResponseSuccess | registerAdminResponseError)

export const getRegisterAdminUrl = () => {


  

  return `/api/v1/auth/admin/register`
}

export const registerAdmin = async (adminRegisterRequest: NonReadonly<AdminRegisterRequest>, options?: RequestInit): Promise<registerAdminResponse> => {
  
  const res = await fetch(getRegisterAdminUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminRegisterRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerAdminResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerAdminResponse
}
  

/**
 * Replaces roles assigned to an admin account.
 * @summary Update admin roles
 */
export type updateAdminRolesResponse200 = {
  data: AdminUpdateRolesOutputBody
  status: 200
}

export type updateAdminRolesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateAdminRolesResponseSuccess = (updateAdminRolesResponse200) & {
  headers: Headers;
};
export type updateAdminRolesResponseError = (updateAdminRolesResponseDefault) & {
  headers: Headers;
};

export type updateAdminRolesResponse = (updateAdminRolesResponseSuccess | updateAdminRolesResponseError)

export const getUpdateAdminRolesUrl = (accountId: string,) => {


  

  return `/api/v1/auth/admin/${accountId}/roles`
}

export const updateAdminRoles = async (accountId: string,
    adminUpdateRolesRequest: NonReadonly<AdminUpdateRolesRequest>, options?: RequestInit): Promise<updateAdminRolesResponse> => {
  
  const res = await fetch(getUpdateAdminRolesUrl(accountId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      adminUpdateRolesRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateAdminRolesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateAdminRolesResponse
}
  

/**
 * Authenticates a user with email or username and password, returns authentication tokens.
 * @summary Log in a user
 */
export type loginResponse200 = {
  data: LoginResponseBody
  status: 200
}

export type loginResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponseDefault) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {


  

  return `/api/v1/auth/login`
}

export const login = async (loginRequest: NonReadonly<LoginRequest>, options?: RequestInit): Promise<loginResponse> => {
  
  const res = await fetch(getLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}
  

/**
 * Revokes the current session and clears the refresh token cookie.
 * @summary Log out current session
 */
export type logoutResponse200 = {
  data: void
  status: 200
}

export type logoutResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type logoutResponseSuccess = (logoutResponse200) & {
  headers: Headers;
};
export type logoutResponseError = (logoutResponseDefault) & {
  headers: Headers;
};

export type logoutResponse = (logoutResponseSuccess | logoutResponseError)

export const getLogoutUrl = () => {


  

  return `/api/v1/auth/logout`
}

export const logout = async ( options?: RequestInit): Promise<logoutResponse> => {
  
  const res = await fetch(getLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: logoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutResponse
}
  

/**
 * Revokes all sessions for the current user's account and clears the refresh token cookie.
 * @summary Log out all sessions
 */
export type logoutAllResponse200 = {
  data: void
  status: 200
}

export type logoutAllResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type logoutAllResponseSuccess = (logoutAllResponse200) & {
  headers: Headers;
};
export type logoutAllResponseError = (logoutAllResponseDefault) & {
  headers: Headers;
};

export type logoutAllResponse = (logoutAllResponseSuccess | logoutAllResponseError)

export const getLogoutAllUrl = () => {


  

  return `/api/v1/auth/logout/all`
}

export const logoutAll = async ( options?: RequestInit): Promise<logoutAllResponse> => {
  
  const res = await fetch(getLogoutAllUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: logoutAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as logoutAllResponse
}
  

/**
 * Returns the current authenticated user's profile and account information.
 * @summary Get current user
 */
export type getCurrentUserResponse200 = {
  data: GetCurrentUserResponseBody
  status: 200
}

export type getCurrentUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCurrentUserResponseSuccess = (getCurrentUserResponse200) & {
  headers: Headers;
};
export type getCurrentUserResponseError = (getCurrentUserResponseDefault) & {
  headers: Headers;
};

export type getCurrentUserResponse = (getCurrentUserResponseSuccess | getCurrentUserResponseError)

export const getGetCurrentUserUrl = () => {


  

  return `/api/v1/auth/me`
}

export const getCurrentUser = async ( options?: RequestInit): Promise<getCurrentUserResponse> => {
  
  const res = await fetch(getGetCurrentUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCurrentUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCurrentUserResponse
}
  

/**
 * Uses the refresh token cookie to issue new access and refresh tokens. Implements token rotation for security.
 * @summary Refresh access token
 */
export type refreshResponse200 = {
  data: RefreshResponseBody
  status: 200
}

export type refreshResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type refreshResponseSuccess = (refreshResponse200) & {
  headers: Headers;
};
export type refreshResponseError = (refreshResponseDefault) & {
  headers: Headers;
};

export type refreshResponse = (refreshResponseSuccess | refreshResponseError)

export const getRefreshUrl = () => {


  

  return `/api/v1/auth/refresh`
}

export const refresh = async ( options?: RequestInit): Promise<refreshResponse> => {
  
  const res = await fetch(getRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: refreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as refreshResponse
}
  

/**
 * Creates a new user account and returns authentication tokens. The user is automatically logged in after registration.
 * @summary Register a new user
 */
export type registerResponse200 = {
  data: RegisterResponseBody
  status: 200
}

export type registerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type registerResponseSuccess = (registerResponse200) & {
  headers: Headers;
};
export type registerResponseError = (registerResponseDefault) & {
  headers: Headers;
};

export type registerResponse = (registerResponseSuccess | registerResponseError)

export const getRegisterUrl = () => {


  

  return `/api/v1/auth/register`
}

export const register = async (registerRequest: NonReadonly<RegisterRequest>, options?: RequestInit): Promise<registerResponse> => {
  
  const res = await fetch(getRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: registerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerResponse
}
  

/**
 * Resends a new one-time password for email verification with cooldown and resend limits.
 * @summary Resend account email OTP
 */
export type resendEmailOTPResponse200 = {
  data: ResendEmailOTPResponseBody
  status: 200
}

export type resendEmailOTPResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type resendEmailOTPResponseSuccess = (resendEmailOTPResponse200) & {
  headers: Headers;
};
export type resendEmailOTPResponseError = (resendEmailOTPResponseDefault) & {
  headers: Headers;
};

export type resendEmailOTPResponse = (resendEmailOTPResponseSuccess | resendEmailOTPResponseError)

export const getResendEmailOTPUrl = () => {


  

  return `/api/v1/auth/resend-email-otp`
}

export const resendEmailOTP = async ( options?: RequestInit): Promise<resendEmailOTPResponse> => {
  
  const res = await fetch(getResendEmailOTPUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: resendEmailOTPResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resendEmailOTPResponse
}
  

/**
 * Updates account password
 * @summary Update account password
 */
export type accountPasswordResponse200 = {
  data: UpdateAccountPasswordResponseBody
  status: 200
}

export type accountPasswordResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type accountPasswordResponseSuccess = (accountPasswordResponse200) & {
  headers: Headers;
};
export type accountPasswordResponseError = (accountPasswordResponseDefault) & {
  headers: Headers;
};

export type accountPasswordResponse = (accountPasswordResponseSuccess | accountPasswordResponseError)

export const getAccountPasswordUrl = () => {


  

  return `/api/v1/auth/user/updatePassword`
}

export const accountPassword = async (updateAccountPasswordRequest: NonReadonly<UpdateAccountPasswordRequest>, options?: RequestInit): Promise<accountPasswordResponse> => {
  
  const res = await fetch(getAccountPasswordUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateAccountPasswordRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: accountPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as accountPasswordResponse
}
  

/**
 * Verifies pending account email using a one-time password and activates the account.
 * @summary Verify account email with OTP
 */
export type verifyEmailOTPResponse200 = {
  data: VerifyEmailOTPResponseBody
  status: 200
}

export type verifyEmailOTPResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type verifyEmailOTPResponseSuccess = (verifyEmailOTPResponse200) & {
  headers: Headers;
};
export type verifyEmailOTPResponseError = (verifyEmailOTPResponseDefault) & {
  headers: Headers;
};

export type verifyEmailOTPResponse = (verifyEmailOTPResponseSuccess | verifyEmailOTPResponseError)

export const getVerifyEmailOTPUrl = () => {


  

  return `/api/v1/auth/verify-email-otp`
}

export const verifyEmailOTP = async (verifyEmailOTPRequest: NonReadonly<VerifyEmailOTPRequest>, options?: RequestInit): Promise<verifyEmailOTPResponse> => {
  
  const res = await fetch(getVerifyEmailOTPUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailOTPRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: verifyEmailOTPResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as verifyEmailOTPResponse
}
  

