/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  BusinessProfileResponse,
  CreateBusinessProfileRequest,
  ErrorModel,
  UpdateBusinessProfileRequest
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Retrieves the authenticated user's business profile.
 * @summary Get business profile
 */
export type getBusinessProfileResponse200 = {
  data: BusinessProfileResponse
  status: 200
}

export type getBusinessProfileResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getBusinessProfileResponseSuccess = (getBusinessProfileResponse200) & {
  headers: Headers;
};
export type getBusinessProfileResponseError = (getBusinessProfileResponseDefault) & {
  headers: Headers;
};

export type getBusinessProfileResponse = (getBusinessProfileResponseSuccess | getBusinessProfileResponseError)

export const getGetBusinessProfileUrl = () => {


  

  return `/api/v1/users/business-profile`
}

export const getBusinessProfile = async ( options?: RequestInit): Promise<getBusinessProfileResponse> => {
  
  return customFetch<getBusinessProfileResponse>(getGetBusinessProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a business profile for the authenticated user. Accepts slugs for sector and tags, which are resolved server-side. Auto-fills company name, email, and phone from account data if omitted.
 * @summary Create business profile
 */
export type createBusinessProfileResponse200 = {
  data: BusinessProfileResponse
  status: 200
}

export type createBusinessProfileResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createBusinessProfileResponseSuccess = (createBusinessProfileResponse200) & {
  headers: Headers;
};
export type createBusinessProfileResponseError = (createBusinessProfileResponseDefault) & {
  headers: Headers;
};

export type createBusinessProfileResponse = (createBusinessProfileResponseSuccess | createBusinessProfileResponseError)

export const getCreateBusinessProfileUrl = () => {


  

  return `/api/v1/users/business-profile`
}

export const createBusinessProfile = async (createBusinessProfileRequest: NonReadonly<CreateBusinessProfileRequest>, options?: RequestInit): Promise<createBusinessProfileResponse> => {
  
  return customFetch<createBusinessProfileResponse>(getCreateBusinessProfileUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createBusinessProfileRequest,)
  }
);}
  

/**
 * Updates the authenticated user's business profile. Accepts slugs for sector and tags, which are resolved server-side.
 * @summary Update business profile
 */
export type updateBusinessProfileResponse200 = {
  data: BusinessProfileResponse
  status: 200
}

export type updateBusinessProfileResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateBusinessProfileResponseSuccess = (updateBusinessProfileResponse200) & {
  headers: Headers;
};
export type updateBusinessProfileResponseError = (updateBusinessProfileResponseDefault) & {
  headers: Headers;
};

export type updateBusinessProfileResponse = (updateBusinessProfileResponseSuccess | updateBusinessProfileResponseError)

export const getUpdateBusinessProfileUrl = () => {


  

  return `/api/v1/users/business-profile`
}

export const updateBusinessProfile = async (updateBusinessProfileRequest: NonReadonly<UpdateBusinessProfileRequest>, options?: RequestInit): Promise<updateBusinessProfileResponse> => {
  
  return customFetch<updateBusinessProfileResponse>(getUpdateBusinessProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBusinessProfileRequest,)
  }
);}
  

