/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  BlockUserRequest,
  BlockUserResponseBody,
  CreateCommunityPostBody,
  CreateCommunityThreadBody,
  CreatePostResponseBody,
  CreateThreadResponseBody,
  DeletePostResponseBody,
  DeleteThreadResponseBody,
  ErrorModel,
  FollowResponseBody,
  GetCategoryResponseBody,
  GetThreadResponseBody,
  ListAllCommunityThreadsParams,
  ListCategoriesResponseBody,
  ListCommunityCategoriesParams,
  ListCommunityPostsParams,
  ListCommunityThreadsParams,
  ListFollowedCategoriesParams,
  ListFollowedCategoriesResponseBody,
  ListFollowedThreadsParams,
  ListFollowedThreadsResponseBody,
  ListPostsResponseBody,
  ListThreadsResponseBody,
  MarkSolutionResponseBody,
  ReplyCommunityPostBody,
  ReportPostRequest,
  ReportPostResponseBody,
  ReportThreadRequest,
  ReportThreadResponseBody,
  ReportUserRequest,
  ReportUserResponseBody,
  SearchCommunityThreadsParams,
  UpdateCommunityPostBody,
  UpdateCommunityThreadBody,
  UpdatePostResponseBody,
  UpdateThreadResponseBody,
  UploadAttachmentsBody,
  UploadAttachmentsResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Uploads one or more attachments for later use when creating/updating posts.
 * @summary Upload attachments
 */
export type uploadAttachmentsResponse200 = {
  data: UploadAttachmentsResponseBody
  status: 200
}

export type uploadAttachmentsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type uploadAttachmentsResponseSuccess = (uploadAttachmentsResponse200) & {
  headers: Headers;
};
export type uploadAttachmentsResponseError = (uploadAttachmentsResponseDefault) & {
  headers: Headers;
};

export type uploadAttachmentsResponse = (uploadAttachmentsResponseSuccess | uploadAttachmentsResponseError)

export const getUploadAttachmentsUrl = () => {


  

  return `/api/v1/community/attachments`
}

export const uploadAttachments = async (uploadAttachmentsBody: UploadAttachmentsBody, options?: RequestInit): Promise<uploadAttachmentsResponse> => {
    const formData = new FormData();
uploadAttachmentsBody.files.forEach(value => formData.append(`files`, value));

  return customFetch<uploadAttachmentsResponse>(getUploadAttachmentsUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Deletes a pending attachment that was uploaded but not yet linked to a post.
 * @summary Delete orphan attachment
 */
export type deleteOrphanAttachmentResponse200 = {
  data: DeletePostResponseBody
  status: 200
}

export type deleteOrphanAttachmentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteOrphanAttachmentResponseSuccess = (deleteOrphanAttachmentResponse200) & {
  headers: Headers;
};
export type deleteOrphanAttachmentResponseError = (deleteOrphanAttachmentResponseDefault) & {
  headers: Headers;
};

export type deleteOrphanAttachmentResponse = (deleteOrphanAttachmentResponseSuccess | deleteOrphanAttachmentResponseError)

export const getDeleteOrphanAttachmentUrl = (id: string,) => {


  

  return `/api/v1/community/attachments/${id}`
}

export const deleteOrphanAttachment = async (id: string, options?: RequestInit): Promise<deleteOrphanAttachmentResponse> => {
  
  return customFetch<deleteOrphanAttachmentResponse>(getDeleteOrphanAttachmentUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Lists active community categories.
 * @summary List community categories
 */
export type listCommunityCategoriesResponse200 = {
  data: ListCategoriesResponseBody
  status: 200
}

export type listCommunityCategoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listCommunityCategoriesResponseSuccess = (listCommunityCategoriesResponse200) & {
  headers: Headers;
};
export type listCommunityCategoriesResponseError = (listCommunityCategoriesResponseDefault) & {
  headers: Headers;
};

export type listCommunityCategoriesResponse = (listCommunityCategoriesResponseSuccess | listCommunityCategoriesResponseError)

export const getListCommunityCategoriesUrl = (params?: ListCommunityCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/categories?${stringifiedParams}` : `/api/v1/community/categories`
}

export const listCommunityCategories = async (params?: ListCommunityCategoriesParams, options?: RequestInit): Promise<listCommunityCategoriesResponse> => {
  
  return customFetch<listCommunityCategoriesResponse>(getListCommunityCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Retrieves community category details.
 * @summary Get community category
 */
export type getCommunityCategoryResponse200 = {
  data: GetCategoryResponseBody
  status: 200
}

export type getCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCommunityCategoryResponseSuccess = (getCommunityCategoryResponse200) & {
  headers: Headers;
};
export type getCommunityCategoryResponseError = (getCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type getCommunityCategoryResponse = (getCommunityCategoryResponseSuccess | getCommunityCategoryResponseError)

export const getGetCommunityCategoryUrl = (id: string,) => {


  

  return `/api/v1/community/categories/${id}`
}

export const getCommunityCategory = async (id: string, options?: RequestInit): Promise<getCommunityCategoryResponse> => {
  
  return customFetch<getCommunityCategoryResponse>(getGetCommunityCategoryUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Unfollows a community category.
 * @summary Unfollow category
 */
export type unfollowCommunityCategoryResponse200 = {
  data: FollowResponseBody
  status: 200
}

export type unfollowCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type unfollowCommunityCategoryResponseSuccess = (unfollowCommunityCategoryResponse200) & {
  headers: Headers;
};
export type unfollowCommunityCategoryResponseError = (unfollowCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type unfollowCommunityCategoryResponse = (unfollowCommunityCategoryResponseSuccess | unfollowCommunityCategoryResponseError)

export const getUnfollowCommunityCategoryUrl = (id: string,) => {


  

  return `/api/v1/community/categories/${id}/follow`
}

export const unfollowCommunityCategory = async (id: string, options?: RequestInit): Promise<unfollowCommunityCategoryResponse> => {
  
  return customFetch<unfollowCommunityCategoryResponse>(getUnfollowCommunityCategoryUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Follows a community category.
 * @summary Follow category
 */
export type followCommunityCategoryResponse200 = {
  data: FollowResponseBody
  status: 200
}

export type followCommunityCategoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type followCommunityCategoryResponseSuccess = (followCommunityCategoryResponse200) & {
  headers: Headers;
};
export type followCommunityCategoryResponseError = (followCommunityCategoryResponseDefault) & {
  headers: Headers;
};

export type followCommunityCategoryResponse = (followCommunityCategoryResponseSuccess | followCommunityCategoryResponseError)

export const getFollowCommunityCategoryUrl = (id: string,) => {


  

  return `/api/v1/community/categories/${id}/follow`
}

export const followCommunityCategory = async (id: string, options?: RequestInit): Promise<followCommunityCategoryResponse> => {
  
  return customFetch<followCommunityCategoryResponse>(getFollowCommunityCategoryUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Lists categories followed by the current user.
 * @summary List followed categories
 */
export type listFollowedCategoriesResponse200 = {
  data: ListFollowedCategoriesResponseBody
  status: 200
}

export type listFollowedCategoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listFollowedCategoriesResponseSuccess = (listFollowedCategoriesResponse200) & {
  headers: Headers;
};
export type listFollowedCategoriesResponseError = (listFollowedCategoriesResponseDefault) & {
  headers: Headers;
};

export type listFollowedCategoriesResponse = (listFollowedCategoriesResponseSuccess | listFollowedCategoriesResponseError)

export const getListFollowedCategoriesUrl = (params?: ListFollowedCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/follows/categories?${stringifiedParams}` : `/api/v1/community/follows/categories`
}

export const listFollowedCategories = async (params?: ListFollowedCategoriesParams, options?: RequestInit): Promise<listFollowedCategoriesResponse> => {
  
  return customFetch<listFollowedCategoriesResponse>(getListFollowedCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists threads followed by the current user.
 * @summary List followed threads
 */
export type listFollowedThreadsResponse200 = {
  data: ListFollowedThreadsResponseBody
  status: 200
}

export type listFollowedThreadsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listFollowedThreadsResponseSuccess = (listFollowedThreadsResponse200) & {
  headers: Headers;
};
export type listFollowedThreadsResponseError = (listFollowedThreadsResponseDefault) & {
  headers: Headers;
};

export type listFollowedThreadsResponse = (listFollowedThreadsResponseSuccess | listFollowedThreadsResponseError)

export const getListFollowedThreadsUrl = (params?: ListFollowedThreadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/follows/threads?${stringifiedParams}` : `/api/v1/community/follows/threads`
}

export const listFollowedThreads = async (params?: ListFollowedThreadsParams, options?: RequestInit): Promise<listFollowedThreadsResponse> => {
  
  return customFetch<listFollowedThreadsResponse>(getListFollowedThreadsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Deletes a post.
 * @summary Delete post
 */
export type deleteCommunityPostResponse200 = {
  data: DeletePostResponseBody
  status: 200
}

export type deleteCommunityPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteCommunityPostResponseSuccess = (deleteCommunityPostResponse200) & {
  headers: Headers;
};
export type deleteCommunityPostResponseError = (deleteCommunityPostResponseDefault) & {
  headers: Headers;
};

export type deleteCommunityPostResponse = (deleteCommunityPostResponseSuccess | deleteCommunityPostResponseError)

export const getDeleteCommunityPostUrl = (id: string,) => {


  

  return `/api/v1/community/posts/${id}`
}

export const deleteCommunityPost = async (id: string, options?: RequestInit): Promise<deleteCommunityPostResponse> => {
  
  return customFetch<deleteCommunityPostResponse>(getDeleteCommunityPostUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates a post.
 * @summary Update post
 */
export type updateCommunityPostResponse200 = {
  data: UpdatePostResponseBody
  status: 200
}

export type updateCommunityPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCommunityPostResponseSuccess = (updateCommunityPostResponse200) & {
  headers: Headers;
};
export type updateCommunityPostResponseError = (updateCommunityPostResponseDefault) & {
  headers: Headers;
};

export type updateCommunityPostResponse = (updateCommunityPostResponseSuccess | updateCommunityPostResponseError)

export const getUpdateCommunityPostUrl = (id: string,) => {


  

  return `/api/v1/community/posts/${id}`
}

export const updateCommunityPost = async (id: string,
    updateCommunityPostBody: UpdateCommunityPostBody, options?: RequestInit): Promise<updateCommunityPostResponse> => {
    const formData = new FormData();
if(updateCommunityPostBody.attachmentIds !== undefined) {
 formData.append(`attachmentIds`, updateCommunityPostBody.attachmentIds instanceof Blob ? updateCommunityPostBody.attachmentIds : new Blob([updateCommunityPostBody.attachmentIds], { type: 'text/plain' }));
 }
formData.append(`content`, updateCommunityPostBody.content instanceof Blob ? updateCommunityPostBody.content : new Blob([updateCommunityPostBody.content], { type: 'text/plain' }));
formData.append(`removeAllAttachments`, updateCommunityPostBody.removeAllAttachments.toString())
if(updateCommunityPostBody.removeAttachmentIds !== undefined) {
 formData.append(`removeAttachmentIds`, updateCommunityPostBody.removeAttachmentIds instanceof Blob ? updateCommunityPostBody.removeAttachmentIds : new Blob([updateCommunityPostBody.removeAttachmentIds], { type: 'text/plain' }));
 }

  return customFetch<updateCommunityPostResponse>(getUpdateCommunityPostUrl(id),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Lists discussion threads filtered by user's business profile taxonomy.
 * @summary List discussion threads
 */
export type listCommunityThreadsResponse200 = {
  data: ListThreadsResponseBody
  status: 200
}

export type listCommunityThreadsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listCommunityThreadsResponseSuccess = (listCommunityThreadsResponse200) & {
  headers: Headers;
};
export type listCommunityThreadsResponseError = (listCommunityThreadsResponseDefault) & {
  headers: Headers;
};

export type listCommunityThreadsResponse = (listCommunityThreadsResponseSuccess | listCommunityThreadsResponseError)

export const getListCommunityThreadsUrl = (params?: ListCommunityThreadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/threads?${stringifiedParams}` : `/api/v1/community/threads`
}

export const listCommunityThreads = async (params?: ListCommunityThreadsParams, options?: RequestInit): Promise<listCommunityThreadsResponse> => {
  
  return customFetch<listCommunityThreadsResponse>(getListCommunityThreadsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a thread with an initial post.
 * @summary Create discussion thread
 */
export type createCommunityThreadResponse200 = {
  data: CreateThreadResponseBody
  status: 200
}

export type createCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createCommunityThreadResponseSuccess = (createCommunityThreadResponse200) & {
  headers: Headers;
};
export type createCommunityThreadResponseError = (createCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type createCommunityThreadResponse = (createCommunityThreadResponseSuccess | createCommunityThreadResponseError)

export const getCreateCommunityThreadUrl = () => {


  

  return `/api/v1/community/threads`
}

export const createCommunityThread = async (createCommunityThreadBody: CreateCommunityThreadBody, options?: RequestInit): Promise<createCommunityThreadResponse> => {
    const formData = new FormData();
if(createCommunityThreadBody.attachmentIds !== undefined) {
 formData.append(`attachmentIds`, createCommunityThreadBody.attachmentIds instanceof Blob ? createCommunityThreadBody.attachmentIds : new Blob([createCommunityThreadBody.attachmentIds], { type: 'text/plain' }));
 }
formData.append(`description`, createCommunityThreadBody.description instanceof Blob ? createCommunityThreadBody.description : new Blob([createCommunityThreadBody.description], { type: 'text/plain' }));
formData.append(`initialPostContent`, createCommunityThreadBody.initialPostContent instanceof Blob ? createCommunityThreadBody.initialPostContent : new Blob([createCommunityThreadBody.initialPostContent], { type: 'text/plain' }));
if(createCommunityThreadBody.parentThreadId !== undefined) {
 formData.append(`parentThreadId`, createCommunityThreadBody.parentThreadId instanceof Blob ? createCommunityThreadBody.parentThreadId : new Blob([createCommunityThreadBody.parentThreadId], { type: 'text/plain' }));
 }
if(createCommunityThreadBody.sectorIds !== undefined) {
 formData.append(`sectorIds`, createCommunityThreadBody.sectorIds instanceof Blob ? createCommunityThreadBody.sectorIds : new Blob([createCommunityThreadBody.sectorIds], { type: 'text/plain' }));
 }
formData.append(`slug`, createCommunityThreadBody.slug instanceof Blob ? createCommunityThreadBody.slug : new Blob([createCommunityThreadBody.slug], { type: 'text/plain' }));
if(createCommunityThreadBody.tagIds !== undefined) {
 formData.append(`tagIds`, createCommunityThreadBody.tagIds instanceof Blob ? createCommunityThreadBody.tagIds : new Blob([createCommunityThreadBody.tagIds], { type: 'text/plain' }));
 }
formData.append(`title`, createCommunityThreadBody.title instanceof Blob ? createCommunityThreadBody.title : new Blob([createCommunityThreadBody.title], { type: 'text/plain' }));

  return customFetch<createCommunityThreadResponse>(getCreateCommunityThreadUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Lists all discussion threads without taxonomy filtering.
 * @summary List all discussion threads
 */
export type listAllCommunityThreadsResponse200 = {
  data: ListThreadsResponseBody
  status: 200
}

export type listAllCommunityThreadsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listAllCommunityThreadsResponseSuccess = (listAllCommunityThreadsResponse200) & {
  headers: Headers;
};
export type listAllCommunityThreadsResponseError = (listAllCommunityThreadsResponseDefault) & {
  headers: Headers;
};

export type listAllCommunityThreadsResponse = (listAllCommunityThreadsResponseSuccess | listAllCommunityThreadsResponseError)

export const getListAllCommunityThreadsUrl = (params?: ListAllCommunityThreadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/threads/all?${stringifiedParams}` : `/api/v1/community/threads/all`
}

export const listAllCommunityThreads = async (params?: ListAllCommunityThreadsParams, options?: RequestInit): Promise<listAllCommunityThreadsResponse> => {
  
  return customFetch<listAllCommunityThreadsResponse>(getListAllCommunityThreadsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Searches threads by keyword, filtered by user's business profile taxonomy.
 * @summary Search discussion threads
 */
export type searchCommunityThreadsResponse200 = {
  data: ListThreadsResponseBody
  status: 200
}

export type searchCommunityThreadsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type searchCommunityThreadsResponseSuccess = (searchCommunityThreadsResponse200) & {
  headers: Headers;
};
export type searchCommunityThreadsResponseError = (searchCommunityThreadsResponseDefault) & {
  headers: Headers;
};

export type searchCommunityThreadsResponse = (searchCommunityThreadsResponseSuccess | searchCommunityThreadsResponseError)

export const getSearchCommunityThreadsUrl = (params?: SearchCommunityThreadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/threads/search?${stringifiedParams}` : `/api/v1/community/threads/search`
}

export const searchCommunityThreads = async (params?: SearchCommunityThreadsParams, options?: RequestInit): Promise<searchCommunityThreadsResponse> => {
  
  return customFetch<searchCommunityThreadsResponse>(getSearchCommunityThreadsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Deletes a thread (author only, no replies beyond the initial post).
 * @summary Delete discussion thread
 */
export type deleteCommunityThreadResponse200 = {
  data: DeleteThreadResponseBody
  status: 200
}

export type deleteCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteCommunityThreadResponseSuccess = (deleteCommunityThreadResponse200) & {
  headers: Headers;
};
export type deleteCommunityThreadResponseError = (deleteCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type deleteCommunityThreadResponse = (deleteCommunityThreadResponseSuccess | deleteCommunityThreadResponseError)

export const getDeleteCommunityThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}`
}

export const deleteCommunityThread = async (id: string, options?: RequestInit): Promise<deleteCommunityThreadResponse> => {
  
  return customFetch<deleteCommunityThreadResponse>(getDeleteCommunityThreadUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Retrieves thread details.
 * @summary Get discussion thread
 */
export type getCommunityThreadResponse200 = {
  data: GetThreadResponseBody
  status: 200
}

export type getCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCommunityThreadResponseSuccess = (getCommunityThreadResponse200) & {
  headers: Headers;
};
export type getCommunityThreadResponseError = (getCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type getCommunityThreadResponse = (getCommunityThreadResponseSuccess | getCommunityThreadResponseError)

export const getGetCommunityThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}`
}

export const getCommunityThread = async (id: string, options?: RequestInit): Promise<getCommunityThreadResponse> => {
  
  return customFetch<getCommunityThreadResponse>(getGetCommunityThreadUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates a thread's metadata (author only, active threads only).
 * @summary Update discussion thread
 */
export type updateCommunityThreadResponse200 = {
  data: UpdateThreadResponseBody
  status: 200
}

export type updateCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateCommunityThreadResponseSuccess = (updateCommunityThreadResponse200) & {
  headers: Headers;
};
export type updateCommunityThreadResponseError = (updateCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type updateCommunityThreadResponse = (updateCommunityThreadResponseSuccess | updateCommunityThreadResponseError)

export const getUpdateCommunityThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}`
}

export const updateCommunityThread = async (id: string,
    updateCommunityThreadBody: UpdateCommunityThreadBody, options?: RequestInit): Promise<updateCommunityThreadResponse> => {
    const formData = new FormData();
if(updateCommunityThreadBody.description !== undefined) {
 formData.append(`description`, updateCommunityThreadBody.description instanceof Blob ? updateCommunityThreadBody.description : new Blob([updateCommunityThreadBody.description], { type: 'text/plain' }));
 }
if(updateCommunityThreadBody.isPinned !== undefined) {
 formData.append(`isPinned`, updateCommunityThreadBody.isPinned instanceof Blob ? updateCommunityThreadBody.isPinned : new Blob([updateCommunityThreadBody.isPinned], { type: 'text/plain' }));
 }
if(updateCommunityThreadBody.sectorIds !== undefined) {
 formData.append(`sectorIds`, updateCommunityThreadBody.sectorIds instanceof Blob ? updateCommunityThreadBody.sectorIds : new Blob([updateCommunityThreadBody.sectorIds], { type: 'text/plain' }));
 }
if(updateCommunityThreadBody.status !== undefined) {
 formData.append(`status`, updateCommunityThreadBody.status instanceof Blob ? updateCommunityThreadBody.status : new Blob([updateCommunityThreadBody.status], { type: 'text/plain' }));
 }
if(updateCommunityThreadBody.tagIds !== undefined) {
 formData.append(`tagIds`, updateCommunityThreadBody.tagIds instanceof Blob ? updateCommunityThreadBody.tagIds : new Blob([updateCommunityThreadBody.tagIds], { type: 'text/plain' }));
 }
if(updateCommunityThreadBody.title !== undefined) {
 formData.append(`title`, updateCommunityThreadBody.title instanceof Blob ? updateCommunityThreadBody.title : new Blob([updateCommunityThreadBody.title], { type: 'text/plain' }));
 }

  return customFetch<updateCommunityThreadResponse>(getUpdateCommunityThreadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Blocks a user from a thread (thread author only).
 * @summary Block user in thread
 */
export type blockCommunityUserResponse200 = {
  data: BlockUserResponseBody
  status: 200
}

export type blockCommunityUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type blockCommunityUserResponseSuccess = (blockCommunityUserResponse200) & {
  headers: Headers;
};
export type blockCommunityUserResponseError = (blockCommunityUserResponseDefault) & {
  headers: Headers;
};

export type blockCommunityUserResponse = (blockCommunityUserResponseSuccess | blockCommunityUserResponseError)

export const getBlockCommunityUserUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/blocks`
}

export const blockCommunityUser = async (id: string,
    blockUserRequest: NonReadonly<BlockUserRequest>, options?: RequestInit): Promise<blockCommunityUserResponse> => {
  
  return customFetch<blockCommunityUserResponse>(getBlockCommunityUserUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      blockUserRequest,)
  }
);}
  

/**
 * Unblocks a user from a thread (thread author only).
 * @summary Unblock user in thread
 */
export type unblockCommunityUserResponse200 = {
  data: BlockUserResponseBody
  status: 200
}

export type unblockCommunityUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type unblockCommunityUserResponseSuccess = (unblockCommunityUserResponse200) & {
  headers: Headers;
};
export type unblockCommunityUserResponseError = (unblockCommunityUserResponseDefault) & {
  headers: Headers;
};

export type unblockCommunityUserResponse = (unblockCommunityUserResponseSuccess | unblockCommunityUserResponseError)

export const getUnblockCommunityUserUrl = (id: string,
    accountId: string,) => {


  

  return `/api/v1/community/threads/${id}/blocks/${accountId}`
}

export const unblockCommunityUser = async (id: string,
    accountId: string, options?: RequestInit): Promise<unblockCommunityUserResponse> => {
  
  return customFetch<unblockCommunityUserResponse>(getUnblockCommunityUserUrl(id,accountId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Unfollows a discussion thread.
 * @summary Unfollow thread
 */
export type unfollowCommunityThreadResponse200 = {
  data: FollowResponseBody
  status: 200
}

export type unfollowCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type unfollowCommunityThreadResponseSuccess = (unfollowCommunityThreadResponse200) & {
  headers: Headers;
};
export type unfollowCommunityThreadResponseError = (unfollowCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type unfollowCommunityThreadResponse = (unfollowCommunityThreadResponseSuccess | unfollowCommunityThreadResponseError)

export const getUnfollowCommunityThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/follow`
}

export const unfollowCommunityThread = async (id: string, options?: RequestInit): Promise<unfollowCommunityThreadResponse> => {
  
  return customFetch<unfollowCommunityThreadResponse>(getUnfollowCommunityThreadUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Follows a discussion thread.
 * @summary Follow thread
 */
export type followCommunityThreadResponse200 = {
  data: FollowResponseBody
  status: 200
}

export type followCommunityThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type followCommunityThreadResponseSuccess = (followCommunityThreadResponse200) & {
  headers: Headers;
};
export type followCommunityThreadResponseError = (followCommunityThreadResponseDefault) & {
  headers: Headers;
};

export type followCommunityThreadResponse = (followCommunityThreadResponseSuccess | followCommunityThreadResponseError)

export const getFollowCommunityThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/follow`
}

export const followCommunityThread = async (id: string, options?: RequestInit): Promise<followCommunityThreadResponse> => {
  
  return customFetch<followCommunityThreadResponse>(getFollowCommunityThreadUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Lists posts in a thread.
 * @summary List thread posts
 */
export type listCommunityPostsResponse200 = {
  data: ListPostsResponseBody
  status: 200
}

export type listCommunityPostsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listCommunityPostsResponseSuccess = (listCommunityPostsResponse200) & {
  headers: Headers;
};
export type listCommunityPostsResponseError = (listCommunityPostsResponseDefault) & {
  headers: Headers;
};

export type listCommunityPostsResponse = (listCommunityPostsResponseSuccess | listCommunityPostsResponseError)

export const getListCommunityPostsUrl = (id: string,
    params?: ListCommunityPostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/community/threads/${id}/posts?${stringifiedParams}` : `/api/v1/community/threads/${id}/posts`
}

export const listCommunityPosts = async (id: string,
    params?: ListCommunityPostsParams, options?: RequestInit): Promise<listCommunityPostsResponse> => {
  
  return customFetch<listCommunityPostsResponse>(getListCommunityPostsUrl(id,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a top-level post in a thread.
 * @summary Create thread post
 */
export type createCommunityPostResponse200 = {
  data: CreatePostResponseBody
  status: 200
}

export type createCommunityPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createCommunityPostResponseSuccess = (createCommunityPostResponse200) & {
  headers: Headers;
};
export type createCommunityPostResponseError = (createCommunityPostResponseDefault) & {
  headers: Headers;
};

export type createCommunityPostResponse = (createCommunityPostResponseSuccess | createCommunityPostResponseError)

export const getCreateCommunityPostUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/posts`
}

export const createCommunityPost = async (id: string,
    createCommunityPostBody: CreateCommunityPostBody, options?: RequestInit): Promise<createCommunityPostResponse> => {
    const formData = new FormData();
if(createCommunityPostBody.attachmentIds !== undefined) {
 formData.append(`attachmentIds`, createCommunityPostBody.attachmentIds instanceof Blob ? createCommunityPostBody.attachmentIds : new Blob([createCommunityPostBody.attachmentIds], { type: 'text/plain' }));
 }
formData.append(`content`, createCommunityPostBody.content instanceof Blob ? createCommunityPostBody.content : new Blob([createCommunityPostBody.content], { type: 'text/plain' }));

  return customFetch<createCommunityPostResponse>(getCreateCommunityPostUrl(id),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Replies to a post in a thread.
 * @summary Reply to post
 */
export type replyCommunityPostResponse200 = {
  data: CreatePostResponseBody
  status: 200
}

export type replyCommunityPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type replyCommunityPostResponseSuccess = (replyCommunityPostResponse200) & {
  headers: Headers;
};
export type replyCommunityPostResponseError = (replyCommunityPostResponseDefault) & {
  headers: Headers;
};

export type replyCommunityPostResponse = (replyCommunityPostResponseSuccess | replyCommunityPostResponseError)

export const getReplyCommunityPostUrl = (id: string,
    postId: string,) => {


  

  return `/api/v1/community/threads/${id}/posts/${postId}/reply`
}

export const replyCommunityPost = async (id: string,
    postId: string,
    replyCommunityPostBody: ReplyCommunityPostBody, options?: RequestInit): Promise<replyCommunityPostResponse> => {
    const formData = new FormData();
if(replyCommunityPostBody.attachmentIds !== undefined) {
 formData.append(`attachmentIds`, replyCommunityPostBody.attachmentIds instanceof Blob ? replyCommunityPostBody.attachmentIds : new Blob([replyCommunityPostBody.attachmentIds], { type: 'text/plain' }));
 }
formData.append(`content`, replyCommunityPostBody.content instanceof Blob ? replyCommunityPostBody.content : new Blob([replyCommunityPostBody.content], { type: 'text/plain' }));

  return customFetch<replyCommunityPostResponse>(getReplyCommunityPostUrl(id,postId),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Reports a discussion post.
 * @summary Report post
 */
export type reportPostResponse200 = {
  data: ReportPostResponseBody
  status: 200
}

export type reportPostResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type reportPostResponseSuccess = (reportPostResponse200) & {
  headers: Headers;
};
export type reportPostResponseError = (reportPostResponseDefault) & {
  headers: Headers;
};

export type reportPostResponse = (reportPostResponseSuccess | reportPostResponseError)

export const getReportPostUrl = (id: string,
    postId: string,) => {


  

  return `/api/v1/community/threads/${id}/posts/${postId}/reports`
}

export const reportPost = async (id: string,
    postId: string,
    reportPostRequest: NonReadonly<ReportPostRequest>, options?: RequestInit): Promise<reportPostResponse> => {
  
  return customFetch<reportPostResponse>(getReportPostUrl(id,postId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportPostRequest,)
  }
);}
  

/**
 * Reports a discussion thread.
 * @summary Report thread
 */
export type reportThreadResponse200 = {
  data: ReportThreadResponseBody
  status: 200
}

export type reportThreadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type reportThreadResponseSuccess = (reportThreadResponse200) & {
  headers: Headers;
};
export type reportThreadResponseError = (reportThreadResponseDefault) & {
  headers: Headers;
};

export type reportThreadResponse = (reportThreadResponseSuccess | reportThreadResponseError)

export const getReportThreadUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/reports`
}

export const reportThread = async (id: string,
    reportThreadRequest: NonReadonly<ReportThreadRequest>, options?: RequestInit): Promise<reportThreadResponse> => {
  
  return customFetch<reportThreadResponse>(getReportThreadUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportThreadRequest,)
  }
);}
  

/**
 * Reports a user in a thread.
 * @summary Report user
 */
export type reportUserResponse200 = {
  data: ReportUserResponseBody
  status: 200
}

export type reportUserResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type reportUserResponseSuccess = (reportUserResponse200) & {
  headers: Headers;
};
export type reportUserResponseError = (reportUserResponseDefault) & {
  headers: Headers;
};

export type reportUserResponse = (reportUserResponseSuccess | reportUserResponseError)

export const getReportUserUrl = (id: string,) => {


  

  return `/api/v1/community/threads/${id}/reports/user`
}

export const reportUser = async (id: string,
    reportUserRequest: NonReadonly<ReportUserRequest>, options?: RequestInit): Promise<reportUserResponse> => {
  
  return customFetch<reportUserResponse>(getReportUserUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reportUserRequest,)
  }
);}
  

/**
 * Marks a post as the accepted solution.
 * @summary Mark accepted solution
 */
export type markCommunitySolutionResponse200 = {
  data: MarkSolutionResponseBody
  status: 200
}

export type markCommunitySolutionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type markCommunitySolutionResponseSuccess = (markCommunitySolutionResponse200) & {
  headers: Headers;
};
export type markCommunitySolutionResponseError = (markCommunitySolutionResponseDefault) & {
  headers: Headers;
};

export type markCommunitySolutionResponse = (markCommunitySolutionResponseSuccess | markCommunitySolutionResponseError)

export const getMarkCommunitySolutionUrl = (id: string,
    postId: string,) => {


  

  return `/api/v1/community/threads/${id}/solution/${postId}`
}

export const markCommunitySolution = async (id: string,
    postId: string, options?: RequestInit): Promise<markCommunitySolutionResponse> => {
  
  return customFetch<markCommunitySolutionResponse>(getMarkCommunitySolutionUrl(id,postId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

