/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  AddBookmarkResponseBody,
  CompleteStepRequest,
  CompleteStepResponseBody,
  CompletionStatsDTO,
  ErrorModel,
  GetCurrentStepParams,
  GetCurrentStepResponseBody,
  GetInProgressGuidesParams,
  GetInProgressGuidesResponseBody,
  GetPersonalizedGuideParams,
  GetPersonalizedGuideResponseBody,
  GetRecentlyViewedParams,
  GetRecentlyViewedResponseBody,
  ListBookmarksParams,
  ListBookmarksResponseBody,
  ListGuidesParams,
  ListGuidesResponseBody,
  MarkStepIncompleteResponseBody,
  RemoveBookmarkResponseBody,
  SearchGuidesParams,
  SearchGuidesResponseBody,
  SkipOptionalStepResponseBody,
  StartStepResponseBody,
  UpdateBookmarkNoteRequest,
  UpdateBookmarkNoteResponseBody,
  UpdateProgressRequest,
  UpdateProgressResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists guides filtered by the user's business profile taxonomy (sector, tags, region, stage).
 * @summary List guides
 */
export type listGuidesResponse200 = {
  data: ListGuidesResponseBody
  status: 200
}

export type listGuidesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listGuidesResponseSuccess = (listGuidesResponse200) & {
  headers: Headers;
};
export type listGuidesResponseError = (listGuidesResponseDefault) & {
  headers: Headers;
};

export type listGuidesResponse = (listGuidesResponseSuccess | listGuidesResponseError)

export const getListGuidesUrl = (params?: ListGuidesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides?${stringifiedParams}` : `/api/v1/guides`
}

export const listGuides = async (params?: ListGuidesParams, options?: RequestInit): Promise<listGuidesResponse> => {
  
  return customFetch<listGuidesResponse>(getListGuidesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists all bookmarks for the user.
 * @summary List bookmarks
 */
export type listBookmarksResponse200 = {
  data: ListBookmarksResponseBody
  status: 200
}

export type listBookmarksResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listBookmarksResponseSuccess = (listBookmarksResponse200) & {
  headers: Headers;
};
export type listBookmarksResponseError = (listBookmarksResponseDefault) & {
  headers: Headers;
};

export type listBookmarksResponse = (listBookmarksResponseSuccess | listBookmarksResponseError)

export const getListBookmarksUrl = (params?: ListBookmarksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/bookmarks?${stringifiedParams}` : `/api/v1/guides/bookmarks`
}

export const listBookmarks = async (params?: ListBookmarksParams, options?: RequestInit): Promise<listBookmarksResponse> => {
  
  return customFetch<listBookmarksResponse>(getListBookmarksUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Returns aggregate completion statistics for dashboard.
 * @summary Get completion statistics
 */
export type getCompletionStatsResponse200 = {
  data: CompletionStatsDTO
  status: 200
}

export type getCompletionStatsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCompletionStatsResponseSuccess = (getCompletionStatsResponse200) & {
  headers: Headers;
};
export type getCompletionStatsResponseError = (getCompletionStatsResponseDefault) & {
  headers: Headers;
};

export type getCompletionStatsResponse = (getCompletionStatsResponseSuccess | getCompletionStatsResponseError)

export const getGetCompletionStatsUrl = () => {


  

  return `/api/v1/guides/completion-stats`
}

export const getCompletionStats = async ( options?: RequestInit): Promise<getCompletionStatsResponse> => {
  
  return customFetch<getCompletionStatsResponse>(getGetCompletionStatsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Retrieves guides the user has started but not completed, with progress data.
 * @summary Get in-progress guides
 */
export type getInProgressGuidesResponse200 = {
  data: GetInProgressGuidesResponseBody
  status: 200
}

export type getInProgressGuidesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getInProgressGuidesResponseSuccess = (getInProgressGuidesResponse200) & {
  headers: Headers;
};
export type getInProgressGuidesResponseError = (getInProgressGuidesResponseDefault) & {
  headers: Headers;
};

export type getInProgressGuidesResponse = (getInProgressGuidesResponseSuccess | getInProgressGuidesResponseError)

export const getGetInProgressGuidesUrl = (params?: GetInProgressGuidesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/in-progress?${stringifiedParams}` : `/api/v1/guides/in-progress`
}

export const getInProgressGuides = async (params?: GetInProgressGuidesParams, options?: RequestInit): Promise<getInProgressGuidesResponse> => {
  
  return customFetch<getInProgressGuidesResponse>(getGetInProgressGuidesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Retrieves the user's recently viewed guides with localized names.
 * @summary Get recently viewed guides
 */
export type getRecentlyViewedResponse200 = {
  data: GetRecentlyViewedResponseBody
  status: 200
}

export type getRecentlyViewedResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getRecentlyViewedResponseSuccess = (getRecentlyViewedResponse200) & {
  headers: Headers;
};
export type getRecentlyViewedResponseError = (getRecentlyViewedResponseDefault) & {
  headers: Headers;
};

export type getRecentlyViewedResponse = (getRecentlyViewedResponseSuccess | getRecentlyViewedResponseError)

export const getGetRecentlyViewedUrl = (params?: GetRecentlyViewedParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/recent?${stringifiedParams}` : `/api/v1/guides/recent`
}

export const getRecentlyViewed = async (params?: GetRecentlyViewedParams, options?: RequestInit): Promise<getRecentlyViewedResponse> => {
  
  return customFetch<getRecentlyViewedResponse>(getGetRecentlyViewedUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Searches guides by keyword with localized results.
 * @summary Search guides
 */
export type searchGuidesResponse200 = {
  data: SearchGuidesResponseBody
  status: 200
}

export type searchGuidesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type searchGuidesResponseSuccess = (searchGuidesResponse200) & {
  headers: Headers;
};
export type searchGuidesResponseError = (searchGuidesResponseDefault) & {
  headers: Headers;
};

export type searchGuidesResponse = (searchGuidesResponseSuccess | searchGuidesResponseError)

export const getSearchGuidesUrl = (params?: SearchGuidesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/search?${stringifiedParams}` : `/api/v1/guides/search`
}

export const searchGuides = async (params?: SearchGuidesParams, options?: RequestInit): Promise<searchGuidesResponse> => {
  
  return customFetch<searchGuidesResponse>(getSearchGuidesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Removes a bookmark from a step.
 * @summary Remove bookmark
 */
export type removeBookmarkResponse200 = {
  data: RemoveBookmarkResponseBody
  status: 200
}

export type removeBookmarkResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type removeBookmarkResponseSuccess = (removeBookmarkResponse200) & {
  headers: Headers;
};
export type removeBookmarkResponseError = (removeBookmarkResponseDefault) & {
  headers: Headers;
};

export type removeBookmarkResponse = (removeBookmarkResponseSuccess | removeBookmarkResponseError)

export const getRemoveBookmarkUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/bookmark`
}

export const removeBookmark = async (stepId: string, options?: RequestInit): Promise<removeBookmarkResponse> => {
  
  return customFetch<removeBookmarkResponse>(getRemoveBookmarkUrl(stepId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates the note on an existing bookmark.
 * @summary Update bookmark note
 */
export type updateBookmarkNoteResponse200 = {
  data: UpdateBookmarkNoteResponseBody
  status: 200
}

export type updateBookmarkNoteResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateBookmarkNoteResponseSuccess = (updateBookmarkNoteResponse200) & {
  headers: Headers;
};
export type updateBookmarkNoteResponseError = (updateBookmarkNoteResponseDefault) & {
  headers: Headers;
};

export type updateBookmarkNoteResponse = (updateBookmarkNoteResponseSuccess | updateBookmarkNoteResponseError)

export const getUpdateBookmarkNoteUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/bookmark`
}

export const updateBookmarkNote = async (stepId: string,
    updateBookmarkNoteRequest: NonReadonly<UpdateBookmarkNoteRequest>, options?: RequestInit): Promise<updateBookmarkNoteResponse> => {
  
  return customFetch<updateBookmarkNoteResponse>(getUpdateBookmarkNoteUrl(stepId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBookmarkNoteRequest,)
  }
);}
  

/**
 * Bookmarks a step with an optional note.
 * @summary Add bookmark
 */
export type addBookmarkResponse200 = {
  data: AddBookmarkResponseBody
  status: 200
}

export type addBookmarkResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type addBookmarkResponseSuccess = (addBookmarkResponse200) & {
  headers: Headers;
};
export type addBookmarkResponseError = (addBookmarkResponseDefault) & {
  headers: Headers;
};

export type addBookmarkResponse = (addBookmarkResponseSuccess | addBookmarkResponseError)

export const getAddBookmarkUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/bookmark`
}

export const addBookmark = async (stepId: string, options?: RequestInit): Promise<addBookmarkResponse> => {
  
  return customFetch<addBookmarkResponse>(getAddBookmarkUrl(stepId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Marks a step as completed with optional documents and notes.
 * @summary Complete a step
 */
export type completeStepResponse200 = {
  data: CompleteStepResponseBody
  status: 200
}

export type completeStepResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type completeStepResponseSuccess = (completeStepResponse200) & {
  headers: Headers;
};
export type completeStepResponseError = (completeStepResponseDefault) & {
  headers: Headers;
};

export type completeStepResponse = (completeStepResponseSuccess | completeStepResponseError)

export const getCompleteStepUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/complete`
}

export const completeStep = async (stepId: string,
    completeStepRequest: NonReadonly<CompleteStepRequest>, options?: RequestInit): Promise<completeStepResponse> => {
  
  return customFetch<completeStepResponse>(getCompleteStepUrl(stepId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      completeStepRequest,)
  }
);}
  

/**
 * Resets a step's status to in-progress.
 * @summary Mark step as incomplete
 */
export type markStepIncompleteResponse200 = {
  data: MarkStepIncompleteResponseBody
  status: 200
}

export type markStepIncompleteResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type markStepIncompleteResponseSuccess = (markStepIncompleteResponse200) & {
  headers: Headers;
};
export type markStepIncompleteResponseError = (markStepIncompleteResponseDefault) & {
  headers: Headers;
};

export type markStepIncompleteResponse = (markStepIncompleteResponseSuccess | markStepIncompleteResponseError)

export const getMarkStepIncompleteUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/mark-incomplete`
}

export const markStepIncomplete = async (stepId: string, options?: RequestInit): Promise<markStepIncompleteResponse> => {
  
  return customFetch<markStepIncompleteResponse>(getMarkStepIncompleteUrl(stepId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Updates progress details for a step including documents and notes.
 * @summary Update step progress
 */
export type updateProgressResponse200 = {
  data: UpdateProgressResponseBody
  status: 200
}

export type updateProgressResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateProgressResponseSuccess = (updateProgressResponse200) & {
  headers: Headers;
};
export type updateProgressResponseError = (updateProgressResponseDefault) & {
  headers: Headers;
};

export type updateProgressResponse = (updateProgressResponseSuccess | updateProgressResponseError)

export const getUpdateProgressUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/progress`
}

export const updateProgress = async (stepId: string,
    updateProgressRequest: NonReadonly<UpdateProgressRequest>, options?: RequestInit): Promise<updateProgressResponse> => {
  
  return customFetch<updateProgressResponse>(getUpdateProgressUrl(stepId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProgressRequest,)
  }
);}
  

/**
 * Skips an optional step with an optional reason.
 * @summary Skip an optional step
 */
export type skipOptionalStepResponse200 = {
  data: SkipOptionalStepResponseBody
  status: 200
}

export type skipOptionalStepResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type skipOptionalStepResponseSuccess = (skipOptionalStepResponse200) & {
  headers: Headers;
};
export type skipOptionalStepResponseError = (skipOptionalStepResponseDefault) & {
  headers: Headers;
};

export type skipOptionalStepResponse = (skipOptionalStepResponseSuccess | skipOptionalStepResponseError)

export const getSkipOptionalStepUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/skip`
}

export const skipOptionalStep = async (stepId: string, options?: RequestInit): Promise<skipOptionalStepResponse> => {
  
  return customFetch<skipOptionalStepResponse>(getSkipOptionalStepUrl(stepId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Marks a step as in-progress for the user.
 * @summary Start a step
 */
export type startStepResponse200 = {
  data: StartStepResponseBody
  status: 200
}

export type startStepResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type startStepResponseSuccess = (startStepResponse200) & {
  headers: Headers;
};
export type startStepResponseError = (startStepResponseDefault) & {
  headers: Headers;
};

export type startStepResponse = (startStepResponseSuccess | startStepResponseError)

export const getStartStepUrl = (stepId: string,) => {


  

  return `/api/v1/guides/steps/${stepId}/start`
}

export const startStep = async (stepId: string, options?: RequestInit): Promise<startStepResponse> => {
  
  return customFetch<startStepResponse>(getStartStepUrl(stepId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Retrieves a guide with personalized step statuses based on user progress.
 * @summary Get personalized guide
 */
export type getPersonalizedGuideResponse200 = {
  data: GetPersonalizedGuideResponseBody
  status: 200
}

export type getPersonalizedGuideResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getPersonalizedGuideResponseSuccess = (getPersonalizedGuideResponse200) & {
  headers: Headers;
};
export type getPersonalizedGuideResponseError = (getPersonalizedGuideResponseDefault) & {
  headers: Headers;
};

export type getPersonalizedGuideResponse = (getPersonalizedGuideResponseSuccess | getPersonalizedGuideResponseError)

export const getGetPersonalizedGuideUrl = (guideSlug: string,
    params?: GetPersonalizedGuideParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/${guideSlug}?${stringifiedParams}` : `/api/v1/guides/${guideSlug}`
}

export const getPersonalizedGuide = async (guideSlug: string,
    params?: GetPersonalizedGuideParams, options?: RequestInit): Promise<getPersonalizedGuideResponse> => {
  
  return customFetch<getPersonalizedGuideResponse>(getGetPersonalizedGuideUrl(guideSlug,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Returns the next incomplete step in a guide for the user.
 * @summary Get current step
 */
export type getCurrentStepResponse200 = {
  data: GetCurrentStepResponseBody
  status: 200
}

export type getCurrentStepResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getCurrentStepResponseSuccess = (getCurrentStepResponse200) & {
  headers: Headers;
};
export type getCurrentStepResponseError = (getCurrentStepResponseDefault) & {
  headers: Headers;
};

export type getCurrentStepResponse = (getCurrentStepResponseSuccess | getCurrentStepResponseError)

export const getGetCurrentStepUrl = (guideSlug: string,
    params?: GetCurrentStepParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/guides/${guideSlug}/current-step?${stringifiedParams}` : `/api/v1/guides/${guideSlug}/current-step`
}

export const getCurrentStep = async (guideSlug: string,
    params?: GetCurrentStepParams, options?: RequestInit): Promise<getCurrentStepResponse> => {
  
  return customFetch<getCurrentStepResponse>(getGetCurrentStepUrl(guideSlug,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

