/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  CategoryNodeResponse,
  DownloadTemplateResponseBody,
  ErrorModel,
  LibraryDownloadTemplateParams,
  LibraryGetTemplateGroupParams,
  LibraryListCategoriesParams,
  LibraryListMyDownloadsParams,
  LibraryListTemplateGroupsParams,
  ListMyDownloadsResponseBody,
  ListTemplateGroupsResponseBody,
  UserTemplateGroupDetailResponse
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists active categories as a tree, optionally localized.
 * @summary List categories
 */
export type libraryListCategoriesResponse200 = {
  data: CategoryNodeResponse[] | null
  status: 200
}

export type libraryListCategoriesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListCategoriesResponseSuccess = (libraryListCategoriesResponse200) & {
  headers: Headers;
};
export type libraryListCategoriesResponseError = (libraryListCategoriesResponseDefault) & {
  headers: Headers;
};

export type libraryListCategoriesResponse = (libraryListCategoriesResponseSuccess | libraryListCategoriesResponseError)

export const getLibraryListCategoriesUrl = (params?: LibraryListCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library/categories?${stringifiedParams}` : `/api/v1/library/categories`
}

export const libraryListCategories = async (params?: LibraryListCategoriesParams, options?: RequestInit): Promise<libraryListCategoriesResponse> => {
  
  return customFetch<libraryListCategoriesResponse>(getLibraryListCategoriesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists the authenticated user's download history.
 * @summary My downloads
 */
export type libraryListMyDownloadsResponse200 = {
  data: ListMyDownloadsResponseBody
  status: 200
}

export type libraryListMyDownloadsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListMyDownloadsResponseSuccess = (libraryListMyDownloadsResponse200) & {
  headers: Headers;
};
export type libraryListMyDownloadsResponseError = (libraryListMyDownloadsResponseDefault) & {
  headers: Headers;
};

export type libraryListMyDownloadsResponse = (libraryListMyDownloadsResponseSuccess | libraryListMyDownloadsResponseError)

export const getLibraryListMyDownloadsUrl = (params?: LibraryListMyDownloadsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library/downloads?${stringifiedParams}` : `/api/v1/library/downloads`
}

export const libraryListMyDownloads = async (params?: LibraryListMyDownloadsParams, options?: RequestInit): Promise<libraryListMyDownloadsResponse> => {
  
  return customFetch<libraryListMyDownloadsResponse>(getLibraryListMyDownloadsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists active template groups with optional filters.
 * @summary List template groups
 */
export type libraryListTemplateGroupsResponse200 = {
  data: ListTemplateGroupsResponseBody
  status: 200
}

export type libraryListTemplateGroupsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryListTemplateGroupsResponseSuccess = (libraryListTemplateGroupsResponse200) & {
  headers: Headers;
};
export type libraryListTemplateGroupsResponseError = (libraryListTemplateGroupsResponseDefault) & {
  headers: Headers;
};

export type libraryListTemplateGroupsResponse = (libraryListTemplateGroupsResponseSuccess | libraryListTemplateGroupsResponseError)

export const getLibraryListTemplateGroupsUrl = (params?: LibraryListTemplateGroupsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library/templates?${stringifiedParams}` : `/api/v1/library/templates`
}

export const libraryListTemplateGroups = async (params?: LibraryListTemplateGroupsParams, options?: RequestInit): Promise<libraryListTemplateGroupsResponse> => {
  
  return customFetch<libraryListTemplateGroupsResponse>(getLibraryListTemplateGroupsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Gets a template group with its language variants.
 * @summary Get template group
 */
export type libraryGetTemplateGroupResponse200 = {
  data: UserTemplateGroupDetailResponse
  status: 200
}

export type libraryGetTemplateGroupResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryGetTemplateGroupResponseSuccess = (libraryGetTemplateGroupResponse200) & {
  headers: Headers;
};
export type libraryGetTemplateGroupResponseError = (libraryGetTemplateGroupResponseDefault) & {
  headers: Headers;
};

export type libraryGetTemplateGroupResponse = (libraryGetTemplateGroupResponseSuccess | libraryGetTemplateGroupResponseError)

export const getLibraryGetTemplateGroupUrl = (groupId: string,
    params?: LibraryGetTemplateGroupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library/templates/${groupId}?${stringifiedParams}` : `/api/v1/library/templates/${groupId}`
}

export const libraryGetTemplateGroup = async (groupId: string,
    params?: LibraryGetTemplateGroupParams, options?: RequestInit): Promise<libraryGetTemplateGroupResponse> => {
  
  return customFetch<libraryGetTemplateGroupResponse>(getLibraryGetTemplateGroupUrl(groupId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Generates a presigned download URL for a template.
 * @summary Download template
 */
export type libraryDownloadTemplateResponse200 = {
  data: DownloadTemplateResponseBody
  status: 200
}

export type libraryDownloadTemplateResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type libraryDownloadTemplateResponseSuccess = (libraryDownloadTemplateResponse200) & {
  headers: Headers;
};
export type libraryDownloadTemplateResponseError = (libraryDownloadTemplateResponseDefault) & {
  headers: Headers;
};

export type libraryDownloadTemplateResponse = (libraryDownloadTemplateResponseSuccess | libraryDownloadTemplateResponseError)

export const getLibraryDownloadTemplateUrl = (groupId: string,
    params?: LibraryDownloadTemplateParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/library/templates/${groupId}/download?${stringifiedParams}` : `/api/v1/library/templates/${groupId}/download`
}

export const libraryDownloadTemplate = async (groupId: string,
    params?: LibraryDownloadTemplateParams, options?: RequestInit): Promise<libraryDownloadTemplateResponse> => {
  
  return customFetch<libraryDownloadTemplateResponse>(getLibraryDownloadTemplateUrl(groupId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

