/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ArchiveNotificationResponseBody,
  CancelScheduledAlertResponseBody,
  CreateScheduledAlertRequest,
  CreateScheduledAlertResponseBody,
  DeactivateDeviceResponseBody,
  DeleteNotificationResponseBody,
  DeletePreferenceResponseBody,
  DeviceResponse,
  ErrorModel,
  HistoryEntryResponse,
  ListHistoryParams,
  ListHistoryResponseBody,
  ListInboxParams,
  ListInboxResponseBody,
  ListMutesParams,
  ListMutesResponseBody,
  ListScheduledAlertsResponseBody,
  ListScheduledTemplatesResponseBody,
  MarkAllAsReadResponseBody,
  MarkAsReadResponseBody,
  MuteAccountRequest,
  MuteAccountResponseBody,
  PreferenceResponse,
  RegisterDeviceRequest,
  RegisterDeviceResponseBody,
  RescheduleScheduledAlertRequest,
  RescheduleScheduledAlertResponseBody,
  SetPreferenceRequest,
  SetPreferenceResponseBody,
  UnmuteAccountResponseBody,
  UnreadCountResponseBody,
  UpdateDeviceRequest
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists all registered devices for the authenticated user.
 * @summary List devices
 */
export type listDevicesResponse200 = {
  data: DeviceResponse[] | null
  status: 200
}

export type listDevicesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listDevicesResponseSuccess = (listDevicesResponse200) & {
  headers: Headers;
};
export type listDevicesResponseError = (listDevicesResponseDefault) & {
  headers: Headers;
};

export type listDevicesResponse = (listDevicesResponseSuccess | listDevicesResponseError)

export const getListDevicesUrl = () => {


  

  return `/api/v1/notifications/devices`
}

export const listDevices = async ( options?: RequestInit): Promise<listDevicesResponse> => {
  
  return customFetch<listDevicesResponse>(getListDevicesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Registers a new device or updates an existing one by device token.
 * @summary Register device
 */
export type registerDeviceResponse200 = {
  data: RegisterDeviceResponseBody
  status: 200
}

export type registerDeviceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type registerDeviceResponseSuccess = (registerDeviceResponse200) & {
  headers: Headers;
};
export type registerDeviceResponseError = (registerDeviceResponseDefault) & {
  headers: Headers;
};

export type registerDeviceResponse = (registerDeviceResponseSuccess | registerDeviceResponseError)

export const getRegisterDeviceUrl = () => {


  

  return `/api/v1/notifications/devices`
}

export const registerDevice = async (registerDeviceRequest: NonReadonly<RegisterDeviceRequest>, options?: RequestInit): Promise<registerDeviceResponse> => {
  
  return customFetch<registerDeviceResponse>(getRegisterDeviceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDeviceRequest,)
  }
);}
  

/**
 * Deactivates a registered device.
 * @summary Deactivate device
 */
export type deactivateDeviceResponse200 = {
  data: DeactivateDeviceResponseBody
  status: 200
}

export type deactivateDeviceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deactivateDeviceResponseSuccess = (deactivateDeviceResponse200) & {
  headers: Headers;
};
export type deactivateDeviceResponseError = (deactivateDeviceResponseDefault) & {
  headers: Headers;
};

export type deactivateDeviceResponse = (deactivateDeviceResponseSuccess | deactivateDeviceResponseError)

export const getDeactivateDeviceUrl = (id: string,) => {


  

  return `/api/v1/notifications/devices/${id}`
}

export const deactivateDevice = async (id: string, options?: RequestInit): Promise<deactivateDeviceResponse> => {
  
  return customFetch<deactivateDeviceResponse>(getDeactivateDeviceUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Updates device metadata such as push token or device name.
 * @summary Update device
 */
export type updateDeviceResponse200 = {
  data: DeviceResponse
  status: 200
}

export type updateDeviceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateDeviceResponseSuccess = (updateDeviceResponse200) & {
  headers: Headers;
};
export type updateDeviceResponseError = (updateDeviceResponseDefault) & {
  headers: Headers;
};

export type updateDeviceResponse = (updateDeviceResponseSuccess | updateDeviceResponseError)

export const getUpdateDeviceUrl = (id: string,) => {


  

  return `/api/v1/notifications/devices/${id}`
}

export const updateDevice = async (id: string,
    updateDeviceRequest: NonReadonly<UpdateDeviceRequest>, options?: RequestInit): Promise<updateDeviceResponse> => {
  
  return customFetch<updateDeviceResponse>(getUpdateDeviceUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateDeviceRequest,)
  }
);}
  

/**
 * Lists the authenticated user's notification history.
 * @summary List history
 */
export type listHistoryResponse200 = {
  data: ListHistoryResponseBody
  status: 200
}

export type listHistoryResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listHistoryResponseSuccess = (listHistoryResponse200) & {
  headers: Headers;
};
export type listHistoryResponseError = (listHistoryResponseDefault) & {
  headers: Headers;
};

export type listHistoryResponse = (listHistoryResponseSuccess | listHistoryResponseError)

export const getListHistoryUrl = (params?: ListHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/notifications/history?${stringifiedParams}` : `/api/v1/notifications/history`
}

export const listHistory = async (params?: ListHistoryParams, options?: RequestInit): Promise<listHistoryResponse> => {
  
  return customFetch<listHistoryResponse>(getListHistoryUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Gets a single notification history entry.
 * @summary Get history detail
 */
export type getHistoryDetailResponse200 = {
  data: HistoryEntryResponse
  status: 200
}

export type getHistoryDetailResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getHistoryDetailResponseSuccess = (getHistoryDetailResponse200) & {
  headers: Headers;
};
export type getHistoryDetailResponseError = (getHistoryDetailResponseDefault) & {
  headers: Headers;
};

export type getHistoryDetailResponse = (getHistoryDetailResponseSuccess | getHistoryDetailResponseError)

export const getGetHistoryDetailUrl = (id: string,) => {


  

  return `/api/v1/notifications/history/${id}`
}

export const getHistoryDetail = async (id: string, options?: RequestInit): Promise<getHistoryDetailResponse> => {
  
  return customFetch<getHistoryDetailResponse>(getGetHistoryDetailUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists the authenticated user's inbox with optional category filter.
 * @summary List inbox
 */
export type listInboxResponse200 = {
  data: ListInboxResponseBody
  status: 200
}

export type listInboxResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listInboxResponseSuccess = (listInboxResponse200) & {
  headers: Headers;
};
export type listInboxResponseError = (listInboxResponseDefault) & {
  headers: Headers;
};

export type listInboxResponse = (listInboxResponseSuccess | listInboxResponseError)

export const getListInboxUrl = (params?: ListInboxParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/notifications/inbox?${stringifiedParams}` : `/api/v1/notifications/inbox`
}

export const listInbox = async (params?: ListInboxParams, options?: RequestInit): Promise<listInboxResponse> => {
  
  return customFetch<listInboxResponse>(getListInboxUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Marks all inbox notifications as read for the authenticated user.
 * @summary Mark all as read
 */
export type markAllAsReadResponse200 = {
  data: MarkAllAsReadResponseBody
  status: 200
}

export type markAllAsReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type markAllAsReadResponseSuccess = (markAllAsReadResponse200) & {
  headers: Headers;
};
export type markAllAsReadResponseError = (markAllAsReadResponseDefault) & {
  headers: Headers;
};

export type markAllAsReadResponse = (markAllAsReadResponseSuccess | markAllAsReadResponseError)

export const getMarkAllAsReadUrl = () => {


  

  return `/api/v1/notifications/inbox/read-all`
}

export const markAllAsRead = async ( options?: RequestInit): Promise<markAllAsReadResponse> => {
  
  return customFetch<markAllAsReadResponse>(getMarkAllAsReadUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  

/**
 * Returns the number of unread notifications for the authenticated user.
 * @summary Get unread count
 */
export type getUnreadCountResponse200 = {
  data: UnreadCountResponseBody
  status: 200
}

export type getUnreadCountResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getUnreadCountResponseSuccess = (getUnreadCountResponse200) & {
  headers: Headers;
};
export type getUnreadCountResponseError = (getUnreadCountResponseDefault) & {
  headers: Headers;
};

export type getUnreadCountResponse = (getUnreadCountResponseSuccess | getUnreadCountResponseError)

export const getGetUnreadCountUrl = () => {


  

  return `/api/v1/notifications/inbox/unread-count`
}

export const getUnreadCount = async ( options?: RequestInit): Promise<getUnreadCountResponse> => {
  
  return customFetch<getUnreadCountResponse>(getGetUnreadCountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Soft-deletes a single inbox notification.
 * @summary Delete notification
 */
export type deleteNotificationResponse200 = {
  data: DeleteNotificationResponseBody
  status: 200
}

export type deleteNotificationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteNotificationResponseSuccess = (deleteNotificationResponse200) & {
  headers: Headers;
};
export type deleteNotificationResponseError = (deleteNotificationResponseDefault) & {
  headers: Headers;
};

export type deleteNotificationResponse = (deleteNotificationResponseSuccess | deleteNotificationResponseError)

export const getDeleteNotificationUrl = (id: string,) => {


  

  return `/api/v1/notifications/inbox/${id}`
}

export const deleteNotification = async (id: string, options?: RequestInit): Promise<deleteNotificationResponse> => {
  
  return customFetch<deleteNotificationResponse>(getDeleteNotificationUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Archives a single inbox notification.
 * @summary Archive notification
 */
export type archiveNotificationResponse200 = {
  data: ArchiveNotificationResponseBody
  status: 200
}

export type archiveNotificationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type archiveNotificationResponseSuccess = (archiveNotificationResponse200) & {
  headers: Headers;
};
export type archiveNotificationResponseError = (archiveNotificationResponseDefault) & {
  headers: Headers;
};

export type archiveNotificationResponse = (archiveNotificationResponseSuccess | archiveNotificationResponseError)

export const getArchiveNotificationUrl = (id: string,) => {


  

  return `/api/v1/notifications/inbox/${id}/archive`
}

export const archiveNotification = async (id: string, options?: RequestInit): Promise<archiveNotificationResponse> => {
  
  return customFetch<archiveNotificationResponse>(getArchiveNotificationUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}
  

/**
 * Marks a single inbox notification as read.
 * @summary Mark as read
 */
export type markAsReadResponse200 = {
  data: MarkAsReadResponseBody
  status: 200
}

export type markAsReadResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type markAsReadResponseSuccess = (markAsReadResponse200) & {
  headers: Headers;
};
export type markAsReadResponseError = (markAsReadResponseDefault) & {
  headers: Headers;
};

export type markAsReadResponse = (markAsReadResponseSuccess | markAsReadResponseError)

export const getMarkAsReadUrl = (id: string,) => {


  

  return `/api/v1/notifications/inbox/${id}/read`
}

export const markAsRead = async (id: string, options?: RequestInit): Promise<markAsReadResponse> => {
  
  return customFetch<markAsReadResponse>(getMarkAsReadUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}
  

/**
 * Lists all muted accounts for the authenticated user.
 * @summary List mutes
 */
export type listMutesResponse200 = {
  data: ListMutesResponseBody
  status: 200
}

export type listMutesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listMutesResponseSuccess = (listMutesResponse200) & {
  headers: Headers;
};
export type listMutesResponseError = (listMutesResponseDefault) & {
  headers: Headers;
};

export type listMutesResponse = (listMutesResponseSuccess | listMutesResponseError)

export const getListMutesUrl = (params?: ListMutesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/notifications/mutes?${stringifiedParams}` : `/api/v1/notifications/mutes`
}

export const listMutes = async (params?: ListMutesParams, options?: RequestInit): Promise<listMutesResponse> => {
  
  return customFetch<listMutesResponse>(getListMutesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Mutes an account so their notifications are not shown in the inbox.
 * @summary Mute account
 */
export type muteAccountResponse200 = {
  data: MuteAccountResponseBody
  status: 200
}

export type muteAccountResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type muteAccountResponseSuccess = (muteAccountResponse200) & {
  headers: Headers;
};
export type muteAccountResponseError = (muteAccountResponseDefault) & {
  headers: Headers;
};

export type muteAccountResponse = (muteAccountResponseSuccess | muteAccountResponseError)

export const getMuteAccountUrl = () => {


  

  return `/api/v1/notifications/mutes`
}

export const muteAccount = async (muteAccountRequest: NonReadonly<MuteAccountRequest>, options?: RequestInit): Promise<muteAccountResponse> => {
  
  return customFetch<muteAccountResponse>(getMuteAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      muteAccountRequest,)
  }
);}
  

/**
 * Unmutes a previously muted account.
 * @summary Unmute account
 */
export type unmuteAccountResponse200 = {
  data: UnmuteAccountResponseBody
  status: 200
}

export type unmuteAccountResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type unmuteAccountResponseSuccess = (unmuteAccountResponse200) & {
  headers: Headers;
};
export type unmuteAccountResponseError = (unmuteAccountResponseDefault) & {
  headers: Headers;
};

export type unmuteAccountResponse = (unmuteAccountResponseSuccess | unmuteAccountResponseError)

export const getUnmuteAccountUrl = (accountId: string,) => {


  

  return `/api/v1/notifications/mutes/${accountId}`
}

export const unmuteAccount = async (accountId: string, options?: RequestInit): Promise<unmuteAccountResponse> => {
  
  return customFetch<unmuteAccountResponse>(getUnmuteAccountUrl(accountId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Lists all notification preference overrides for the authenticated user.
 * @summary List preferences
 */
export type listPreferencesResponse200 = {
  data: PreferenceResponse[] | null
  status: 200
}

export type listPreferencesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPreferencesResponseSuccess = (listPreferencesResponse200) & {
  headers: Headers;
};
export type listPreferencesResponseError = (listPreferencesResponseDefault) & {
  headers: Headers;
};

export type listPreferencesResponse = (listPreferencesResponseSuccess | listPreferencesResponseError)

export const getListPreferencesUrl = () => {


  

  return `/api/v1/notifications/preferences`
}

export const listPreferences = async ( options?: RequestInit): Promise<listPreferencesResponse> => {
  
  return customFetch<listPreferencesResponse>(getListPreferencesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Sets a notification preference override for a type+channel combination.
 * @summary Set preference
 */
export type setPreferenceResponse200 = {
  data: SetPreferenceResponseBody
  status: 200
}

export type setPreferenceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type setPreferenceResponseSuccess = (setPreferenceResponse200) & {
  headers: Headers;
};
export type setPreferenceResponseError = (setPreferenceResponseDefault) & {
  headers: Headers;
};

export type setPreferenceResponse = (setPreferenceResponseSuccess | setPreferenceResponseError)

export const getSetPreferenceUrl = () => {


  

  return `/api/v1/notifications/preferences`
}

export const setPreference = async (setPreferenceRequest: NonReadonly<SetPreferenceRequest>, options?: RequestInit): Promise<setPreferenceResponse> => {
  
  return customFetch<setPreferenceResponse>(getSetPreferenceUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      setPreferenceRequest,)
  }
);}
  

/**
 * Deletes a notification preference override, reverting to defaults.
 * @summary Delete preference
 */
export type deletePreferenceResponse200 = {
  data: DeletePreferenceResponseBody
  status: 200
}

export type deletePreferenceResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deletePreferenceResponseSuccess = (deletePreferenceResponse200) & {
  headers: Headers;
};
export type deletePreferenceResponseError = (deletePreferenceResponseDefault) & {
  headers: Headers;
};

export type deletePreferenceResponse = (deletePreferenceResponseSuccess | deletePreferenceResponseError)

export const getDeletePreferenceUrl = (type: string,
    channel: string,) => {


  

  return `/api/v1/notifications/preferences/${type}/${channel}`
}

export const deletePreference = async (type: string,
    channel: string, options?: RequestInit): Promise<deletePreferenceResponse> => {
  
  return customFetch<deletePreferenceResponse>(getDeletePreferenceUrl(type,channel),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Lists all scheduled alerts for the authenticated user.
 * @summary List scheduled alerts
 */
export type listScheduledAlertsResponse200 = {
  data: ListScheduledAlertsResponseBody
  status: 200
}

export type listScheduledAlertsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listScheduledAlertsResponseSuccess = (listScheduledAlertsResponse200) & {
  headers: Headers;
};
export type listScheduledAlertsResponseError = (listScheduledAlertsResponseDefault) & {
  headers: Headers;
};

export type listScheduledAlertsResponse = (listScheduledAlertsResponseSuccess | listScheduledAlertsResponseError)

export const getListScheduledAlertsUrl = () => {


  

  return `/api/v1/notifications/scheduled`
}

export const listScheduledAlerts = async ( options?: RequestInit): Promise<listScheduledAlertsResponse> => {
  
  return customFetch<listScheduledAlertsResponse>(getListScheduledAlertsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a new scheduled alert for the authenticated user.
 * @summary Create scheduled alert
 */
export type createScheduledAlertResponse200 = {
  data: CreateScheduledAlertResponseBody
  status: 200
}

export type createScheduledAlertResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createScheduledAlertResponseSuccess = (createScheduledAlertResponse200) & {
  headers: Headers;
};
export type createScheduledAlertResponseError = (createScheduledAlertResponseDefault) & {
  headers: Headers;
};

export type createScheduledAlertResponse = (createScheduledAlertResponseSuccess | createScheduledAlertResponseError)

export const getCreateScheduledAlertUrl = () => {


  

  return `/api/v1/notifications/scheduled`
}

export const createScheduledAlert = async (createScheduledAlertRequest: NonReadonly<CreateScheduledAlertRequest>, options?: RequestInit): Promise<createScheduledAlertResponse> => {
  
  return customFetch<createScheduledAlertResponse>(getCreateScheduledAlertUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createScheduledAlertRequest,)
  }
);}
  

/**
 * Lists all available templates for creating scheduled alerts.
 * @summary List scheduled alert templates
 */
export type listScheduledAlertTemplatesResponse200 = {
  data: ListScheduledTemplatesResponseBody
  status: 200
}

export type listScheduledAlertTemplatesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listScheduledAlertTemplatesResponseSuccess = (listScheduledAlertTemplatesResponse200) & {
  headers: Headers;
};
export type listScheduledAlertTemplatesResponseError = (listScheduledAlertTemplatesResponseDefault) & {
  headers: Headers;
};

export type listScheduledAlertTemplatesResponse = (listScheduledAlertTemplatesResponseSuccess | listScheduledAlertTemplatesResponseError)

export const getListScheduledAlertTemplatesUrl = () => {


  

  return `/api/v1/notifications/scheduled/templates`
}

export const listScheduledAlertTemplates = async ( options?: RequestInit): Promise<listScheduledAlertTemplatesResponse> => {
  
  return customFetch<listScheduledAlertTemplatesResponse>(getListScheduledAlertTemplatesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Cancels a pending scheduled alert.
 * @summary Cancel scheduled alert
 */
export type cancelScheduledAlertResponse200 = {
  data: CancelScheduledAlertResponseBody
  status: 200
}

export type cancelScheduledAlertResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type cancelScheduledAlertResponseSuccess = (cancelScheduledAlertResponse200) & {
  headers: Headers;
};
export type cancelScheduledAlertResponseError = (cancelScheduledAlertResponseDefault) & {
  headers: Headers;
};

export type cancelScheduledAlertResponse = (cancelScheduledAlertResponseSuccess | cancelScheduledAlertResponseError)

export const getCancelScheduledAlertUrl = (id: string,) => {


  

  return `/api/v1/notifications/scheduled/${id}/cancel`
}

export const cancelScheduledAlert = async (id: string, options?: RequestInit): Promise<cancelScheduledAlertResponse> => {
  
  return customFetch<cancelScheduledAlertResponse>(getCancelScheduledAlertUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}
  

/**
 * Reschedules a pending scheduled alert to a new date.
 * @summary Reschedule scheduled alert
 */
export type rescheduleScheduledAlertResponse200 = {
  data: RescheduleScheduledAlertResponseBody
  status: 200
}

export type rescheduleScheduledAlertResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type rescheduleScheduledAlertResponseSuccess = (rescheduleScheduledAlertResponse200) & {
  headers: Headers;
};
export type rescheduleScheduledAlertResponseError = (rescheduleScheduledAlertResponseDefault) & {
  headers: Headers;
};

export type rescheduleScheduledAlertResponse = (rescheduleScheduledAlertResponseSuccess | rescheduleScheduledAlertResponseError)

export const getRescheduleScheduledAlertUrl = (id: string,) => {


  

  return `/api/v1/notifications/scheduled/${id}/reschedule`
}

export const rescheduleScheduledAlert = async (id: string,
    rescheduleScheduledAlertRequest: NonReadonly<RescheduleScheduledAlertRequest>, options?: RequestInit): Promise<rescheduleScheduledAlertResponse> => {
  
  return customFetch<rescheduleScheduledAlertResponse>(getRescheduleScheduledAlertUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      rescheduleScheduledAlertRequest,)
  }
);}
  

