/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  GetOAuthProvidersResponse,
  OAuthCallbackResponse,
  OAuthCompleteEmailRequest,
  OAuthIdentitiesResponse,
  OAuthLinkCallbackOutputBody,
  OAuthUnlinkOutputBody,
  OauthCallbackMobileParams,
  OauthCallbackParams,
  OauthLinkCallbackParams
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Handles the OAuth callback from the provider. Returns JSON response.
 * @summary OAuth callback
 */
export type oauthCallbackResponse200 = {
  data: OAuthCallbackResponse
  status: 200
}

export type oauthCallbackResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type oauthCallbackResponseSuccess = (oauthCallbackResponse200) & {
  headers: Headers;
};
export type oauthCallbackResponseError = (oauthCallbackResponseDefault) & {
  headers: Headers;
};

export type oauthCallbackResponse = (oauthCallbackResponseSuccess | oauthCallbackResponseError)

export const getOauthCallbackUrl = (provider: string,
    params?: OauthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/oauth/callback/${provider}?${stringifiedParams}` : `/api/v1/auth/oauth/callback/${provider}`
}

export const oauthCallback = async (provider: string,
    params?: OauthCallbackParams, options?: RequestInit): Promise<oauthCallbackResponse> => {
  
  return customFetch<oauthCallbackResponse>(getOauthCallbackUrl(provider,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Handles the OAuth callback and returns HTTP 302 redirect to mobile deep-link.
 * @summary OAuth callback for mobile
 */
export type oauthCallbackMobileResponse302 = {
  data: void
  status: 302
}

export type oauthCallbackMobileResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 302>
}

;
export type oauthCallbackMobileResponseError = (oauthCallbackMobileResponse302 | oauthCallbackMobileResponseDefault) & {
  headers: Headers;
};

export type oauthCallbackMobileResponse = (oauthCallbackMobileResponseError)

export const getOauthCallbackMobileUrl = (provider: string,
    params?: OauthCallbackMobileParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/oauth/callback/${provider}/mobile?${stringifiedParams}` : `/api/v1/auth/oauth/callback/${provider}/mobile`
}

export const oauthCallbackMobile = async (provider: string,
    params?: OauthCallbackMobileParams, options?: RequestInit): Promise<oauthCallbackMobileResponse> => {
  
  return customFetch<oauthCallbackMobileResponse>(getOauthCallbackMobileUrl(provider,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Completes OAuth flow when email is required.
 * @summary Complete OAuth with email
 */
export type oauthCompleteWithEmailResponse200 = {
  data: OAuthCallbackResponse
  status: 200
}

export type oauthCompleteWithEmailResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type oauthCompleteWithEmailResponseSuccess = (oauthCompleteWithEmailResponse200) & {
  headers: Headers;
};
export type oauthCompleteWithEmailResponseError = (oauthCompleteWithEmailResponseDefault) & {
  headers: Headers;
};

export type oauthCompleteWithEmailResponse = (oauthCompleteWithEmailResponseSuccess | oauthCompleteWithEmailResponseError)

export const getOauthCompleteWithEmailUrl = () => {


  

  return `/api/v1/auth/oauth/complete`
}

export const oauthCompleteWithEmail = async (oAuthCompleteEmailRequest: NonReadonly<OAuthCompleteEmailRequest>, options?: RequestInit): Promise<oauthCompleteWithEmailResponse> => {
  
  return customFetch<oauthCompleteWithEmailResponse>(getOauthCompleteWithEmailUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      oAuthCompleteEmailRequest,)
  }
);}
  

/**
 * Returns all OAuth providers linked to the authenticated account.
 * @summary List linked OAuth identities
 */
export type getOAuthIdentitiesResponse200 = {
  data: OAuthIdentitiesResponse
  status: 200
}

export type getOAuthIdentitiesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getOAuthIdentitiesResponseSuccess = (getOAuthIdentitiesResponse200) & {
  headers: Headers;
};
export type getOAuthIdentitiesResponseError = (getOAuthIdentitiesResponseDefault) & {
  headers: Headers;
};

export type getOAuthIdentitiesResponse = (getOAuthIdentitiesResponseSuccess | getOAuthIdentitiesResponseError)

export const getGetOAuthIdentitiesUrl = () => {


  

  return `/api/v1/auth/oauth/identities`
}

export const getOAuthIdentities = async ( options?: RequestInit): Promise<getOAuthIdentitiesResponse> => {
  
  return customFetch<getOAuthIdentitiesResponse>(getGetOAuthIdentitiesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Unlinks an OAuth provider from the authenticated account.
 * @summary Unlink OAuth provider
 */
export type unlinkOAuthProviderResponse200 = {
  data: OAuthUnlinkOutputBody
  status: 200
}

export type unlinkOAuthProviderResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type unlinkOAuthProviderResponseSuccess = (unlinkOAuthProviderResponse200) & {
  headers: Headers;
};
export type unlinkOAuthProviderResponseError = (unlinkOAuthProviderResponseDefault) & {
  headers: Headers;
};

export type unlinkOAuthProviderResponse = (unlinkOAuthProviderResponseSuccess | unlinkOAuthProviderResponseError)

export const getUnlinkOAuthProviderUrl = (provider: string,) => {


  

  return `/api/v1/auth/oauth/identities/${provider}`
}

export const unlinkOAuthProvider = async (provider: string, options?: RequestInit): Promise<unlinkOAuthProviderResponse> => {
  
  return customFetch<unlinkOAuthProviderResponse>(getUnlinkOAuthProviderUrl(provider),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Handles the OAuth callback when linking a provider.
 * @summary OAuth link callback
 */
export type oauthLinkCallbackResponse200 = {
  data: OAuthLinkCallbackOutputBody
  status: 200
}

export type oauthLinkCallbackResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type oauthLinkCallbackResponseSuccess = (oauthLinkCallbackResponse200) & {
  headers: Headers;
};
export type oauthLinkCallbackResponseError = (oauthLinkCallbackResponseDefault) & {
  headers: Headers;
};

export type oauthLinkCallbackResponse = (oauthLinkCallbackResponseSuccess | oauthLinkCallbackResponseError)

export const getOauthLinkCallbackUrl = (provider: string,
    params?: OauthLinkCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/auth/oauth/link/callback/${provider}?${stringifiedParams}` : `/api/v1/auth/oauth/link/callback/${provider}`
}

export const oauthLinkCallback = async (provider: string,
    params?: OauthLinkCallbackParams, options?: RequestInit): Promise<oauthLinkCallbackResponse> => {
  
  return customFetch<oauthLinkCallbackResponse>(getOauthLinkCallbackUrl(provider,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Initiates linking an OAuth provider to the authenticated account.
 * @summary Initiate OAuth link
 */
export type initiateOAuthLinkResponse204 = {
  data: void
  status: 204
}

export type initiateOAuthLinkResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type initiateOAuthLinkResponseSuccess = (initiateOAuthLinkResponse204) & {
  headers: Headers;
};
export type initiateOAuthLinkResponseError = (initiateOAuthLinkResponseDefault) & {
  headers: Headers;
};

export type initiateOAuthLinkResponse = (initiateOAuthLinkResponseSuccess | initiateOAuthLinkResponseError)

export const getInitiateOAuthLinkUrl = (provider: string,) => {


  

  return `/api/v1/auth/oauth/link/${provider}`
}

export const initiateOAuthLink = async (provider: string, options?: RequestInit): Promise<initiateOAuthLinkResponse> => {
  
  return customFetch<initiateOAuthLinkResponse>(getInitiateOAuthLinkUrl(provider),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Redirects to the OAuth provider for authentication.
 * @summary Initiate OAuth login
 */
export type initiateOAuthLoginResponse302 = {
  data: void
  status: 302
}

export type initiateOAuthLoginResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 302>
}

;
export type initiateOAuthLoginResponseError = (initiateOAuthLoginResponse302 | initiateOAuthLoginResponseDefault) & {
  headers: Headers;
};

export type initiateOAuthLoginResponse = (initiateOAuthLoginResponseError)

export const getInitiateOAuthLoginUrl = (provider: string,) => {


  

  return `/api/v1/auth/oauth/login/${provider}`
}

export const initiateOAuthLogin = async (provider: string, options?: RequestInit): Promise<initiateOAuthLoginResponse> => {
  
  return customFetch<initiateOAuthLoginResponse>(getInitiateOAuthLoginUrl(provider),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Returns a list of available OAuth providers for authentication.
 * @summary List OAuth providers
 */
export type getOAuthProvidersResponse200 = {
  data: GetOAuthProvidersResponse
  status: 200
}

export type getOAuthProvidersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getOAuthProvidersResponseSuccess = (getOAuthProvidersResponse200) & {
  headers: Headers;
};
export type getOAuthProvidersResponseError = (getOAuthProvidersResponseDefault) & {
  headers: Headers;
};

export type getOAuthProvidersResponse = (getOAuthProvidersResponseSuccess | getOAuthProvidersResponseError)

export const getGetOAuthProvidersUrl = () => {


  

  return `/api/v1/auth/oauth/providers`
}

export const getOAuthProviders = async ( options?: RequestInit): Promise<getOAuthProvidersResponse> => {
  
  return customFetch<getOAuthProvidersResponse>(getGetOAuthProvidersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

