/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  GetMySubscriptionResponseBody,
  InitiatePaymentRequestBody,
  InitiatePaymentResponseBody,
  ListPlansResponseBody,
  VerifyPaymentRequestBody,
  VerifyPaymentResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns the current account's active subscription.
 * @summary Get my subscription
 */
export type getMySubscriptionResponse200 = {
  data: GetMySubscriptionResponseBody
  status: 200
}

export type getMySubscriptionResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getMySubscriptionResponseSuccess = (getMySubscriptionResponse200) & {
  headers: Headers;
};
export type getMySubscriptionResponseError = (getMySubscriptionResponseDefault) & {
  headers: Headers;
};

export type getMySubscriptionResponse = (getMySubscriptionResponseSuccess | getMySubscriptionResponseError)

export const getGetMySubscriptionUrl = () => {


  

  return `/api/v1/me/subscription`
}

export const getMySubscription = async ( options?: RequestInit): Promise<getMySubscriptionResponse> => {
  
  return customFetch<getMySubscriptionResponse>(getGetMySubscriptionUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Starts a new payment transaction and returns a Chapa checkout URL.
 * @summary Initiate payment
 */
export type initiatePaymentResponse200 = {
  data: InitiatePaymentResponseBody
  status: 200
}

export type initiatePaymentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type initiatePaymentResponseSuccess = (initiatePaymentResponse200) & {
  headers: Headers;
};
export type initiatePaymentResponseError = (initiatePaymentResponseDefault) & {
  headers: Headers;
};

export type initiatePaymentResponse = (initiatePaymentResponseSuccess | initiatePaymentResponseError)

export const getInitiatePaymentUrl = () => {


  

  return `/api/v1/payments/initiate`
}

export const initiatePayment = async (initiatePaymentRequestBody: NonReadonly<InitiatePaymentRequestBody>, options?: RequestInit): Promise<initiatePaymentResponse> => {
  
  return customFetch<initiatePaymentResponse>(getInitiatePaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      initiatePaymentRequestBody,)
  }
);}
  

/**
 * Returns all available subscription plans.
 * @summary List subscription plans
 */
export type listPlansResponse200 = {
  data: ListPlansResponseBody
  status: 200
}

export type listPlansResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPlansResponseSuccess = (listPlansResponse200) & {
  headers: Headers;
};
export type listPlansResponseError = (listPlansResponseDefault) & {
  headers: Headers;
};

export type listPlansResponse = (listPlansResponseSuccess | listPlansResponseError)

export const getListPlansUrl = () => {


  

  return `/api/v1/payments/plans`
}

export const listPlans = async ( options?: RequestInit): Promise<listPlansResponse> => {
  
  return customFetch<listPlansResponse>(getListPlansUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Verifies the status of a payment by transaction reference.
 * @summary Verify payment
 */
export type verifyPaymentResponse200 = {
  data: VerifyPaymentResponseBody
  status: 200
}

export type verifyPaymentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type verifyPaymentResponseSuccess = (verifyPaymentResponse200) & {
  headers: Headers;
};
export type verifyPaymentResponseError = (verifyPaymentResponseDefault) & {
  headers: Headers;
};

export type verifyPaymentResponse = (verifyPaymentResponseSuccess | verifyPaymentResponseError)

export const getVerifyPaymentUrl = () => {


  

  return `/api/v1/payments/verify`
}

export const verifyPayment = async (verifyPaymentRequestBody: NonReadonly<VerifyPaymentRequestBody>, options?: RequestInit): Promise<verifyPaymentResponse> => {
  
  return customFetch<verifyPaymentResponse>(getVerifyPaymentUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyPaymentRequestBody,)
  }
);}
  

