/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  ListPermissionsParams,
  ListPermissionsResponseBody
} from '../types';




export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns permissions with optional filtering by module and code.
 * @summary List permissions
 */
export type listPermissionsResponse200 = {
  data: ListPermissionsResponseBody
  status: 200
}

export type listPermissionsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listPermissionsResponseSuccess = (listPermissionsResponse200) & {
  headers: Headers;
};
export type listPermissionsResponseError = (listPermissionsResponseDefault) & {
  headers: Headers;
};

export type listPermissionsResponse = (listPermissionsResponseSuccess | listPermissionsResponseError)

export const getListPermissionsUrl = (params?: ListPermissionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/permissions?${stringifiedParams}` : `/api/v1/permissions`
}

export const listPermissions = async (params?: ListPermissionsParams, options?: RequestInit): Promise<listPermissionsResponse> => {
  
  const res = await fetch(getListPermissionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: listPermissionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listPermissionsResponse
}
  

