/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateRoleRequest,
  CreateRoleResponseBody,
  DeleteRoleOutputBody,
  ErrorModel,
  GetRoleResponseBody,
  ListRolesResponseBody,
  UpdateRoleRequest,
  UpdateRoleResponseBody
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Returns all roles.
 * @summary List roles
 */
export type listRolesResponse200 = {
  data: ListRolesResponseBody
  status: 200
}

export type listRolesResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listRolesResponseSuccess = (listRolesResponse200) & {
  headers: Headers;
};
export type listRolesResponseError = (listRolesResponseDefault) & {
  headers: Headers;
};

export type listRolesResponse = (listRolesResponseSuccess | listRolesResponseError)

export const getListRolesUrl = () => {


  

  return `/api/v1/roles`
}

export const listRoles = async ( options?: RequestInit): Promise<listRolesResponse> => {
  
  return customFetch<listRolesResponse>(getListRolesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Creates a custom role and assigns permissions.
 * @summary Create role
 */
export type createRoleResponse200 = {
  data: CreateRoleResponseBody
  status: 200
}

export type createRoleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type createRoleResponseSuccess = (createRoleResponse200) & {
  headers: Headers;
};
export type createRoleResponseError = (createRoleResponseDefault) & {
  headers: Headers;
};

export type createRoleResponse = (createRoleResponseSuccess | createRoleResponseError)

export const getCreateRoleUrl = () => {


  

  return `/api/v1/roles`
}

export const createRole = async (createRoleRequest: NonReadonly<CreateRoleRequest>, options?: RequestInit): Promise<createRoleResponse> => {
  
  return customFetch<createRoleResponse>(getCreateRoleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createRoleRequest,)
  }
);}
  

/**
 * Permanently deletes a role if it is mutable.
 * @summary Delete role
 */
export type deleteRoleResponse200 = {
  data: DeleteRoleOutputBody
  status: 200
}

export type deleteRoleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type deleteRoleResponseSuccess = (deleteRoleResponse200) & {
  headers: Headers;
};
export type deleteRoleResponseError = (deleteRoleResponseDefault) & {
  headers: Headers;
};

export type deleteRoleResponse = (deleteRoleResponseSuccess | deleteRoleResponseError)

export const getDeleteRoleUrl = (roleId: string,) => {


  

  return `/api/v1/roles/${roleId}`
}

export const deleteRole = async (roleId: string, options?: RequestInit): Promise<deleteRoleResponse> => {
  
  return customFetch<deleteRoleResponse>(getDeleteRoleUrl(roleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}
  

/**
 * Returns role details and its permissions.
 * @summary Get role
 */
export type getRoleResponse200 = {
  data: GetRoleResponseBody
  status: 200
}

export type getRoleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getRoleResponseSuccess = (getRoleResponse200) & {
  headers: Headers;
};
export type getRoleResponseError = (getRoleResponseDefault) & {
  headers: Headers;
};

export type getRoleResponse = (getRoleResponseSuccess | getRoleResponseError)

export const getGetRoleUrl = (roleId: string,) => {


  

  return `/api/v1/roles/${roleId}`
}

export const getRole = async (roleId: string, options?: RequestInit): Promise<getRoleResponse> => {
  
  return customFetch<getRoleResponse>(getGetRoleUrl(roleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Updates role details and replaces permissions.
 * @summary Update role
 */
export type updateRoleResponse200 = {
  data: UpdateRoleResponseBody
  status: 200
}

export type updateRoleResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateRoleResponseSuccess = (updateRoleResponse200) & {
  headers: Headers;
};
export type updateRoleResponseError = (updateRoleResponseDefault) & {
  headers: Headers;
};

export type updateRoleResponse = (updateRoleResponseSuccess | updateRoleResponseError)

export const getUpdateRoleUrl = (roleId: string,) => {


  

  return `/api/v1/roles/${roleId}`
}

export const updateRole = async (roleId: string,
    updateRoleRequest: NonReadonly<UpdateRoleRequest>, options?: RequestInit): Promise<updateRoleResponse> => {
  
  return customFetch<updateRoleResponse>(getUpdateRoleUrl(roleId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateRoleRequest,)
  }
);}
  

