/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  ListSectorsResponseBody,
  ListTagsResponseBody,
  ListTaxonomySectorsParams,
  ListTaxonomyTagsParams,
  SectorResponse,
  TagResponse
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Lists all available sectors.
 * @summary List sectors
 */
export type listTaxonomySectorsResponse200 = {
  data: ListSectorsResponseBody
  status: 200
}

export type listTaxonomySectorsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listTaxonomySectorsResponseSuccess = (listTaxonomySectorsResponse200) & {
  headers: Headers;
};
export type listTaxonomySectorsResponseError = (listTaxonomySectorsResponseDefault) & {
  headers: Headers;
};

export type listTaxonomySectorsResponse = (listTaxonomySectorsResponseSuccess | listTaxonomySectorsResponseError)

export const getListTaxonomySectorsUrl = (params?: ListTaxonomySectorsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/taxonomy/sectors?${stringifiedParams}` : `/api/v1/taxonomy/sectors`
}

export const listTaxonomySectors = async (params?: ListTaxonomySectorsParams, options?: RequestInit): Promise<listTaxonomySectorsResponse> => {
  
  return customFetch<listTaxonomySectorsResponse>(getListTaxonomySectorsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Retrieves a single sector by ID.
 * @summary Get sector
 */
export type getTaxonomySectorResponse200 = {
  data: SectorResponse
  status: 200
}

export type getTaxonomySectorResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getTaxonomySectorResponseSuccess = (getTaxonomySectorResponse200) & {
  headers: Headers;
};
export type getTaxonomySectorResponseError = (getTaxonomySectorResponseDefault) & {
  headers: Headers;
};

export type getTaxonomySectorResponse = (getTaxonomySectorResponseSuccess | getTaxonomySectorResponseError)

export const getGetTaxonomySectorUrl = (id: string,) => {


  

  return `/api/v1/taxonomy/sectors/${id}`
}

export const getTaxonomySector = async (id: string, options?: RequestInit): Promise<getTaxonomySectorResponse> => {
  
  return customFetch<getTaxonomySectorResponse>(getGetTaxonomySectorUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Lists all available tags.
 * @summary List tags
 */
export type listTaxonomyTagsResponse200 = {
  data: ListTagsResponseBody
  status: 200
}

export type listTaxonomyTagsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listTaxonomyTagsResponseSuccess = (listTaxonomyTagsResponse200) & {
  headers: Headers;
};
export type listTaxonomyTagsResponseError = (listTaxonomyTagsResponseDefault) & {
  headers: Headers;
};

export type listTaxonomyTagsResponse = (listTaxonomyTagsResponseSuccess | listTaxonomyTagsResponseError)

export const getListTaxonomyTagsUrl = (params?: ListTaxonomyTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/taxonomy/tags?${stringifiedParams}` : `/api/v1/taxonomy/tags`
}

export const listTaxonomyTags = async (params?: ListTaxonomyTagsParams, options?: RequestInit): Promise<listTaxonomyTagsResponse> => {
  
  return customFetch<listTaxonomyTagsResponse>(getListTaxonomyTagsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

/**
 * Retrieves a single tag by ID.
 * @summary Get tag
 */
export type getTaxonomyTagResponse200 = {
  data: TagResponse
  status: 200
}

export type getTaxonomyTagResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getTaxonomyTagResponseSuccess = (getTaxonomyTagResponse200) & {
  headers: Headers;
};
export type getTaxonomyTagResponseError = (getTaxonomyTagResponseDefault) & {
  headers: Headers;
};

export type getTaxonomyTagResponse = (getTaxonomyTagResponseSuccess | getTaxonomyTagResponseError)

export const getGetTaxonomyTagUrl = (id: string,) => {


  

  return `/api/v1/taxonomy/tags/${id}`
}

export const getTaxonomyTag = async (id: string, options?: RequestInit): Promise<getTaxonomyTagResponse> => {
  
  return customFetch<getTaxonomyTagResponse>(getGetTaxonomyTagUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  

