/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  UpdateUserProfileRequest,
  UpdateUserProfileResponseBody,
  UploadAvatarBody,
  UploadAvatarResponse
} from '../types';

import { customFetch } from '../mutator/custom-fetch';



// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;

/**
 * Uploads and sets the authenticated user's avatar image
 * @summary Upload user avatar
 */
export type uploadAvatarResponse200 = {
  data: UploadAvatarResponse
  status: 200
}

export type uploadAvatarResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type uploadAvatarResponseSuccess = (uploadAvatarResponse200) & {
  headers: Headers;
};
export type uploadAvatarResponseError = (uploadAvatarResponseDefault) & {
  headers: Headers;
};

export type uploadAvatarResponse = (uploadAvatarResponseSuccess | uploadAvatarResponseError)

export const getUploadAvatarUrl = () => {


  

  return `/api/v1/users/avatar`
}

export const uploadAvatar = async (uploadAvatarBody: UploadAvatarBody, options?: RequestInit): Promise<uploadAvatarResponse> => {
    const formData = new FormData();
formData.append(`file`, uploadAvatarBody.file);

  return customFetch<uploadAvatarResponse>(getUploadAvatarUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}
  

/**
 * Updates the authenticated user's profile information such as name, bio, or other editable account fields.
 * @summary Update user profile
 */
export type updateUserProfileResponse200 = {
  data: UpdateUserProfileResponseBody
  status: 200
}

export type updateUserProfileResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateUserProfileResponseSuccess = (updateUserProfileResponse200) & {
  headers: Headers;
};
export type updateUserProfileResponseError = (updateUserProfileResponseDefault) & {
  headers: Headers;
};

export type updateUserProfileResponse = (updateUserProfileResponseSuccess | updateUserProfileResponseError)

export const getUpdateUserProfileUrl = () => {


  

  return `/api/v1/users/profile`
}

export const updateUserProfile = async (updateUserProfileRequest: NonReadonly<UpdateUserProfileRequest>, options?: RequestInit): Promise<updateUserProfileResponse> => {
  
  return customFetch<updateUserProfileResponse>(getUpdateUserProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateUserProfileRequest,)
  }
);}
  

