/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface AccountPreferenceResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** User's language preference (en, am) */
  language: string;
  /** User's timezone (e.g. UTC, Africa/Addis_Ababa) */
  timezone: string;
}
