/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { ActivityLogEntry } from './activityLogEntry';

export interface ActivityLogsResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  data: ActivityLogEntry[] | null;
}
