/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface AdminRegisterRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Email address
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * First name
   * @minLength 1
   * @maxLength 100
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   * @maxLength 100
   */
  lastName: string;
  /**
   * Role IDs
   * @nullable
   */
  roleIds: string[] | null;
  /**
   * Username (lowercase letters, digits, underscore)
   * @minLength 3
   * @maxLength 32
   * @pattern ^[a-z0-9_]+$
   */
  username?: string;
}
