/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AdminConditionDTO } from './adminConditionDTO';
import type { AdminTranslationDTO } from './adminTranslationDTO';

export interface AdminGuideDetailDTO {
  /** @nullable */
  conditions: AdminConditionDTO[] | null;
  icon?: string;
  id: string;
  imageUrl?: string;
  /** @nullable */
  sectorIds: string[] | null;
  slug: string;
  sortOrder: number;
  /** @nullable */
  tagIds: string[] | null;
  /** @nullable */
  translations: AdminTranslationDTO[] | null;
}
