/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface AdminGuideCardDTO {
  description?: string;
  icon?: string;
  id: string;
  name: string;
  /** @nullable */
  sectorIds: string[] | null;
  slug: string;
  sortOrder: number;
  /** @nullable */
  tagIds: string[] | null;
}
