/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AdminStepDocumentDTO } from './adminStepDocumentDTO';
import type { AdminStepTranslationDTO } from './adminStepTranslationDTO';

export interface AdminGuideStepDTO {
  difficultyLevel?: number;
  effectiveDate: string;
  estimatedTime?: number;
  expiryDate?: string;
  feeEstimate?: number;
  guideId: string;
  id: string;
  isOptional: boolean;
  /** @nullable */
  requiredDocuments?: AdminStepDocumentDTO[] | null;
  slug: string;
  sortOrder: number;
  stepType: string;
  /** @nullable */
  translations: AdminStepTranslationDTO[] | null;
}
