/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface AskRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Language code (e.g. en, am) */
  language?: string;
  /**
   * User question
   * @minLength 1
   * @maxLength 10000
   */
  query: string;
  /** Optional conversation ID to continue */
  sessionId?: string;
  /** Custom conversation title */
  title?: string;
  /** Number of context chunks to retrieve */
  topK?: number;
}
