/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface BookmarkWithStepDTO {
  /** Creation timestamp */
  createdAt: string;
  /** Guide name */
  guideName: string;
  /** Bookmark ID */
  id: string;
  /** Bookmark note */
  note?: string;
  /** Step ID */
  stepId: string;
  /** Step title */
  stepTitle: string;
}
