/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { BusinessProfileResponseSocialLinks } from './businessProfileResponseSocialLinks';
import type { SectorRef } from './sectorRef';
import type { TagRef } from './tagRef';

export interface BusinessProfileResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Banner URL */
  bannerUrl?: string;
  /** Company email */
  companyEmail: string;
  /** Company name */
  companyName: string;
  /** Company phone number */
  companyPhoneNumber: string;
  /**
   * Creation timestamp
   * @nullable
   */
  createdAt: string | null;
  /** Business description */
  description?: string;
  /** Business profile identifier */
  id: string;
  /** Logo URL */
  logoUrl?: string;
  /** Physical address */
  physicalAddress?: string;
  /** Business region */
  region?: string;
  /** Registration date */
  registrationDate?: string;
  /** Business registration number */
  registrationNumber?: string;
  /** Business sector */
  sector?: SectorRef;
  /** Social media links */
  socialLinks: BusinessProfileResponseSocialLinks;
  /** Business lifecycle stage */
  stage?: string;
  /**
   * Associated tags
   * @nullable
   */
  tags: TagRef[] | null;
  /** TIN */
  taxIdentificationNumber?: string;
  /** Trade license number */
  tradeLicenseNumber?: string;
  /**
   * Last update timestamp
   * @nullable
   */
  updatedAt: string | null;
}
