/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CampaignTemplateSummaryResponse {
  /** Creation time */
  createdAt: string;
  /** Template description */
  description?: string;
  /** Template ID */
  id: string;
  /** Template name */
  name: string;
}
