/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CampaignTemplateInfoResponseDefaultContent } from './campaignTemplateInfoResponseDefaultContent';

export interface CampaignTemplateInfoResponse {
  /** Multi-channel content */
  defaultContent: CampaignTemplateInfoResponseDefaultContent;
  /** Template description */
  description?: string;
  /** Template ID */
  id: string;
  /** Template name */
  name: string;
}
