/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CampaignCreatedByResponse } from './campaignCreatedByResponse';
import type { CampaignDetailResponseTargetSegment } from './campaignDetailResponseTargetSegment';
import type { CampaignTemplateInfoResponse } from './campaignTemplateInfoResponse';

export interface CampaignDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Campaign template details */
  campaignTemplate?: CampaignTemplateInfoResponse;
  /** Campaign template ID */
  campaignTemplateId: string;
  /** Campaign type */
  campaignType: string;
  /** Creation time */
  createdAt: string;
  /** Creator account info */
  createdBy: CampaignCreatedByResponse;
  /** Campaign description */
  description?: string;
  /** Campaign ID */
  id: string;
  /** Campaign name */
  name: string;
  /** Target region */
  region?: string;
  /** Scheduled sending time */
  scheduledFor?: string;
  /**
   * Target sector IDs
   * @nullable
   */
  sectorIds: string[] | null;
  /** Actual sending time */
  sentAt?: string;
  /** Target business stage */
  stage?: string;
  /** Campaign status */
  status: string;
  /**
   * Target tag IDs
   * @nullable
   */
  tagIds: string[] | null;
  /** Segment filters or resolved recipients */
  targetSegment?: CampaignDetailResponseTargetSegment;
}
