/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CampaignDetailResponseCustomContent } from './campaignDetailResponseCustomContent';
import type { CampaignDetailResponseTargetSegment } from './campaignDetailResponseTargetSegment';

export interface CampaignDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Campaign type */
  campaignType: string;
  /** Creation time */
  createdAt: string;
  /** Creator account ID */
  createdBy: string;
  /** Override multi-channel content */
  customContent?: CampaignDetailResponseCustomContent;
  /** Override email subject */
  customSubject?: string;
  /** Campaign description */
  description?: string;
  /** Campaign ID */
  id: string;
  /** Campaign name */
  name: string;
  /** Scheduled sending time */
  scheduledFor?: string;
  /** Actual sending time */
  sentAt?: string;
  /** Campaign status */
  status: string;
  /** Segment filters or resolved recipients */
  targetSegment?: CampaignDetailResponseTargetSegment;
  /** Notification template ID */
  templateId: string;
}
