/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { GuideCardDTO } from './guideCardDTO';

export interface CategoryNodeDTO {
  /**
   * Nested subcategories
   * @nullable
   */
  children?: CategoryNodeDTO[] | null;
  /** Localized description */
  description?: string;
  /**
   * Guides in this category
   * @nullable
   */
  guides?: GuideCardDTO[] | null;
  /** Icon identifier */
  icon?: string;
  /** Category ID */
  id: string;
  /** Localized category name */
  name: string;
  /** Category slug */
  slug: string;
  /** Display order */
  sortOrder: number;
}
