/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ComplianceEntryResponse {
  accountId: string;
  businessProfileId: string;
  complianceType: string;
  expiryDate: string;
  id: string;
  issuedDate?: string;
  lastNotifiedAt?: string;
  referenceNumber?: string;
  reminderDaysBefore: number;
  source: string;
  status: string;
}
