/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CompletionStatsDTO {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Number of fully completed guides */
  completedGuides: number;
  /** Number of guides in progress */
  inProgressGuides: number;
  /** Stats period (e.g. monthly) */
  period: string;
  /** Total steps across all guides */
  totalStepsAll: number;
  /** Total steps completed across all guides */
  totalStepsCompleted: number;
}
