/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCampaignTemplateRequestDefaultContent } from './createCampaignTemplateRequestDefaultContent';

export interface CreateCampaignTemplateRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Multi-channel content (in_app, email, push, sms) */
  defaultContent: CreateCampaignTemplateRequestDefaultContent;
  /** Template description */
  description?: string;
  /**
   * Template name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
}
