/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CreateScheduledAlertRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  body: string;
  /** @nullable */
  channels: string[] | null;
  scheduledFor: string;
  templateSlug?: string;
  title: string;
}
