/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUploadIntentResponseBodyHeaders } from './createUploadIntentResponseBodyHeaders';

export interface CreateUploadIntentResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Upload intent expiry timestamp */
  expiresAt: string;
  /** Headers required by storage provider */
  headers?: CreateUploadIntentResponseBodyHeaders;
  /** Resolved object key for upload */
  key: string;
  /** HTTP method for upload */
  method: string;
  /** Direct upload URL */
  uploadUrl: string;
}
