/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateBusinessProfileRequestSocialLinks } from './createBusinessProfileRequestSocialLinks';

export interface CreateBusinessProfileRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Banner URL */
  bannerUrl?: string;
  /** Company email (auto-filled if omitted) */
  companyEmail?: string;
  /** Company name (auto-filled if omitted) */
  companyName?: string;
  /** Company phone (auto-filled if omitted) */
  companyPhoneNumber?: string;
  /** Business description */
  description?: string;
  /** Logo URL */
  logoUrl?: string;
  /** Physical address */
  physicalAddress?: string;
  /** Business region */
  region?: string;
  /** Registration date */
  registrationDate?: string;
  /** Business registration number */
  registrationNumber?: string;
  /** Sector slug (e.g., trade, manufacturing) */
  sectorSlug?: string;
  /** Social media links */
  socialLinks?: CreateBusinessProfileRequestSocialLinks;
  /** Business lifecycle stage */
  stage?: string;
  /**
   * Tag slugs (e.g., sole-proprietor, tax-vat)
   * @nullable
   */
  tagSlugs?: string[] | null;
  /** TIN */
  taxIdentificationNumber?: string;
  /** Trade license number */
  tradeLicenseNumber?: string;
}
