/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type CreateCommunityThreadBody = {
  /** Pre-uploaded attachment IDs (comma-separated) */
  attachmentIds?: Blob | string;
  /** Thread description */
  description: Blob | string;
  /** Initial post content */
  initialPostContent: Blob | string;
  /** Parent thread ID for sub-threads */
  parentThreadId?: Blob | string;
  /** Sector IDs (comma-separated) */
  sectorIds?: Blob | string;
  /** Thread slug */
  slug: Blob | string;
  /** Tag IDs (comma-separated) */
  tagIds?: Blob | string;
  /** Thread title */
  title: Blob | string;
};
