/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type CreateCommunityThreadBody = {
  /** Category ID */
  categoryId: Blob | string;
  /** Thread description */
  description: Blob | string;
  /** Optional attachment file */
  file?: Blob;
  /** Initial post content */
  initialPostContent: Blob | string;
  /** Parent thread ID for sub-threads */
  parentThreadId?: Blob | string;
  /** Thread slug */
  slug: Blob | string;
  /** Thread title */
  title: Blob | string;
};
