/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CreateStepDependency {
  /** Dependency type */
  dependencyType: string;
  /** Required step ID */
  requiredStepId: string;
}
