/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCampaignRequestTargetSegment } from './createCampaignRequestTargetSegment';

export interface CreateCampaignRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Campaign template ID */
  campaignTemplateId: string;
  /** Campaign type (broadcast or segmented) */
  campaignType: string;
  /** Campaign description */
  description?: string;
  /**
   * Campaign name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Target region */
  region?: string;
  /** Scheduled sending time */
  scheduledFor?: string;
  /**
   * Target sector IDs
   * @nullable
   */
  sectorIds?: string[] | null;
  /** Target business stage */
  stage?: string;
  /**
   * Target tag IDs
   * @nullable
   */
  tagIds?: string[] | null;
  /** Segment filters for segmented campaigns */
  targetSegment?: CreateCampaignRequestTargetSegment;
}
