/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateStepCondition } from './createStepCondition';
import type { CreateStepDependency } from './createStepDependency';
import type { CreateStepTranslation } from './createStepTranslation';

export interface CreateStepRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Visibility conditions
   * @nullable
   */
  conditions?: CreateStepCondition[] | null;
  /**
   * Step dependencies
   * @nullable
   */
  dependencies?: CreateStepDependency[] | null;
  /** Difficulty level (1-5) */
  difficultyLevel?: number;
  /** When step becomes active */
  effectiveDate?: string;
  /** Estimated time in minutes */
  estimatedTime?: number;
  /** When step expires */
  expiryDate?: string;
  /** Estimated fee */
  feeEstimate?: number;
  /** Parent guide ID */
  guideId: string;
  /** Whether step can be skipped */
  isOptional: boolean;
  /**
   * Step slug
   * @minLength 1
   * @maxLength 100
   */
  slug: string;
  /** Display order */
  sortOrder: number;
  /** Step type */
  stepType: string;
  /**
   * Localized translations
   * @nullable
   */
  translations?: CreateStepTranslation[] | null;
}
