/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGuideCondition } from './createGuideCondition';
import type { CreateGuideTranslation } from './createGuideTranslation';

export interface CreateGuideRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Parent category ID */
  categoryId: string;
  /**
   * Visibility conditions
   * @nullable
   */
  conditions?: CreateGuideCondition[] | null;
  /**
   * Icon identifier
   * @maxLength 50
   */
  icon?: string;
  /**
   * Guide slug
   * @minLength 1
   * @maxLength 100
   */
  slug: string;
  /** Display order */
  sortOrder: number;
  /**
   * Localized translations
   * @nullable
   */
  translations?: CreateGuideTranslation[] | null;
}
