/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCampaignRequestCustomContent } from './createCampaignRequestCustomContent';
import type { CreateCampaignRequestTargetSegment } from './createCampaignRequestTargetSegment';

export interface CreateCampaignRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Campaign type (broadcast or segmented) */
  campaignType: string;
  /** Override multi-channel content */
  customContent?: CreateCampaignRequestCustomContent;
  /** Override email subject */
  customSubject?: string;
  /** Campaign description */
  description?: string;
  /**
   * Campaign name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Scheduled sending time */
  scheduledFor?: string;
  /** Segment filters for segmented campaigns */
  targetSegment?: CreateCampaignRequestTargetSegment;
  /** Notification template ID */
  templateId: string;
}
