/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTemplateGroupRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Category ID */
  categoryId: string;
  /** Default language code */
  defaultLanguage: string;
  /** Group description */
  description?: string;
  /** Template format */
  format: string;
  /**
   * Group name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Requires authentication */
  requiresAuth: boolean;
  /**
   * URL-friendly identifier
   * @minLength 1
   * @maxLength 200
   */
  slug: string;
  /** Display order */
  sortOrder: number;
  /** Tier access level */
  tierAccess: string;
}
