/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTemplateRequestDefaultContent } from './createTemplateRequestDefaultContent';
import type { CreateTemplateRequestVariablesSchema } from './createTemplateRequestVariablesSchema';

export interface CreateTemplateRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Notification category */
  category: string;
  /** Multi-channel content */
  defaultContent: CreateTemplateRequestDefaultContent;
  /** Default TTL in seconds */
  defaultTtl?: number;
  /** Template description */
  description?: string;
  /**
   * Template name
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  /** Notification type */
  notificationType: string;
  /** Default priority */
  priority: number;
  /** Template variable schema */
  variablesSchema?: CreateTemplateRequestVariablesSchema;
}
