/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CreateUploadIntentRequestMetadata } from './createUploadIntentRequestMetadata';

export interface CreateUploadIntentRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Optional client batch identifier */
  batchId?: string;
  /**
   * Expected MIME content type
   * @minLength 1
   * @maxLength 255
   */
  contentType: string;
  /**
   * Optional upload intent expiration in seconds
   * @minimum 60
   * @maximum 3600
   */
  expiresInSec?: number;
  /** Optional metadata sent as upload headers */
  metadata?: CreateUploadIntentRequestMetadata;
  /** Optional object key. If omitted, server generates one */
  storageKey?: string;
}
