/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CreateThreadResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Initial post ID */
  postId: string;
  /** Created thread ID */
  threadId: string;
}
