/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface CreateStepCondition {
  /**
   * Condition type
   * @minLength 1
   */
  conditionType: string;
  /** Condition value */
  conditionValue: unknown;
  /** Whether to invert the condition */
  isInverse: boolean;
  /**
   * Comparison operator
   * @minLength 1
   */
  operator: string;
}
