/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface DownloadLogResponse {
  /** Account ID */
  accountId: string;
  /** Download timestamp */
  downloadedAt: string;
  /** Group ID */
  groupId: string;
  /** Group name */
  groupName: string;
  /** Download log ID */
  id: string;
  /** Template ID */
  templateId: string;
  /** Template title */
  templateTitle: string;
}
