/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface FinalizeUploadResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Alias of ingestion document identifier */
  documentId: string;
  /** Outbox event identifier */
  eventId: string;
  /** Ingestion document identifier */
  ingestionId: string;
  /** Initial ingestion state */
  state: string;
}
