/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AccountDTO } from './accountDTO';
import type { PermissionDTO } from './permissionDTO';
import type { RoleDTO } from './roleDTO';
import type { UserDTO } from './userDTO';

export interface GetCurrentUserResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Current user account */
  account: AccountDTO;
  /**
   * Current user permissions
   * @nullable
   */
  permissions: PermissionDTO[] | null;
  /**
   * Current user roles
   * @nullable
   */
  roles: RoleDTO[] | null;
  /** Current user */
  user: UserDTO;
}
