/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationDTO } from './conversationDTO';
import type { MessageDTO } from './messageDTO';

export interface GetConversationOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @nullable */
  messages: MessageDTO[] | null;
  session: ConversationDTO;
  totalMsgs: number;
}
