/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { SubscriptionResponse } from './subscriptionResponse';

export interface GetMySubscriptionResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Current subscription, null if none */
  data?: SubscriptionResponse;
}
