/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { GuideProgressSummaryDTO } from './guideProgressSummaryDTO';
import type { PersonalizedStepDTO } from './personalizedStepDTO';

export interface GetPersonalizedGuideResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Localized description */
  description?: string;
  /** Guide ID */
  id: string;
  /** Localized guide name */
  name: string;
  /** User progress summary */
  progress?: GuideProgressSummaryDTO;
  /** Guide slug */
  slug: string;
  /**
   * Guide steps with user progress
   * @nullable
   */
  steps: PersonalizedStepDTO[] | null;
}
