/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { PermissionDTO } from './permissionDTO';
import type { RoleDTO } from './roleDTO';

export interface GetRoleResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Role permissions
   * @nullable
   */
  permissions: PermissionDTO[] | null;
  /** Role details */
  role: RoleDTO;
}
