/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserGrowthPeriod } from './getUserGrowthPeriod';

export type GetUserGrowthParams = {
/**
 * Grouping period: monthly, quarterly, yearly
 */
period?: GetUserGrowthPeriod;
};
