/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type GetUserGrowthPeriod = typeof GetUserGrowthPeriod[keyof typeof GetUserGrowthPeriod];


export const GetUserGrowthPeriod = {
  monthly: 'monthly',
  quarterly: 'quarterly',
  yearly: 'yearly',
} as const;
