/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface GuideProgressSummaryDTO {
  /** Completed steps count */
  completedSteps: number;
  /** In-progress steps count */
  inProgressSteps: number;
  /** Skipped steps count */
  skippedSteps: number;
  /** Total number of steps */
  totalSteps: number;
}
