/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface GuideCardDTO {
  /** Parent category ID */
  categoryId: string;
  /** Localized description */
  description?: string;
  /** Icon identifier */
  icon?: string;
  /** Guide ID */
  id: string;
  /** Localized guide name */
  name: string;
  /** Guide slug */
  slug: string;
}
