/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface HistoryEntryResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Action URL */
  actionUrl?: string;
  /** Delivery channel */
  channel: string;
  /** Time the notification was clicked */
  clickedAt?: string;
  /** Notification content */
  content: string;
  /** Time the notification was delivered */
  deliveredAt?: string;
  /** Current delivery status */
  deliveryStatus: string;
  /** Failure reason if delivery failed */
  failureReason?: string;
  /** History entry ID */
  id: string;
  /** Notification type */
  notificationType: string;
  /** Time the notification was read */
  readAt?: string;
  /** Time the notification was sent */
  sentAt: string;
  /** Notification title */
  title: string;
}
