/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface IngestionStatusProjectionResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Account identifier */
  accountId: string;
  /** Number of chunks failed */
  chunksFailedCount: number;
  /** Number of chunks processed */
  chunksProcessedCount: number;
  /** Completion timestamp if terminal */
  completedAt?: string;
  /** Current ingestion stage */
  currentStage: string;
  /** Document identifier */
  documentId: string;
  /** Monotonic event sequence number */
  eventSequence: number;
  /** Whether this is a terminal stage */
  isTerminal: boolean;
  /** Last error message if failed */
  lastError?: string;
  /** Ingestion start timestamp */
  startedAt: string;
  /** Last update timestamp */
  updatedAt: string;
  /** User identifier */
  userId: string;
}
