/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface InitiatePaymentResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Amount in minor units */
  amount: number;
  /** Chapa checkout URL */
  checkoutUrl: string;
  /** Currency code */
  currency: string;
  /** Checkout URL expiration (Unix timestamp) */
  expiresAt: number;
  /** Billing period */
  period: string;
  /** Plan name */
  planName: string;
  /** Transaction reference */
  txRef: string;
}
