/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { InteractiveFormDetailResponseFormLayout } from './interactiveFormDetailResponseFormLayout';

export interface InteractiveFormDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Form description */
  description?: string;
  /** Form layout JSON */
  formLayout: InteractiveFormDetailResponseFormLayout;
  /** Form ID */
  id: string;
  /** Active flag */
  isActive: boolean;
  /** Form name */
  name: string;
  /** Template ID */
  templateId: string;
  /** Version number */
  version: number;
}
