/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type LibraryListTemplateGroupsParams = {
/**
 * Filter by category ID
 */
categoryId?: string;
/**
 * Filter by format (pdf, docx, xlsx, interactive_form)
 */
format?: string;
/**
 * Search by name or description
 */
search?: string;
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 * @maximum 100
 */
pageSize?: number;
};
