/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface LibraryCreateUploadIntentRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * MIME type
   * @minLength 1
   */
  contentType: string;
  /** Template description */
  description?: string;
  /**
   * Original filename
   * @minLength 1
   */
  fileName: string;
  /** File size in bytes */
  fileSize: number;
  /**
   * Language code
   * @minLength 2
   * @maxLength 10
   */
  language: string;
  /**
   * Template title
   * @minLength 1
   * @maxLength 200
   */
  title: string;
}
