/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type LibraryUpdateTemplateBody = {
  /** Template description */
  description: Blob | string;
  /** Template file (optional) */
  file: Blob;
  /** Active flag (true/false) */
  isActive: Blob | string;
  /** Template title */
  title: Blob | string;
};
