/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface LibraryTemplateDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** MIME type */
  contentType: string;
  /** Template description */
  description?: string;
  /** File size in bytes */
  fileSize: number;
  /** File URL */
  fileUrl?: string;
  /** Group ID */
  groupId: string;
  /** Template ID */
  id: string;
  /** Active flag */
  isActive: boolean;
  /** Language code */
  language: string;
  /** Template title */
  title: string;
  /** Version number */
  version: number;
}
