/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { LibraryCreateUploadIntentOutputBodyHeaders } from './libraryCreateUploadIntentOutputBodyHeaders';

export interface LibraryCreateUploadIntentOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Upload URL expiry time */
  expiresAt: string;
  /** Storage key for the file */
  fileKey: string;
  /** Required upload headers */
  headers?: LibraryCreateUploadIntentOutputBodyHeaders;
  /** HTTP method for upload */
  method: string;
  /** Direct upload URL */
  uploadUrl: string;
}
