/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AdminGuideStepDTO } from './adminGuideStepDTO';

export interface ListGuideStepsAdminResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  page: number;
  pageSize: number;
  /** @nullable */
  steps: AdminGuideStepDTO[] | null;
  totalItems: number;
  totalPages: number;
}
