/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type ListGuidesAdminParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
pageSize?: number;
/**
 * Search keyword
 */
search?: string;
/**
 * Sort columns
 * @nullable
 */
sortBy?: string[] | null;
/**
 * Sort order (asc, desc)
 * @nullable
 */
sortOrder?: string[] | null;
/**
 * Language locale (en, am)
 */
locale?: string;
};
