/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { ReportWithContentDTO } from './reportWithContentDTO';

export interface ListPostReportsResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Current page */
  page: number;
  /** Page size */
  pageSize: number;
  /**
   * Post report list
   * @nullable
   */
  reports: ReportWithContentDTO[] | null;
  /** Total count */
  total: number;
  /** Total pages */
  totalPages: number;
}
