/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateSummaryResponse } from './templateSummaryResponse';

export interface ListTemplatesResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Template list
   * @nullable
   */
  data: TemplateSummaryResponse[] | null;
  /** Current page */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total count */
  total: number;
  /** Total pages */
  totalPages: number;
}
