/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type ListAdminsParams = {
/**
 * Search by email, username, or name
 */
search?: string;
/**
 * Filter by account status
 */
status?: string;
/**
 * Filter by role ID
 */
roleId?: string;
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
pageSize?: number;
};
