/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type ListPermissionsParams = {
/**
 * Filter by module
 */
module?: string;
/**
 * Filter by permission code
 * @nullable
 */
code?: string[] | null;
};
