/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { RoleDTO } from './roleDTO';

export interface ListRolesResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * List of roles
   * @nullable
   */
  roles: RoleDTO[] | null;
}
