/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { CitationDTO } from './citationDTO';
import type { UsageDTO } from './usageDTO';

export interface MessageDTO {
  /** @nullable */
  citations?: CitationDTO[] | null;
  content: string;
  createdAt: string;
  id: string;
  role: string;
  usage?: UsageDTO;
}
