/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface NotificationSummaryResponse {
  /** Delivery channel */
  channel: string;
  /** Notification content */
  content: string;
  /** Time the notification was delivered */
  deliveredAt?: string;
  /** Notification type */
  notificationType: string;
  /** Time the notification was read */
  readAt?: string;
  /** Time the notification was sent */
  sentAt: string;
  /** Notification title */
  title: string;
}
