/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface PostDTO {
  /** Attachment type */
  attachmentType?: string;
  /** Attachment URL */
  attachmentUrl?: string;
  /** Author account ID */
  authorId: string;
  /** Post content */
  content: string;
  /** Created timestamp */
  createdAt?: string;
  /** Edit count */
  editCount: number;
  /** Edited timestamp */
  editedAt?: string;
  /** Post ID */
  id: string;
  /** Pinned flag */
  isPinned: boolean;
  /** Solution flag */
  isSolution: boolean;
  /** Parent post ID */
  parentPostId?: string;
  /** Thread ID */
  threadId: string;
  /** Updated timestamp */
  updatedAt?: string;
  /** Upvote count */
  upvoteCount: number;
}
