/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentDTO } from './attachmentDTO';

export interface PostDTO {
  /**
   * Post attachments
   * @nullable
   */
  attachments?: AttachmentDTO[] | null;
  /** Author avatar URL */
  authorAvatarUrl?: string;
  /** Author display name */
  authorDisplayName: string;
  /** Author account ID */
  authorId: string;
  /** Author username */
  authorUsername?: string;
  /** Post content */
  content: string;
  /** Created timestamp */
  createdAt?: string;
  /** Edit count */
  editCount: number;
  /** Edited timestamp */
  editedAt?: string;
  /** Post ID */
  id: string;
  /** Pinned flag */
  isPinned: boolean;
  /** Solution flag */
  isSolution: boolean;
  /** Parent post ID */
  parentPostId?: string;
  /** Thread ID */
  threadId: string;
  /** Updated timestamp */
  updatedAt?: string;
  /** Upvote count */
  upvoteCount: number;
}
