/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface PostContentDTO {
  /** Author first name */
  authorFirstName: string;
  /** Author account ID */
  authorId: string;
  /** Author last name */
  authorLastName: string;
  /** Post content */
  content: string;
  /** Created timestamp */
  createdAt: string;
  /** Post ID */
  id: string;
  /** Is solution */
  isSolution: boolean;
  /** Parent post ID */
  parentPostId?: string;
  /** Thread ID */
  threadId: string;
  /** Thread slug */
  threadSlug?: string;
  /** Thread title */
  threadTitle?: string;
  /** Updated timestamp */
  updatedAt?: string;
}
