/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface PreferenceResponse {
  /** Channel */
  channel: string;
  /** Whether enabled */
  isEnabled: boolean;
  /** Notification type */
  notificationType: string;
  /** Quiet hours end time */
  quietHoursEnd?: string;
  /** Quiet hours start time */
  quietHoursStart?: string;
}
