/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface QueueStatusResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Number of cancelled notifications */
  cancelled: number;
  /** Number of delivered notifications */
  delivered: number;
  /** Number of failed notifications */
  failed: number;
  /** Number of pending notifications */
  pending: number;
  /** Number of processing notifications */
  processing: number;
}
