/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Email address
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * First name
   * @minLength 1
   * @maxLength 100
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   * @maxLength 100
   */
  lastName: string;
  /**
   * Password (min 8 chars, 1 uppercase, 1 lowercase, 1 digit)
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
