/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterDeviceRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** App version */
  appVersion?: string;
  /** Device model */
  deviceModel?: string;
  /** Device name */
  deviceName?: string;
  /** Device token */
  deviceToken: string;
  /** Device type */
  deviceType: string;
  /** OS version */
  osVersion?: string;
  /** Push notification token */
  pushToken?: string;
}
