/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { AccountDTO } from './accountDTO';
import type { UserDTO } from './userDTO';

export interface RegisterResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** JWT access token */
  accessToken: string;
  /** Created account */
  account: AccountDTO;
  /** When the access token expires */
  expiresAt: string;
  /** Created user */
  user: UserDTO;
}
