/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type ReplyCommunityPostBody = {
  /** Post content */
  content: Blob | string;
  /** Optional attachment file */
  file?: Blob;
};
