/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ReportDTO {
  /** Admin note */
  adminNote?: string;
  /** Created timestamp */
  createdAt: string;
  /** Report ID */
  id: string;
  /** Post ID */
  postId?: string;
  /** Report reason */
  reason: string;
  /** Reported account ID */
  reportedAccountId?: string;
  /** Reporter first name */
  reporterFirstName: string;
  /** Reporter account ID */
  reporterId: string;
  /** Reporter last name */
  reporterLastName: string;
  /** Resolved timestamp */
  resolvedAt?: string;
  /** Resolved by account ID */
  resolvedBy?: string;
  /** Report status */
  status: string;
  /** Thread ID */
  threadId?: string;
}
