/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ReportStatsResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Pending reports */
  pending: number;
  /** Resolved reports */
  resolved: number;
  /** Total reports */
  total: number;
  /** Percentage change vs previous period */
  trendPercent: number;
}
