/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ScheduledAlertResponse {
  body: string;
  cancelledAt?: string;
  /** @nullable */
  channels: string[] | null;
  /** @nullable */
  createdAt: string | null;
  id: string;
  rescheduledFrom?: string;
  scheduledFor: string;
  sentAt?: string;
  status: string;
  templateSlug?: string;
  title: string;
}
