/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export type SetStepTranslationsTranslationMode = typeof SetStepTranslationsTranslationMode[keyof typeof SetStepTranslationsTranslationMode];


export const SetStepTranslationsTranslationMode = {
  merge: 'merge',
  replace: 'replace',
} as const;
