/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { SetStepTranslationsTranslationMode } from './setStepTranslationsTranslationMode';

export type SetStepTranslationsParams = {
/**
 * Translation mode: 'merge' to upsert without deleting, absent for full replacement
 */
translationMode?: SetStepTranslationsTranslationMode;
};
