/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface SubscriptionResponse {
  /** Amount in minor units */
  amount: number;
  /** Currency code */
  currency: string;
  /** Period end */
  currentPeriodEnd: string;
  /** Period start */
  currentPeriodStart: string;
  /** Subscription ID */
  id: string;
  /** Plan name */
  planName: string;
  /** Billing period */
  planPeriod: string;
  /** Number of renewals */
  renewalCount: number;
  /** Subscription status */
  status: string;
}
