/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface TagRef {
  /** Tag group */
  group: string;
  /** Tag identifier */
  id: string;
  /** Whether the tag allows multiple selections */
  isMultiSelect: boolean;
  /** Tag slug */
  slug: string;
}
