/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateItem } from './templateItem';

export interface TemplateGroupDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Category ID */
  categoryId: string;
  /** Creation time */
  createdAt: string;
  /** Creator account ID */
  createdBy: string;
  /** Default language code */
  defaultLanguage: string;
  /** Group description */
  description?: string;
  /** Total downloads */
  downloadCount: number;
  /** Template format */
  format: string;
  /** Group ID */
  id: string;
  /** Active flag */
  isActive: boolean;
  /** Group name */
  name: string;
  /** Requires authentication */
  requiresAuth: boolean;
  /** Group slug */
  slug: string;
  /** Display order */
  sortOrder: number;
  /**
   * Language variants
   * @nullable
   */
  templates?: TemplateItem[] | null;
  /** Thumbnail URL */
  thumbnailUrl?: string;
  /** Tier access level */
  tierAccess: string;
}
