/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateDetailResponseDefaultContent } from './templateDetailResponseDefaultContent';
import type { TemplateDetailResponseVariablesSchema } from './templateDetailResponseVariablesSchema';
import type { TranslationResponse } from './translationResponse';

export interface TemplateDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Multi-channel content */
  defaultContent: TemplateDetailResponseDefaultContent;
  /** Default TTL in seconds */
  defaultTtl?: number;
  /** Template description */
  description?: string;
  /** Template ID */
  id: string;
  /** Whether template is system-managed */
  isSystemManaged: boolean;
  /** Template name */
  name: string;
  /** Notification type */
  notificationType: string;
  /** Default priority */
  priority: number;
  /** Template group */
  templateGroup: string;
  /**
   * Template translations
   * @nullable
   */
  translations?: TranslationResponse[] | null;
  /** Template variable schema */
  variablesSchema?: TemplateDetailResponseVariablesSchema;
}
