/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ThreadContentDTO {
  /** Author first name */
  authorFirstName: string;
  /** Author account ID */
  authorId: string;
  /** Author last name */
  authorLastName: string;
  /** Created timestamp */
  createdAt: string;
  /** Thread description */
  description?: string;
  /** Thread ID */
  id: string;
  /** Reply count */
  replyCount: number;
  /**
   * Sector IDs
   * @nullable
   */
  sectorIds: string[] | null;
  /** Thread slug */
  slug: string;
  /** Thread status */
  status: string;
  /**
   * Tag IDs
   * @nullable
   */
  tagIds: string[] | null;
  /** Thread title */
  title: string;
  /** Updated timestamp */
  updatedAt?: string;
  /** View count */
  viewCount: number;
}
