/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ThreadDTO {
  /** Author avatar URL */
  authorAvatarUrl?: string;
  /** Author display name */
  authorDisplayName: string;
  /** Author account ID */
  authorId: string;
  /** Author username */
  authorUsername?: string;
  /** Category ID */
  categoryId: string;
  /** Created timestamp */
  createdAt?: string;
  /** Thread description */
  description?: string;
  /** Thread ID */
  id: string;
  /** Pinned flag */
  isPinned: boolean;
  /** Last activity timestamp */
  lastActivityAt?: string;
  /** Parent thread ID for sub-threads */
  parentThreadId?: string;
  /** Reply count */
  replyCount: number;
  /** Share count */
  shareCount: number;
  /** Thread slug */
  slug: string;
  /** Thread status */
  status: string;
  /** Thread title */
  title: string;
  /** Updated timestamp */
  updatedAt?: string;
  /** View count */
  viewCount: number;
}
