/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ThreadDTO {
  /** Author avatar URL */
  authorAvatarUrl?: string;
  /** Author display name */
  authorDisplayName: string;
  /** Author account ID */
  authorId: string;
  /** Author username */
  authorUsername?: string;
  /** Created timestamp */
  createdAt?: string;
  /** Thread description */
  description?: string;
  /** Whether thread has an accepted solution */
  hasSolution: boolean;
  /** Thread ID */
  id: string;
  /** Whether current user follows this thread */
  isFollowed: boolean;
  /** Whether current user has muted this thread */
  isMuted: boolean;
  /** Pinned flag */
  isPinned: boolean;
  /** Last activity timestamp */
  lastActivityAt?: string;
  /** Parent thread ID for sub-threads */
  parentThreadId?: string;
  /** Reply count */
  replyCount: number;
  /**
   * Sector IDs
   * @nullable
   */
  sectorIds: string[] | null;
  /** Share count */
  shareCount: number;
  /** Thread slug */
  slug: string;
  /** Thread status */
  status: string;
  /**
   * Tag IDs
   * @nullable
   */
  tagIds: string[] | null;
  /** Thread title */
  title: string;
  /** Number of unread posts/replies */
  unreadCount: number;
  /** Updated timestamp */
  updatedAt?: string;
  /** View count */
  viewCount: number;
}
