/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface ThreadBlockedUserDTO {
  /** Blocked by account ID */
  blockedBy: string;
  /** Blocked by first name */
  blockedByFirstName?: string;
  /** Blocked by last name */
  blockedByLastName?: string;
  /** Blocked user email */
  blockedUserEmail?: string;
  /** Blocked user first name */
  blockedUserFirstName?: string;
  /** Blocked user account ID */
  blockedUserId: string;
  /** Blocked user last name */
  blockedUserLastName?: string;
  /** Created timestamp */
  createdAt: string;
  /** Reason for blocking */
  reason?: string;
  /** Thread ID */
  threadId: string;
  /** Thread slug */
  threadSlug?: string;
  /** Thread title */
  threadTitle?: string;
}
