/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { TranslationResponseContent } from './translationResponseContent';

export interface TranslationResponse {
  /** Multi-channel localized content */
  content: TranslationResponseContent;
  /** Translation ID */
  id: string;
  /** Language code */
  language: string;
  /** Localized subject */
  subject: string;
}
