/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateBusinessProfileRequestSocialLinks } from './updateBusinessProfileRequestSocialLinks';

export interface UpdateBusinessProfileRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Banner URL */
  bannerUrl?: string;
  /** Company email */
  companyEmail?: string;
  /** Company name */
  companyName?: string;
  /** Company phone */
  companyPhoneNumber?: string;
  /** Business description */
  description?: string;
  /** Logo URL */
  logoUrl?: string;
  /** Physical address */
  physicalAddress?: string;
  /** Business region */
  region?: string;
  /** Registration date */
  registrationDate?: string;
  /** Business registration number */
  registrationNumber?: string;
  /** Sector slug */
  sectorSlug?: string;
  /** Social media links */
  socialLinks?: UpdateBusinessProfileRequestSocialLinks;
  /** Business lifecycle stage */
  stage?: string;
  /**
   * Tag slugs
   * @nullable
   */
  tagSlugs?: string[] | null;
  /** TIN */
  taxIdentificationNumber?: string;
  /** Trade license number */
  tradeLicenseNumber?: string;
}
