/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTranslationRequestContent } from './updateTranslationRequestContent';

export interface UpdateTranslationRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Multi-channel localized content */
  content?: UpdateTranslationRequestContent;
  /**
   * Localized subject
   * @maxLength 500
   */
  subject?: string;
}
