/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateTemplateRequestDefaultContent } from './updateTemplateRequestDefaultContent';
import type { UpdateTemplateRequestVariablesSchema } from './updateTemplateRequestVariablesSchema';

export interface UpdateTemplateRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Multi-channel content */
  defaultContent?: UpdateTemplateRequestDefaultContent;
  /** Default TTL in seconds */
  defaultTtl?: number;
  /** Template description */
  description?: string;
  /**
   * Template name
   * @maxLength 200
   */
  name?: string;
  /** Default priority */
  priority?: number;
  /** Template variable schema */
  variablesSchema?: UpdateTemplateRequestVariablesSchema;
}
