/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTagRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Amharic description */
  descAm?: string;
  /** English description */
  descEn?: string;
  /** Tag group */
  group?: string;
  /**
   * Icon identifier
   * @maxLength 50
   */
  icon?: string;
  /** Whether tag is active */
  isActive?: boolean;
  /** Whether multiple tags from this group can be selected together */
  isMultiSelect?: boolean;
  /**
   * Amharic name
   * @maxLength 200
   */
  nameAm?: string;
  /**
   * English name
   * @maxLength 200
   */
  nameEn?: string;
  /**
   * Tag slug
   * @maxLength 100
   */
  slug?: string;
  /** Display order */
  sortOrder?: number;
}
