/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateThreadReportStatusRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Admin note */
  adminNote?: string;
  /** Status: pending, under_review, resolved, dismissed */
  status: string;
}
