/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateStepCondition } from './updateStepCondition';
import type { UpdateStepDependency } from './updateStepDependency';
import type { UpdateStepDocument } from './updateStepDocument';
import type { UpdateStepRequestTranslationMode } from './updateStepRequestTranslationMode';
import type { UpdateStepTranslation } from './updateStepTranslation';

export interface UpdateStepRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Visibility conditions
   * @nullable
   */
  conditions?: UpdateStepCondition[] | null;
  /**
   * Step dependencies
   * @nullable
   */
  dependencies?: UpdateStepDependency[] | null;
  /** Difficulty level (1-5) */
  difficultyLevel?: number;
  /** When step becomes active */
  effectiveDate?: string;
  /** Estimated time in minutes */
  estimatedTime?: number;
  /** When step expires */
  expiryDate?: string;
  /** Estimated fee */
  feeEstimate?: number;
  /** Whether step can be skipped */
  isOptional?: boolean;
  /**
   * Required documents for this step
   * @nullable
   */
  requiredDocuments?: UpdateStepDocument[] | null;
  /**
   * Step slug
   * @maxLength 100
   */
  slug?: string;
  /** Display order */
  sortOrder?: number;
  /** Step type */
  stepType?: string;
  /** Translation mode: 'merge' to upsert without deleting, anything else or absent for full replacement */
  translationMode?: UpdateStepRequestTranslationMode;
  /**
   * Localized translations
   * @nullable
   */
  translations?: UpdateStepTranslation[] | null;
}
