/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateInteractiveFormRequestFormLayout } from './updateInteractiveFormRequestFormLayout';

export interface UpdateInteractiveFormRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Form description */
  description?: string;
  /** Form layout JSON */
  formLayout?: UpdateInteractiveFormRequestFormLayout;
  /** Form name */
  name?: string;
}
