/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCampaignRequestTargetSegment } from './updateCampaignRequestTargetSegment';

export interface UpdateCampaignRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Campaign description */
  description?: string;
  /**
   * Campaign name
   * @maxLength 200
   */
  name?: string;
  /** Scheduled sending time */
  scheduledFor?: string;
  /** Segment filters for segmented campaigns */
  targetSegment?: UpdateCampaignRequestTargetSegment;
}
