/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCampaignTemplateRequestDefaultContent } from './updateCampaignTemplateRequestDefaultContent';

export interface UpdateCampaignTemplateRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Multi-channel content */
  defaultContent?: UpdateCampaignTemplateRequestDefaultContent;
  /** Template description */
  description?: string;
  /**
   * Template name
   * @maxLength 200
   */
  name?: string;
}
