/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Translation mode: 'merge' to upsert without deleting, anything else or absent for full replacement
 */
export type UpdateGuideRequestTranslationMode = typeof UpdateGuideRequestTranslationMode[keyof typeof UpdateGuideRequestTranslationMode];


export const UpdateGuideRequestTranslationMode = {
  merge: 'merge',
  replace: 'replace',
} as const;
