/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { ReportDTO } from './reportDTO';

export interface UpdateThreadReportStatusResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Updated report */
  report: ReportDTO;
}
