/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUserProfileRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Bio */
  bio?: string;
  /**
   * First name
   * @minLength 1
   * @maxLength 100
   */
  firstName: string;
  /**
   * Last name
   * @minLength 1
   * @maxLength 100
   */
  lastName: string;
}
