/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateGuideCondition } from './updateGuideCondition';
import type { UpdateGuideRequestTranslationMode } from './updateGuideRequestTranslationMode';
import type { UpdateGuideTranslation } from './updateGuideTranslation';

export interface UpdateGuideRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Visibility conditions
   * @nullable
   */
  conditions?: UpdateGuideCondition[] | null;
  /**
   * Icon identifier
   * @maxLength 50
   */
  icon?: string;
  /**
   * Target sector IDs
   * @nullable
   */
  sectorIds?: string[] | null;
  /**
   * Guide slug
   * @maxLength 100
   */
  slug?: string;
  /** Display order */
  sortOrder?: number;
  /**
   * Target tag IDs
   * @nullable
   */
  tagIds?: string[] | null;
  /** Translation mode: 'merge' to upsert without deleting, anything else or absent for full replacement */
  translationMode?: UpdateGuideRequestTranslationMode;
  /**
   * Localized translations
   * @nullable
   */
  translations?: UpdateGuideTranslation[] | null;
}
