/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCategoryCondition } from './updateCategoryCondition';
import type { UpdateCategoryTranslation } from './updateCategoryTranslation';

export interface UpdateCategoryRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
   * Visibility conditions
   * @nullable
   */
  conditions?: UpdateCategoryCondition[] | null;
  /**
   * Icon identifier
   * @maxLength 50
   */
  icon?: string;
  /** Parent category ID */
  parentId?: string;
  /**
   * Category slug
   * @maxLength 100
   */
  slug?: string;
  /** Display order */
  sortOrder?: number;
  /**
   * Localized translations
   * @nullable
   */
  translations?: UpdateCategoryTranslation[] | null;
}
