/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTemplateGroupRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Category ID */
  categoryId?: string;
  /** Default language code */
  defaultLanguage?: string;
  /** Group description */
  description?: string;
  /** Template format */
  format?: string;
  /** Active flag */
  isActive?: boolean;
  /** Group name */
  name?: string;
  /** Requires authentication */
  requiresAuth?: boolean;
  /** Group slug */
  slug?: string;
  /** Display order */
  sortOrder?: number;
  /** Tier access level */
  tierAccess?: string;
}
