/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */
import type { LanguageVariantResponse } from './languageVariantResponse';

export interface UserTemplateGroupDetailResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Category ID */
  categoryId: string;
  /** Default language code */
  defaultLanguage: string;
  /** Total downloads */
  downloadCount: number;
  /** Template format */
  format: string;
  /** Group ID */
  id: string;
  /**
   * Available language variants
   * @nullable
   */
  languages: LanguageVariantResponse[] | null;
  /** Group name */
  name: string;
  /** Requires authentication */
  requiresAuth: boolean;
  /** Group slug */
  slug: string;
  /** Display order */
  sortOrder: number;
  /** Thumbnail URL */
  thumbnailUrl?: string;
  /** Tier access level */
  tierAccess: string;
}
