/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UserContentDTO {
  /** User email */
  email: string;
  /** First name */
  firstName: string;
  /** User ID */
  id: string;
  /** Last name */
  lastName: string;
  /** Thread ID */
  threadId?: string;
  /** Thread title */
  threadTitle?: string;
}
