/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface UserDTO {
  /** User's biography */
  bio?: string;
  /** User's first name */
  firstName: string;
  /** User's unique identifier */
  id: string;
  /** URL to user's profile image */
  imageUrl?: string;
  /** User's last name */
  lastName: string;
}
