/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Adisu Backend API
 * Backend API for the Adisu platform
 * OpenAPI spec version: 1.0.0
 */

export interface VerifyPaymentResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Amount in minor units */
  amount: number;
  /** Chapa internal reference */
  chapaRef?: string;
  /** Currency code */
  currency: string;
  /** Payment method used */
  paymentMethod?: string;
  /** Plan name */
  planName: string;
  /** Billing period */
  planPeriod: string;
  /** Payment status */
  status: string;
  /** Transaction reference */
  txRef: string;
  /** Verification timestamp */
  verifiedAt?: string;
}
